// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: federation.sql

package db_postgres

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const consumeFederatedLoginAttempt = `-- name: ConsumeFederatedLoginAttempt :one
UPDATE federated_login_attempts SET consumed_at=$3
WHERE tenant_id=$1 AND state=$2 AND consumed_at IS NULL AND expires_at>$3
RETURNING state,tenant_id,provider_id,protocol,COALESCE(nonce,'') AS nonce,COALESCE(pkce_verifier,'') AS pkce_verifier,
  COALESCE(request_id,'') AS request_id,COALESCE(return_to,'') AS return_to,COALESCE(link_user_id::text,'') AS link_user_id,
  created_at,expires_at,consumed_at
`

type ConsumeFederatedLoginAttemptParams struct {
	TenantID   string
	State      string
	ConsumedAt pgtype.Timestamptz
}

type ConsumeFederatedLoginAttemptRow struct {
	State        string
	TenantID     string
	ProviderID   string
	Protocol     string
	Nonce        string
	PkceVerifier string
	RequestID    string
	ReturnTo     string
	LinkUserID   interface{}
	CreatedAt    time.Time
	ExpiresAt    time.Time
	ConsumedAt   pgtype.Timestamptz
}

func (q *Queries) ConsumeFederatedLoginAttempt(ctx context.Context, arg ConsumeFederatedLoginAttemptParams) (*ConsumeFederatedLoginAttemptRow, error) {
	row := q.db.QueryRow(ctx, consumeFederatedLoginAttempt, arg.TenantID, arg.State, arg.ConsumedAt)
	var i ConsumeFederatedLoginAttemptRow
	err := row.Scan(
		&i.State,
		&i.TenantID,
		&i.ProviderID,
		&i.Protocol,
		&i.Nonce,
		&i.PkceVerifier,
		&i.RequestID,
		&i.ReturnTo,
		&i.LinkUserID,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.ConsumedAt,
	)
	return &i, err
}

const countIdentityProviderConnectionsPendingSecretReencryption = `-- name: CountIdentityProviderConnectionsPendingSecretReencryption :one
SELECT count(*) FROM identity_provider_connections
WHERE tenant_id = $1
  AND (secret_reference IS NOT NULL OR secret_ciphertext IS NOT NULL)
  AND (secret_key_version IS NULL OR secret_key_version <> $2)
`

type CountIdentityProviderConnectionsPendingSecretReencryptionParams struct {
	TenantID         string
	SecretKeyVersion pgtype.Int4
}

func (q *Queries) CountIdentityProviderConnectionsPendingSecretReencryption(ctx context.Context, arg CountIdentityProviderConnectionsPendingSecretReencryptionParams) (int64, error) {
	row := q.db.QueryRow(ctx, countIdentityProviderConnectionsPendingSecretReencryption, arg.TenantID, arg.SecretKeyVersion)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createFederatedIdentity = `-- name: CreateFederatedIdentity :exec
INSERT INTO federated_identities
  (tenant_id,provider_id,external_subject,local_user_id,linked_at,last_login_at)
VALUES ($1,$2,$3,$4,$5,$6)
`

type CreateFederatedIdentityParams struct {
	TenantID        string
	ProviderID      string
	ExternalSubject string
	LocalUserID     string
	LinkedAt        time.Time
	LastLoginAt     pgtype.Timestamptz
}

func (q *Queries) CreateFederatedIdentity(ctx context.Context, arg CreateFederatedIdentityParams) error {
	_, err := q.db.Exec(ctx, createFederatedIdentity,
		arg.TenantID,
		arg.ProviderID,
		arg.ExternalSubject,
		arg.LocalUserID,
		arg.LinkedAt,
		arg.LastLoginAt,
	)
	return err
}

const deleteExpiredReplays = `-- name: DeleteExpiredReplays :exec
DELETE FROM federated_response_replays
WHERE tenant_id=$1 AND response_id=$2 AND expires_at<=now()
`

type DeleteExpiredReplaysParams struct {
	TenantID   string
	ResponseID string
}

func (q *Queries) DeleteExpiredReplays(ctx context.Context, arg DeleteExpiredReplaysParams) error {
	_, err := q.db.Exec(ctx, deleteExpiredReplays, arg.TenantID, arg.ResponseID)
	return err
}

const deleteFederatedIdentity = `-- name: DeleteFederatedIdentity :exec
DELETE FROM federated_identities
WHERE tenant_id=$1 AND provider_id=$2 AND local_user_id=$3
`

type DeleteFederatedIdentityParams struct {
	TenantID    string
	ProviderID  string
	LocalUserID string
}

func (q *Queries) DeleteFederatedIdentity(ctx context.Context, arg DeleteFederatedIdentityParams) error {
	_, err := q.db.Exec(ctx, deleteFederatedIdentity, arg.TenantID, arg.ProviderID, arg.LocalUserID)
	return err
}

const deleteIdentityProviderConnection = `-- name: DeleteIdentityProviderConnection :exec
DELETE FROM identity_provider_connections WHERE tenant_id=$1 AND id=$2
`

type DeleteIdentityProviderConnectionParams struct {
	TenantID string
	ID       string
}

func (q *Queries) DeleteIdentityProviderConnection(ctx context.Context, arg DeleteIdentityProviderConnectionParams) error {
	_, err := q.db.Exec(ctx, deleteIdentityProviderConnection, arg.TenantID, arg.ID)
	return err
}

const findFederatedIdentityBySubject = `-- name: FindFederatedIdentityBySubject :one
SELECT tenant_id,provider_id,external_subject,local_user_id,linked_at,last_login_at
FROM federated_identities WHERE tenant_id=$1 AND provider_id=$2 AND external_subject=$3
`

type FindFederatedIdentityBySubjectParams struct {
	TenantID        string
	ProviderID      string
	ExternalSubject string
}

func (q *Queries) FindFederatedIdentityBySubject(ctx context.Context, arg FindFederatedIdentityBySubjectParams) (*FederatedIdentity, error) {
	row := q.db.QueryRow(ctx, findFederatedIdentityBySubject, arg.TenantID, arg.ProviderID, arg.ExternalSubject)
	var i FederatedIdentity
	err := row.Scan(
		&i.TenantID,
		&i.ProviderID,
		&i.ExternalSubject,
		&i.LocalUserID,
		&i.LinkedAt,
		&i.LastLoginAt,
	)
	return &i, err
}

const findFederatedIdentityByUserProvider = `-- name: FindFederatedIdentityByUserProvider :one
SELECT tenant_id,provider_id,external_subject,local_user_id,linked_at,last_login_at
FROM federated_identities WHERE tenant_id=$1 AND provider_id=$2 AND local_user_id=$3
`

type FindFederatedIdentityByUserProviderParams struct {
	TenantID    string
	ProviderID  string
	LocalUserID string
}

func (q *Queries) FindFederatedIdentityByUserProvider(ctx context.Context, arg FindFederatedIdentityByUserProviderParams) (*FederatedIdentity, error) {
	row := q.db.QueryRow(ctx, findFederatedIdentityByUserProvider, arg.TenantID, arg.ProviderID, arg.LocalUserID)
	var i FederatedIdentity
	err := row.Scan(
		&i.TenantID,
		&i.ProviderID,
		&i.ExternalSubject,
		&i.LocalUserID,
		&i.LinkedAt,
		&i.LastLoginAt,
	)
	return &i, err
}

const findIdentityProviderConnection = `-- name: FindIdentityProviderConnection :one
SELECT tenant_id, id, display_name, protocol, status, issuer,
COALESCE(client_id,'') AS client_id, COALESCE(secret_reference,'') AS secret_reference,
secret_key_version, secret_ciphertext,
COALESCE(authorization_endpoint,'') AS authorization_endpoint,
COALESCE(token_endpoint,'') AS token_endpoint, COALESCE(jwks_uri,'') AS jwks_uri, COALESCE(saml_sso_url,'') AS saml_sso_url,
COALESCE(saml_entity_id,'') AS saml_entity_id, saml_signing_certificates, claim_mapping, linking_policy,
jit_provisioning, allowed_email_domains, metadata_refreshed_at, created_at, updated_at
FROM identity_provider_connections WHERE tenant_id=$1 AND id=$2
`

type FindIdentityProviderConnectionParams struct {
	TenantID string
	ID       string
}

type FindIdentityProviderConnectionRow struct {
	TenantID                string
	ID                      string
	DisplayName             string
	Protocol                string
	Status                  string
	Issuer                  string
	ClientID                string
	SecretReference         string
	SecretKeyVersion        pgtype.Int4
	SecretCiphertext        []byte
	AuthorizationEndpoint   string
	TokenEndpoint           string
	JwksUri                 string
	SamlSsoUrl              string
	SamlEntityID            string
	SamlSigningCertificates []byte
	ClaimMapping            []byte
	LinkingPolicy           string
	JitProvisioning         bool
	AllowedEmailDomains     []byte
	MetadataRefreshedAt     pgtype.Timestamptz
	CreatedAt               time.Time
	UpdatedAt               time.Time
}

func (q *Queries) FindIdentityProviderConnection(ctx context.Context, arg FindIdentityProviderConnectionParams) (*FindIdentityProviderConnectionRow, error) {
	row := q.db.QueryRow(ctx, findIdentityProviderConnection, arg.TenantID, arg.ID)
	var i FindIdentityProviderConnectionRow
	err := row.Scan(
		&i.TenantID,
		&i.ID,
		&i.DisplayName,
		&i.Protocol,
		&i.Status,
		&i.Issuer,
		&i.ClientID,
		&i.SecretReference,
		&i.SecretKeyVersion,
		&i.SecretCiphertext,
		&i.AuthorizationEndpoint,
		&i.TokenEndpoint,
		&i.JwksUri,
		&i.SamlSsoUrl,
		&i.SamlEntityID,
		&i.SamlSigningCertificates,
		&i.ClaimMapping,
		&i.LinkingPolicy,
		&i.JitProvisioning,
		&i.AllowedEmailDomains,
		&i.MetadataRefreshedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const getFederatedLoginAttemptConsumedAt = `-- name: GetFederatedLoginAttemptConsumedAt :one
SELECT consumed_at FROM federated_login_attempts
WHERE tenant_id=$1 AND state=$2
`

type GetFederatedLoginAttemptConsumedAtParams struct {
	TenantID string
	State    string
}

func (q *Queries) GetFederatedLoginAttemptConsumedAt(ctx context.Context, arg GetFederatedLoginAttemptConsumedAtParams) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, getFederatedLoginAttemptConsumedAt, arg.TenantID, arg.State)
	var consumed_at pgtype.Timestamptz
	err := row.Scan(&consumed_at)
	return consumed_at, err
}

const listFederatedIdentitiesByUser = `-- name: ListFederatedIdentitiesByUser :many
SELECT tenant_id,provider_id,external_subject,local_user_id,linked_at,last_login_at
FROM federated_identities WHERE tenant_id=$1 AND local_user_id=$2 ORDER BY provider_id
`

type ListFederatedIdentitiesByUserParams struct {
	TenantID    string
	LocalUserID string
}

func (q *Queries) ListFederatedIdentitiesByUser(ctx context.Context, arg ListFederatedIdentitiesByUserParams) ([]*FederatedIdentity, error) {
	rows, err := q.db.Query(ctx, listFederatedIdentitiesByUser, arg.TenantID, arg.LocalUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*FederatedIdentity
	for rows.Next() {
		var i FederatedIdentity
		if err := rows.Scan(
			&i.TenantID,
			&i.ProviderID,
			&i.ExternalSubject,
			&i.LocalUserID,
			&i.LinkedAt,
			&i.LastLoginAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIdentityProviderConnections = `-- name: ListIdentityProviderConnections :many
SELECT tenant_id, id, display_name, protocol, status, issuer,
COALESCE(client_id,'') AS client_id, COALESCE(secret_reference,'') AS secret_reference,
secret_key_version, secret_ciphertext,
COALESCE(authorization_endpoint,'') AS authorization_endpoint,
COALESCE(token_endpoint,'') AS token_endpoint, COALESCE(jwks_uri,'') AS jwks_uri, COALESCE(saml_sso_url,'') AS saml_sso_url,
COALESCE(saml_entity_id,'') AS saml_entity_id, saml_signing_certificates, claim_mapping, linking_policy,
jit_provisioning, allowed_email_domains, metadata_refreshed_at, created_at, updated_at
FROM identity_provider_connections WHERE tenant_id=$1 ORDER BY display_name, id
`

type ListIdentityProviderConnectionsRow struct {
	TenantID                string
	ID                      string
	DisplayName             string
	Protocol                string
	Status                  string
	Issuer                  string
	ClientID                string
	SecretReference         string
	SecretKeyVersion        pgtype.Int4
	SecretCiphertext        []byte
	AuthorizationEndpoint   string
	TokenEndpoint           string
	JwksUri                 string
	SamlSsoUrl              string
	SamlEntityID            string
	SamlSigningCertificates []byte
	ClaimMapping            []byte
	LinkingPolicy           string
	JitProvisioning         bool
	AllowedEmailDomains     []byte
	MetadataRefreshedAt     pgtype.Timestamptz
	CreatedAt               time.Time
	UpdatedAt               time.Time
}

func (q *Queries) ListIdentityProviderConnections(ctx context.Context, tenantID string) ([]*ListIdentityProviderConnectionsRow, error) {
	rows, err := q.db.Query(ctx, listIdentityProviderConnections, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*ListIdentityProviderConnectionsRow
	for rows.Next() {
		var i ListIdentityProviderConnectionsRow
		if err := rows.Scan(
			&i.TenantID,
			&i.ID,
			&i.DisplayName,
			&i.Protocol,
			&i.Status,
			&i.Issuer,
			&i.ClientID,
			&i.SecretReference,
			&i.SecretKeyVersion,
			&i.SecretCiphertext,
			&i.AuthorizationEndpoint,
			&i.TokenEndpoint,
			&i.JwksUri,
			&i.SamlSsoUrl,
			&i.SamlEntityID,
			&i.SamlSigningCertificates,
			&i.ClaimMapping,
			&i.LinkingPolicy,
			&i.JitProvisioning,
			&i.AllowedEmailDomains,
			&i.MetadataRefreshedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIdentityProviderConnectionsPendingSecretReencryption = `-- name: ListIdentityProviderConnectionsPendingSecretReencryption :many
SELECT tenant_id, id, secret_reference, secret_key_version, secret_ciphertext
FROM identity_provider_connections
WHERE tenant_id = $1
  AND (secret_reference IS NOT NULL OR secret_ciphertext IS NOT NULL)
  AND (secret_key_version IS NULL OR secret_key_version <> $2)
ORDER BY id
LIMIT $3
`

type ListIdentityProviderConnectionsPendingSecretReencryptionParams struct {
	TenantID         string
	SecretKeyVersion pgtype.Int4
	Limit            int32
}

type ListIdentityProviderConnectionsPendingSecretReencryptionRow struct {
	TenantID         string
	ID               string
	SecretReference  pgtype.Text
	SecretKeyVersion pgtype.Int4
	SecretCiphertext []byte
}

// Rows with secret material (legacy env: reference or ciphertext) not yet on
// activeVersion: never-migrated legacy reference (secret_key_version NULL) or an
// older DEK version. Rows with no secret configured at all are excluded.
func (q *Queries) ListIdentityProviderConnectionsPendingSecretReencryption(ctx context.Context, arg ListIdentityProviderConnectionsPendingSecretReencryptionParams) ([]*ListIdentityProviderConnectionsPendingSecretReencryptionRow, error) {
	rows, err := q.db.Query(ctx, listIdentityProviderConnectionsPendingSecretReencryption, arg.TenantID, arg.SecretKeyVersion, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*ListIdentityProviderConnectionsPendingSecretReencryptionRow
	for rows.Next() {
		var i ListIdentityProviderConnectionsPendingSecretReencryptionRow
		if err := rows.Scan(
			&i.TenantID,
			&i.ID,
			&i.SecretReference,
			&i.SecretKeyVersion,
			&i.SecretCiphertext,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reserveReplay = `-- name: ReserveReplay :one
INSERT INTO federated_response_replays
  (tenant_id,response_id,expires_at) VALUES ($1,$2,$3)
ON CONFLICT DO NOTHING RETURNING response_id
`

type ReserveReplayParams struct {
	TenantID   string
	ResponseID string
	ExpiresAt  time.Time
}

func (q *Queries) ReserveReplay(ctx context.Context, arg ReserveReplayParams) (string, error) {
	row := q.db.QueryRow(ctx, reserveReplay, arg.TenantID, arg.ResponseID, arg.ExpiresAt)
	var response_id string
	err := row.Scan(&response_id)
	return response_id, err
}

const saveFederatedLoginAttempt = `-- name: SaveFederatedLoginAttempt :exec
INSERT INTO federated_login_attempts
  (tenant_id,state,provider_id,protocol,nonce,pkce_verifier,request_id,return_to,link_user_id,
   created_at,expires_at,consumed_at)
VALUES ($1,$2,$3,$4,NULLIF($5::text,''),NULLIF($6::text,''),NULLIF($7::text,''),NULLIF($8::text,''),NULLIF($9::text,'')::uuid,
  $10,$11,$12)
`

type SaveFederatedLoginAttemptParams struct {
	TenantID   string
	State      string
	ProviderID string
	Protocol   string
	Column5    string
	Column6    string
	Column7    string
	Column8    string
	Column9    string
	CreatedAt  time.Time
	ExpiresAt  time.Time
	ConsumedAt pgtype.Timestamptz
}

func (q *Queries) SaveFederatedLoginAttempt(ctx context.Context, arg SaveFederatedLoginAttemptParams) error {
	_, err := q.db.Exec(ctx, saveFederatedLoginAttempt,
		arg.TenantID,
		arg.State,
		arg.ProviderID,
		arg.Protocol,
		arg.Column5,
		arg.Column6,
		arg.Column7,
		arg.Column8,
		arg.Column9,
		arg.CreatedAt,
		arg.ExpiresAt,
		arg.ConsumedAt,
	)
	return err
}

const saveIdentityProviderConnection = `-- name: SaveIdentityProviderConnection :exec
INSERT INTO identity_provider_connections (
  tenant_id, id, display_name, protocol, status, issuer, client_id, secret_reference,
  secret_key_version, secret_ciphertext,
  authorization_endpoint, token_endpoint, jwks_uri, saml_sso_url, saml_entity_id,
  saml_signing_certificates, claim_mapping, linking_policy, jit_provisioning,
  allowed_email_domains, metadata_refreshed_at, created_at, updated_at
) VALUES ($1,$2,$3,$4,$5,$6,NULLIF($7::text,''),NULLIF($8::text,''),$9,$10,NULLIF($11::text,''),
  NULLIF($12::text,''),NULLIF($13::text,''),NULLIF($14::text,''),NULLIF($15::text,''),
  $16,$17,$18,$19,$20,$21,$22,$23)
ON CONFLICT (id) DO UPDATE SET
  display_name=EXCLUDED.display_name, protocol=EXCLUDED.protocol, status=EXCLUDED.status,
  issuer=EXCLUDED.issuer, client_id=EXCLUDED.client_id,
  secret_reference=EXCLUDED.secret_reference,
  secret_key_version=EXCLUDED.secret_key_version, secret_ciphertext=EXCLUDED.secret_ciphertext,
  authorization_endpoint=EXCLUDED.authorization_endpoint, token_endpoint=EXCLUDED.token_endpoint,
  jwks_uri=EXCLUDED.jwks_uri, saml_sso_url=EXCLUDED.saml_sso_url,
  saml_entity_id=EXCLUDED.saml_entity_id,
  saml_signing_certificates=EXCLUDED.saml_signing_certificates,
  claim_mapping=EXCLUDED.claim_mapping, linking_policy=EXCLUDED.linking_policy,
  jit_provisioning=EXCLUDED.jit_provisioning, allowed_email_domains=EXCLUDED.allowed_email_domains,
  metadata_refreshed_at=EXCLUDED.metadata_refreshed_at, updated_at=EXCLUDED.updated_at
`

type SaveIdentityProviderConnectionParams struct {
	TenantID                string
	ID                      string
	DisplayName             string
	Protocol                string
	Status                  string
	Issuer                  string
	Column7                 string
	Column8                 string
	SecretKeyVersion        pgtype.Int4
	SecretCiphertext        []byte
	Column11                string
	Column12                string
	Column13                string
	Column14                string
	Column15                string
	SamlSigningCertificates []byte
	ClaimMapping            []byte
	LinkingPolicy           string
	JitProvisioning         bool
	AllowedEmailDomains     []byte
	MetadataRefreshedAt     pgtype.Timestamptz
	CreatedAt               time.Time
	UpdatedAt               time.Time
}

// secret_reference/secret_key_version/secret_ciphertext are always written as an
// authoritative trio computed by the Go layer: the caller already resolved
// "keep the existing secret unchanged" by copying the previous value forward, so this
// query never needs to fall back to the stored row for those three columns.
func (q *Queries) SaveIdentityProviderConnection(ctx context.Context, arg SaveIdentityProviderConnectionParams) error {
	_, err := q.db.Exec(ctx, saveIdentityProviderConnection,
		arg.TenantID,
		arg.ID,
		arg.DisplayName,
		arg.Protocol,
		arg.Status,
		arg.Issuer,
		arg.Column7,
		arg.Column8,
		arg.SecretKeyVersion,
		arg.SecretCiphertext,
		arg.Column11,
		arg.Column12,
		arg.Column13,
		arg.Column14,
		arg.Column15,
		arg.SamlSigningCertificates,
		arg.ClaimMapping,
		arg.LinkingPolicy,
		arg.JitProvisioning,
		arg.AllowedEmailDomains,
		arg.MetadataRefreshedAt,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const updateIdentityProviderConnectionSecretCiphertext = `-- name: UpdateIdentityProviderConnectionSecretCiphertext :exec
UPDATE identity_provider_connections
SET secret_reference = NULL, secret_key_version = $3, secret_ciphertext = $4, updated_at = now()
WHERE tenant_id = $1 AND id = $2
`

type UpdateIdentityProviderConnectionSecretCiphertextParams struct {
	TenantID         string
	ID               string
	SecretKeyVersion pgtype.Int4
	SecretCiphertext []byte
}

// Writes back a (re-)encrypted secret and always clears the legacy plaintext
// secret_reference column, mirroring UpdateMfaFactorCiphertext.
func (q *Queries) UpdateIdentityProviderConnectionSecretCiphertext(ctx context.Context, arg UpdateIdentityProviderConnectionSecretCiphertextParams) error {
	_, err := q.db.Exec(ctx, updateIdentityProviderConnectionSecretCiphertext,
		arg.TenantID,
		arg.ID,
		arg.SecretKeyVersion,
		arg.SecretCiphertext,
	)
	return err
}
