// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package salts_postgres

import (
	"context"
)

type Querier interface {
	FindTenantCorrelationSalt(ctx context.Context, tenantID string) ([]byte, error)
	InsertTenantCorrelationSalt(ctx context.Context, arg InsertTenantCorrelationSaltParams) error
}

var _ Querier = (*Queries)(nil)
