// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tenant_correlation_salts.sql

package salts_postgres

import (
	"context"
)

const findTenantCorrelationSalt = `-- name: FindTenantCorrelationSalt :one
SELECT salt FROM tenant_correlation_salts WHERE tenant_id = $1
`

func (q *Queries) FindTenantCorrelationSalt(ctx context.Context, tenantID string) ([]byte, error) {
	row := q.db.QueryRow(ctx, findTenantCorrelationSalt, tenantID)
	var salt []byte
	err := row.Scan(&salt)
	return salt, err
}

const insertTenantCorrelationSalt = `-- name: InsertTenantCorrelationSalt :exec
INSERT INTO tenant_correlation_salts (tenant_id, salt) VALUES ($1, $2) ON CONFLICT (tenant_id) DO NOTHING
`

type InsertTenantCorrelationSaltParams struct {
	TenantID string
	Salt     []byte
}

func (q *Queries) InsertTenantCorrelationSalt(ctx context.Context, arg InsertTenantCorrelationSaltParams) error {
	_, err := q.db.Exec(ctx, insertTenantCorrelationSalt, arg.TenantID, arg.Salt)
	return err
}
