// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db_postgres

import (
	"context"
)

type Querier interface {
	DeleteExpiredWebauthnSessionsBatch(ctx context.Context, arg DeleteExpiredWebauthnSessionsBatchParams) (int64, error)
	DeleteWebAuthnCredential(ctx context.Context, arg DeleteWebAuthnCredentialParams) error
	DeleteWebAuthnCredentialsForSub(ctx context.Context, userID string) error
	GetWebAuthnCredentialByID(ctx context.Context, credentialID string) (*GetWebAuthnCredentialByIDRow, error)
	ListWebAuthnCredentialsBySub(ctx context.Context, userID string) ([]*ListWebAuthnCredentialsBySubRow, error)
	SaveWebauthnSession(ctx context.Context, arg SaveWebauthnSessionParams) error
	// GetDel 相当。live な行だけを一度きり取り出す。期限切れ / 未存在は 0 行 (ErrNoRows → nil)。
	TakeWebauthnSession(ctx context.Context, arg TakeWebauthnSessionParams) ([]byte, error)
	UpdateWebAuthnCredentialSignCount(ctx context.Context, arg UpdateWebAuthnCredentialSignCountParams) error
	UpsertWebAuthnCredential(ctx context.Context, arg UpsertWebAuthnCredentialParams) error
}

var _ Querier = (*Queries)(nil)
