// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: webauthn_session_store.sql

package db_postgres

import (
	"context"
	"time"
)

const deleteExpiredWebauthnSessionsBatch = `-- name: DeleteExpiredWebauthnSessionsBatch :execrows
DELETE FROM webauthn_sessions AS o
WHERE (o.tenant_id, o.session_key) IN (
    SELECT s.tenant_id, s.session_key
    FROM webauthn_sessions AS s
    WHERE s.expires_at < $1
    LIMIT $2
)
`

type DeleteExpiredWebauthnSessionsBatchParams struct {
	Cutoff     time.Time
	BatchLimit int32
}

func (q *Queries) DeleteExpiredWebauthnSessionsBatch(ctx context.Context, arg DeleteExpiredWebauthnSessionsBatchParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredWebauthnSessionsBatch, arg.Cutoff, arg.BatchLimit)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const saveWebauthnSession = `-- name: SaveWebauthnSession :exec
INSERT INTO webauthn_sessions (tenant_id, session_key, data, expires_at)
VALUES ($1, $2, $3, $4)
ON CONFLICT (tenant_id, session_key) DO UPDATE
    SET data = EXCLUDED.data, expires_at = EXCLUDED.expires_at, updated_at = now()
`

type SaveWebauthnSessionParams struct {
	TenantID   string
	SessionKey string
	Data       []byte
	ExpiresAt  time.Time
}

func (q *Queries) SaveWebauthnSession(ctx context.Context, arg SaveWebauthnSessionParams) error {
	_, err := q.db.Exec(ctx, saveWebauthnSession,
		arg.TenantID,
		arg.SessionKey,
		arg.Data,
		arg.ExpiresAt,
	)
	return err
}

const takeWebauthnSession = `-- name: TakeWebauthnSession :one
DELETE FROM webauthn_sessions
WHERE tenant_id = $1 AND session_key = $2 AND expires_at > $3
RETURNING data
`

type TakeWebauthnSessionParams struct {
	TenantID   string
	SessionKey string
	Now        time.Time
}

// GetDel 相当。live な行だけを一度きり取り出す。期限切れ / 未存在は 0 行 (ErrNoRows → nil)。
func (q *Queries) TakeWebauthnSession(ctx context.Context, arg TakeWebauthnSessionParams) ([]byte, error) {
	row := q.db.QueryRow(ctx, takeWebauthnSession, arg.TenantID, arg.SessionKey, arg.Now)
	var data []byte
	err := row.Scan(&data)
	return data, err
}
