// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: webauthn_credentials.sql

package db_postgres

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteWebAuthnCredential = `-- name: DeleteWebAuthnCredential :exec
DELETE FROM webauthn_credentials WHERE user_id = $1 AND credential_id = $2
`

type DeleteWebAuthnCredentialParams struct {
	UserID       string
	CredentialID string
}

func (q *Queries) DeleteWebAuthnCredential(ctx context.Context, arg DeleteWebAuthnCredentialParams) error {
	_, err := q.db.Exec(ctx, deleteWebAuthnCredential, arg.UserID, arg.CredentialID)
	return err
}

const deleteWebAuthnCredentialsForSub = `-- name: DeleteWebAuthnCredentialsForSub :exec
DELETE FROM webauthn_credentials WHERE user_id = $1
`

func (q *Queries) DeleteWebAuthnCredentialsForSub(ctx context.Context, userID string) error {
	_, err := q.db.Exec(ctx, deleteWebAuthnCredentialsForSub, userID)
	return err
}

const getWebAuthnCredentialByID = `-- name: GetWebAuthnCredentialByID :one
SELECT credential_id, user_id, public_key, sign_count, transports, aaguid, label,
    backup_eligible, backup_state, created_at, last_used_at
FROM webauthn_credentials
WHERE credential_id = $1
`

type GetWebAuthnCredentialByIDRow struct {
	CredentialID   string
	UserID         string
	PublicKey      string
	SignCount      int64
	Transports     []string
	Aaguid         pgtype.Text
	Label          pgtype.Text
	BackupEligible bool
	BackupState    bool
	CreatedAt      time.Time
	LastUsedAt     pgtype.Timestamptz
}

func (q *Queries) GetWebAuthnCredentialByID(ctx context.Context, credentialID string) (*GetWebAuthnCredentialByIDRow, error) {
	row := q.db.QueryRow(ctx, getWebAuthnCredentialByID, credentialID)
	var i GetWebAuthnCredentialByIDRow
	err := row.Scan(
		&i.CredentialID,
		&i.UserID,
		&i.PublicKey,
		&i.SignCount,
		&i.Transports,
		&i.Aaguid,
		&i.Label,
		&i.BackupEligible,
		&i.BackupState,
		&i.CreatedAt,
		&i.LastUsedAt,
	)
	return &i, err
}

const listWebAuthnCredentialsBySub = `-- name: ListWebAuthnCredentialsBySub :many
SELECT credential_id, user_id, public_key, sign_count, transports, aaguid, label,
    backup_eligible, backup_state, created_at, last_used_at
FROM webauthn_credentials
WHERE user_id = $1
ORDER BY created_at
`

type ListWebAuthnCredentialsBySubRow struct {
	CredentialID   string
	UserID         string
	PublicKey      string
	SignCount      int64
	Transports     []string
	Aaguid         pgtype.Text
	Label          pgtype.Text
	BackupEligible bool
	BackupState    bool
	CreatedAt      time.Time
	LastUsedAt     pgtype.Timestamptz
}

func (q *Queries) ListWebAuthnCredentialsBySub(ctx context.Context, userID string) ([]*ListWebAuthnCredentialsBySubRow, error) {
	rows, err := q.db.Query(ctx, listWebAuthnCredentialsBySub, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*ListWebAuthnCredentialsBySubRow
	for rows.Next() {
		var i ListWebAuthnCredentialsBySubRow
		if err := rows.Scan(
			&i.CredentialID,
			&i.UserID,
			&i.PublicKey,
			&i.SignCount,
			&i.Transports,
			&i.Aaguid,
			&i.Label,
			&i.BackupEligible,
			&i.BackupState,
			&i.CreatedAt,
			&i.LastUsedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateWebAuthnCredentialSignCount = `-- name: UpdateWebAuthnCredentialSignCount :exec
UPDATE webauthn_credentials
SET sign_count = $2, last_used_at = $3, updated_at = now()
WHERE credential_id = $1
`

type UpdateWebAuthnCredentialSignCountParams struct {
	CredentialID string
	SignCount    int64
	LastUsedAt   pgtype.Timestamptz
}

func (q *Queries) UpdateWebAuthnCredentialSignCount(ctx context.Context, arg UpdateWebAuthnCredentialSignCountParams) error {
	_, err := q.db.Exec(ctx, updateWebAuthnCredentialSignCount, arg.CredentialID, arg.SignCount, arg.LastUsedAt)
	return err
}

const upsertWebAuthnCredential = `-- name: UpsertWebAuthnCredential :exec
INSERT INTO webauthn_credentials (credential_id, user_id, public_key, sign_count, transports, aaguid, label,
    backup_eligible, backup_state, created_at, last_used_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
ON CONFLICT (credential_id) DO UPDATE SET
    sign_count = EXCLUDED.sign_count,
    label = EXCLUDED.label,
    last_used_at = EXCLUDED.last_used_at,
    updated_at = now()
`

type UpsertWebAuthnCredentialParams struct {
	CredentialID   string
	UserID         string
	PublicKey      string
	SignCount      int64
	Transports     []string
	Aaguid         pgtype.Text
	Label          pgtype.Text
	BackupEligible bool
	BackupState    bool
	CreatedAt      time.Time
	LastUsedAt     pgtype.Timestamptz
}

func (q *Queries) UpsertWebAuthnCredential(ctx context.Context, arg UpsertWebAuthnCredentialParams) error {
	_, err := q.db.Exec(ctx, upsertWebAuthnCredential,
		arg.CredentialID,
		arg.UserID,
		arg.PublicKey,
		arg.SignCount,
		arg.Transports,
		arg.Aaguid,
		arg.Label,
		arg.BackupEligible,
		arg.BackupState,
		arg.CreatedAt,
		arg.LastUsedAt,
	)
	return err
}
