// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db_postgres

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type AgentWorkloadBinding struct {
	ID             string
	TenantID       string
	TrustBundleID  string
	SubjectPattern string
	AgentID        string
	Status         string
	CreatedAt      time.Time
	UpdatedAt      time.Time
	DisabledAt     pgtype.Timestamptz
}

type WorkloadTrustBundle struct {
	ID                        string
	TenantID                  string
	Name                      string
	TrustDomain               string
	Issuer                    string
	JwksUri                   pgtype.Text
	Jwks                      []byte
	AcceptedAudiences         []byte
	MaxSubjectTokenTtlSeconds int32
	Status                    string
	CreatedAt                 time.Time
	UpdatedAt                 time.Time
	JwksCachedAt              pgtype.Timestamptz
}
