// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db_postgres

import (
	"context"
)

type Querier interface {
	DeleteAgentWorkloadBinding(ctx context.Context, arg DeleteAgentWorkloadBindingParams) error
	DeleteWorkloadTrustBundle(ctx context.Context, arg DeleteWorkloadTrustBundleParams) error
	FindAgentWorkloadBindingByID(ctx context.Context, arg FindAgentWorkloadBindingByIDParams) (*AgentWorkloadBinding, error)
	FindWorkloadTrustBundleByID(ctx context.Context, arg FindWorkloadTrustBundleByIDParams) (*WorkloadTrustBundle, error)
	FindWorkloadTrustBundleByIssuer(ctx context.Context, arg FindWorkloadTrustBundleByIssuerParams) (*WorkloadTrustBundle, error)
	ListAgentWorkloadBindingsByTrustBundle(ctx context.Context, arg ListAgentWorkloadBindingsByTrustBundleParams) ([]*AgentWorkloadBinding, error)
	ListWorkloadTrustBundlesByTenant(ctx context.Context, tenantID string) ([]*WorkloadTrustBundle, error)
	SaveAgentWorkloadBinding(ctx context.Context, arg SaveAgentWorkloadBindingParams) error
	SaveWorkloadTrustBundle(ctx context.Context, arg SaveWorkloadTrustBundleParams) error
}

var _ Querier = (*Queries)(nil)
