// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"context"
)

type Querier interface {
	DeleteWebAuthnCredential(ctx context.Context, arg DeleteWebAuthnCredentialParams) error
	DeleteWebAuthnCredentialsForSub(ctx context.Context, userID string) error
	GetWebAuthnCredentialByID(ctx context.Context, credentialID string) (*GetWebAuthnCredentialByIDRow, error)
	ListWebAuthnCredentialsBySub(ctx context.Context, userID string) ([]*ListWebAuthnCredentialsBySubRow, error)
	UpdateWebAuthnCredentialSignCount(ctx context.Context, arg UpdateWebAuthnCredentialSignCountParams) error
	UpsertWebAuthnCredential(ctx context.Context, arg UpsertWebAuthnCredentialParams) error
}

var _ Querier = (*Queries)(nil)
