// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db_postgres

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type TrustedDevice struct {
	ID           string
	TenantID     string
	UserID       string
	Selector     string
	VerifierHash string
	Label        pgtype.Text
	CreatedAt    time.Time
	LastUsedAt   time.Time
	ExpiresAt    time.Time
	RevokedAt    pgtype.Timestamptz
	RevokeReason pgtype.Text
}
