// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db_postgres

import (
	"context"
)

type Querier interface {
	DeleteTrustedDevicesForSub(ctx context.Context, userID string) error
	FindTrustedDeviceByID(ctx context.Context, arg FindTrustedDeviceByIDParams) (*TrustedDevice, error)
	FindTrustedDeviceBySelector(ctx context.Context, arg FindTrustedDeviceBySelectorParams) (*TrustedDevice, error)
	ListActiveTrustedDevicesByUser(ctx context.Context, arg ListActiveTrustedDevicesByUserParams) ([]*TrustedDevice, error)
	RevokeTrustedDevicesForUser(ctx context.Context, arg RevokeTrustedDevicesForUserParams) ([]*TrustedDevice, error)
	UpsertTrustedDevice(ctx context.Context, arg UpsertTrustedDeviceParams) error
}

var _ Querier = (*Queries)(nil)
