// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: trusted_devices.sql

package db_postgres

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteTrustedDevicesForSub = `-- name: DeleteTrustedDevicesForSub :exec
DELETE FROM trusted_devices WHERE user_id = $1
`

func (q *Queries) DeleteTrustedDevicesForSub(ctx context.Context, userID string) error {
	_, err := q.db.Exec(ctx, deleteTrustedDevicesForSub, userID)
	return err
}

const findTrustedDeviceByID = `-- name: FindTrustedDeviceByID :one
SELECT id, tenant_id, user_id, selector, verifier_hash, label,
       created_at, last_used_at, expires_at, revoked_at, revoke_reason
FROM trusted_devices
WHERE tenant_id = $1 AND user_id = $2 AND id = $3
`

type FindTrustedDeviceByIDParams struct {
	TenantID string
	UserID   string
	ID       string
}

func (q *Queries) FindTrustedDeviceByID(ctx context.Context, arg FindTrustedDeviceByIDParams) (*TrustedDevice, error) {
	row := q.db.QueryRow(ctx, findTrustedDeviceByID, arg.TenantID, arg.UserID, arg.ID)
	var i TrustedDevice
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.Selector,
		&i.VerifierHash,
		&i.Label,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.RevokeReason,
	)
	return &i, err
}

const findTrustedDeviceBySelector = `-- name: FindTrustedDeviceBySelector :one
SELECT id, tenant_id, user_id, selector, verifier_hash, label,
       created_at, last_used_at, expires_at, revoked_at, revoke_reason
FROM trusted_devices
WHERE tenant_id = $1 AND selector = $2
`

type FindTrustedDeviceBySelectorParams struct {
	TenantID string
	Selector string
}

func (q *Queries) FindTrustedDeviceBySelector(ctx context.Context, arg FindTrustedDeviceBySelectorParams) (*TrustedDevice, error) {
	row := q.db.QueryRow(ctx, findTrustedDeviceBySelector, arg.TenantID, arg.Selector)
	var i TrustedDevice
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.Selector,
		&i.VerifierHash,
		&i.Label,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.RevokeReason,
	)
	return &i, err
}

const listActiveTrustedDevicesByUser = `-- name: ListActiveTrustedDevicesByUser :many
SELECT id, tenant_id, user_id, selector, verifier_hash, label,
       created_at, last_used_at, expires_at, revoked_at, revoke_reason
FROM trusted_devices
WHERE tenant_id = $1 AND user_id = $2 AND revoked_at IS NULL AND expires_at > $3
ORDER BY last_used_at DESC
`

type ListActiveTrustedDevicesByUserParams struct {
	TenantID  string
	UserID    string
	ExpiresAt time.Time
}

func (q *Queries) ListActiveTrustedDevicesByUser(ctx context.Context, arg ListActiveTrustedDevicesByUserParams) ([]*TrustedDevice, error) {
	rows, err := q.db.Query(ctx, listActiveTrustedDevicesByUser, arg.TenantID, arg.UserID, arg.ExpiresAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*TrustedDevice
	for rows.Next() {
		var i TrustedDevice
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.UserID,
			&i.Selector,
			&i.VerifierHash,
			&i.Label,
			&i.CreatedAt,
			&i.LastUsedAt,
			&i.ExpiresAt,
			&i.RevokedAt,
			&i.RevokeReason,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeTrustedDevicesForUser = `-- name: RevokeTrustedDevicesForUser :many
UPDATE trusted_devices
SET revoked_at = $3, revoke_reason = $4
WHERE tenant_id = $1 AND user_id = $2 AND revoked_at IS NULL
RETURNING id, tenant_id, user_id, selector, verifier_hash, label,
          created_at, last_used_at, expires_at, revoked_at, revoke_reason
`

type RevokeTrustedDevicesForUserParams struct {
	TenantID     string
	UserID       string
	RevokedAt    pgtype.Timestamptz
	RevokeReason pgtype.Text
}

func (q *Queries) RevokeTrustedDevicesForUser(ctx context.Context, arg RevokeTrustedDevicesForUserParams) ([]*TrustedDevice, error) {
	rows, err := q.db.Query(ctx, revokeTrustedDevicesForUser,
		arg.TenantID,
		arg.UserID,
		arg.RevokedAt,
		arg.RevokeReason,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*TrustedDevice
	for rows.Next() {
		var i TrustedDevice
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.UserID,
			&i.Selector,
			&i.VerifierHash,
			&i.Label,
			&i.CreatedAt,
			&i.LastUsedAt,
			&i.ExpiresAt,
			&i.RevokedAt,
			&i.RevokeReason,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertTrustedDevice = `-- name: UpsertTrustedDevice :exec
INSERT INTO trusted_devices (
    id, tenant_id, user_id, selector, verifier_hash, label,
    created_at, last_used_at, expires_at, revoked_at, revoke_reason
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
ON CONFLICT (id) DO UPDATE SET
    selector = EXCLUDED.selector,
    verifier_hash = EXCLUDED.verifier_hash,
    label = EXCLUDED.label,
    last_used_at = EXCLUDED.last_used_at,
    expires_at = EXCLUDED.expires_at,
    revoked_at = EXCLUDED.revoked_at,
    revoke_reason = EXCLUDED.revoke_reason
`

type UpsertTrustedDeviceParams struct {
	ID           string
	TenantID     string
	UserID       string
	Selector     string
	VerifierHash string
	Label        pgtype.Text
	CreatedAt    time.Time
	LastUsedAt   time.Time
	ExpiresAt    time.Time
	RevokedAt    pgtype.Timestamptz
	RevokeReason pgtype.Text
}

func (q *Queries) UpsertTrustedDevice(ctx context.Context, arg UpsertTrustedDeviceParams) error {
	_, err := q.db.Exec(ctx, upsertTrustedDevice,
		arg.ID,
		arg.TenantID,
		arg.UserID,
		arg.Selector,
		arg.VerifierHash,
		arg.Label,
		arg.CreatedAt,
		arg.LastUsedAt,
		arg.ExpiresAt,
		arg.RevokedAt,
		arg.RevokeReason,
	)
	return err
}
