// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tenant_brandings.sql

package db_postgres

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const findTenantBrandingByTenant = `-- name: FindTenantBrandingByTenant :one
SELECT tenant_id, product_name, logo_object_key, logo_url, favicon_object_key, favicon_url,
       primary_color, accent_color, footer_link_1_label, footer_link_1_url,
       footer_link_2_label, footer_link_2_url, footer_text, created_at, updated_at
FROM tenant_brandings
WHERE tenant_id = $1
`

func (q *Queries) FindTenantBrandingByTenant(ctx context.Context, tenantID string) (*TenantBranding, error) {
	row := q.db.QueryRow(ctx, findTenantBrandingByTenant, tenantID)
	var i TenantBranding
	err := row.Scan(
		&i.TenantID,
		&i.ProductName,
		&i.LogoObjectKey,
		&i.LogoUrl,
		&i.FaviconObjectKey,
		&i.FaviconUrl,
		&i.PrimaryColor,
		&i.AccentColor,
		&i.FooterLink1Label,
		&i.FooterLink1Url,
		&i.FooterLink2Label,
		&i.FooterLink2Url,
		&i.FooterText,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const saveTenantBranding = `-- name: SaveTenantBranding :exec
INSERT INTO tenant_brandings (
    tenant_id, product_name, logo_object_key, logo_url, favicon_object_key, favicon_url,
    primary_color, accent_color, footer_link_1_label, footer_link_1_url,
    footer_link_2_label, footer_link_2_url, footer_text, created_at, updated_at
) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15)
ON CONFLICT (tenant_id) DO UPDATE SET
    product_name = EXCLUDED.product_name,
    logo_object_key = EXCLUDED.logo_object_key,
    logo_url = EXCLUDED.logo_url,
    favicon_object_key = EXCLUDED.favicon_object_key,
    favicon_url = EXCLUDED.favicon_url,
    primary_color = EXCLUDED.primary_color,
    accent_color = EXCLUDED.accent_color,
    footer_link_1_label = EXCLUDED.footer_link_1_label,
    footer_link_1_url = EXCLUDED.footer_link_1_url,
    footer_link_2_label = EXCLUDED.footer_link_2_label,
    footer_link_2_url = EXCLUDED.footer_link_2_url,
    footer_text = EXCLUDED.footer_text,
    updated_at = EXCLUDED.updated_at
`

type SaveTenantBrandingParams struct {
	TenantID         string
	ProductName      pgtype.Text
	LogoObjectKey    pgtype.Text
	LogoUrl          pgtype.Text
	FaviconObjectKey pgtype.Text
	FaviconUrl       pgtype.Text
	PrimaryColor     pgtype.Text
	AccentColor      pgtype.Text
	FooterLink1Label pgtype.Text
	FooterLink1Url   pgtype.Text
	FooterLink2Label pgtype.Text
	FooterLink2Url   pgtype.Text
	FooterText       pgtype.Text
	CreatedAt        time.Time
	UpdatedAt        time.Time
}

func (q *Queries) SaveTenantBranding(ctx context.Context, arg SaveTenantBrandingParams) error {
	_, err := q.db.Exec(ctx, saveTenantBranding,
		arg.TenantID,
		arg.ProductName,
		arg.LogoObjectKey,
		arg.LogoUrl,
		arg.FaviconObjectKey,
		arg.FaviconUrl,
		arg.PrimaryColor,
		arg.AccentColor,
		arg.FooterLink1Label,
		arg.FooterLink1Url,
		arg.FooterLink2Label,
		arg.FooterLink2Url,
		arg.FooterText,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}
