// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tenant_usages.sql

package db_postgres

import (
	"context"
)

const decrementTenantUsageActiveJobs = `-- name: DecrementTenantUsageActiveJobs :exec
UPDATE tenant_usages u SET active_jobs = GREATEST(0, u.active_jobs - $1::int) WHERE u.tenant_id = $2
`

type DecrementTenantUsageActiveJobsParams struct {
	Delta    int32
	TenantID string
}

func (q *Queries) DecrementTenantUsageActiveJobs(ctx context.Context, arg DecrementTenantUsageActiveJobsParams) error {
	_, err := q.db.Exec(ctx, decrementTenantUsageActiveJobs, arg.Delta, arg.TenantID)
	return err
}

const decrementTenantUsageActiveSessions = `-- name: DecrementTenantUsageActiveSessions :exec
UPDATE tenant_usages u SET active_sessions = GREATEST(0, u.active_sessions - $1::int) WHERE u.tenant_id = $2
`

type DecrementTenantUsageActiveSessionsParams struct {
	Delta    int32
	TenantID string
}

func (q *Queries) DecrementTenantUsageActiveSessions(ctx context.Context, arg DecrementTenantUsageActiveSessionsParams) error {
	_, err := q.db.Exec(ctx, decrementTenantUsageActiveSessions, arg.Delta, arg.TenantID)
	return err
}

const decrementTenantUsageAgents = `-- name: DecrementTenantUsageAgents :exec
UPDATE tenant_usages u SET agents = GREATEST(0, u.agents - $1::int) WHERE u.tenant_id = $2
`

type DecrementTenantUsageAgentsParams struct {
	Delta    int32
	TenantID string
}

func (q *Queries) DecrementTenantUsageAgents(ctx context.Context, arg DecrementTenantUsageAgentsParams) error {
	_, err := q.db.Exec(ctx, decrementTenantUsageAgents, arg.Delta, arg.TenantID)
	return err
}

const decrementTenantUsageApplications = `-- name: DecrementTenantUsageApplications :exec
UPDATE tenant_usages u SET applications = GREATEST(0, u.applications - $1::int) WHERE u.tenant_id = $2
`

type DecrementTenantUsageApplicationsParams struct {
	Delta    int32
	TenantID string
}

func (q *Queries) DecrementTenantUsageApplications(ctx context.Context, arg DecrementTenantUsageApplicationsParams) error {
	_, err := q.db.Exec(ctx, decrementTenantUsageApplications, arg.Delta, arg.TenantID)
	return err
}

const decrementTenantUsageAuditEventsRetained = `-- name: DecrementTenantUsageAuditEventsRetained :exec
UPDATE tenant_usages u SET audit_events_retained = GREATEST(0, u.audit_events_retained - $1::int) WHERE u.tenant_id = $2
`

type DecrementTenantUsageAuditEventsRetainedParams struct {
	Delta    int32
	TenantID string
}

func (q *Queries) DecrementTenantUsageAuditEventsRetained(ctx context.Context, arg DecrementTenantUsageAuditEventsRetainedParams) error {
	_, err := q.db.Exec(ctx, decrementTenantUsageAuditEventsRetained, arg.Delta, arg.TenantID)
	return err
}

const decrementTenantUsageConsents = `-- name: DecrementTenantUsageConsents :exec
UPDATE tenant_usages u SET consents = GREATEST(0, u.consents - $1::int) WHERE u.tenant_id = $2
`

type DecrementTenantUsageConsentsParams struct {
	Delta    int32
	TenantID string
}

func (q *Queries) DecrementTenantUsageConsents(ctx context.Context, arg DecrementTenantUsageConsentsParams) error {
	_, err := q.db.Exec(ctx, decrementTenantUsageConsents, arg.Delta, arg.TenantID)
	return err
}

const decrementTenantUsageExportArtifactsBytes = `-- name: DecrementTenantUsageExportArtifactsBytes :exec
UPDATE tenant_usages u SET export_artifacts_bytes = GREATEST(0, u.export_artifacts_bytes - $1::int) WHERE u.tenant_id = $2
`

type DecrementTenantUsageExportArtifactsBytesParams struct {
	Delta    int32
	TenantID string
}

func (q *Queries) DecrementTenantUsageExportArtifactsBytes(ctx context.Context, arg DecrementTenantUsageExportArtifactsBytesParams) error {
	_, err := q.db.Exec(ctx, decrementTenantUsageExportArtifactsBytes, arg.Delta, arg.TenantID)
	return err
}

const decrementTenantUsageGroups = `-- name: DecrementTenantUsageGroups :exec
UPDATE tenant_usages u SET groups = GREATEST(0, u.groups - $1::int) WHERE u.tenant_id = $2
`

type DecrementTenantUsageGroupsParams struct {
	Delta    int32
	TenantID string
}

func (q *Queries) DecrementTenantUsageGroups(ctx context.Context, arg DecrementTenantUsageGroupsParams) error {
	_, err := q.db.Exec(ctx, decrementTenantUsageGroups, arg.Delta, arg.TenantID)
	return err
}

const decrementTenantUsageOAuth2Clients = `-- name: DecrementTenantUsageOAuth2Clients :exec
UPDATE tenant_usages u SET oauth2_clients = GREATEST(0, u.oauth2_clients - $1::int) WHERE u.tenant_id = $2
`

type DecrementTenantUsageOAuth2ClientsParams struct {
	Delta    int32
	TenantID string
}

func (q *Queries) DecrementTenantUsageOAuth2Clients(ctx context.Context, arg DecrementTenantUsageOAuth2ClientsParams) error {
	_, err := q.db.Exec(ctx, decrementTenantUsageOAuth2Clients, arg.Delta, arg.TenantID)
	return err
}

const decrementTenantUsageSsfStreams = `-- name: DecrementTenantUsageSsfStreams :exec
UPDATE tenant_usages u SET ssf_streams = GREATEST(0, u.ssf_streams - $1::int) WHERE u.tenant_id = $2
`

type DecrementTenantUsageSsfStreamsParams struct {
	Delta    int32
	TenantID string
}

func (q *Queries) DecrementTenantUsageSsfStreams(ctx context.Context, arg DecrementTenantUsageSsfStreamsParams) error {
	_, err := q.db.Exec(ctx, decrementTenantUsageSsfStreams, arg.Delta, arg.TenantID)
	return err
}

const decrementTenantUsageUsers = `-- name: DecrementTenantUsageUsers :exec
UPDATE tenant_usages u SET users = GREATEST(0, u.users - $1::int) WHERE u.tenant_id = $2
`

type DecrementTenantUsageUsersParams struct {
	Delta    int32
	TenantID string
}

func (q *Queries) DecrementTenantUsageUsers(ctx context.Context, arg DecrementTenantUsageUsersParams) error {
	_, err := q.db.Exec(ctx, decrementTenantUsageUsers, arg.Delta, arg.TenantID)
	return err
}

const ensureTenantUsage = `-- name: EnsureTenantUsage :exec
INSERT INTO tenant_usages (tenant_id) VALUES ($1) ON CONFLICT DO NOTHING
`

func (q *Queries) EnsureTenantUsage(ctx context.Context, tenantID string) error {
	_, err := q.db.Exec(ctx, ensureTenantUsage, tenantID)
	return err
}

const incrementTenantUsageActiveJobs = `-- name: IncrementTenantUsageActiveJobs :one
UPDATE tenant_usages u
SET active_jobs = u.active_jobs + $1::int
WHERE u.tenant_id = $2
  AND COALESCE((SELECT q.active_jobs FROM tenant_quotas q WHERE q.tenant_id = u.tenant_id), $3::int) >= u.active_jobs + $1::int
RETURNING u.active_jobs
`

type IncrementTenantUsageActiveJobsParams struct {
	Delta        int32
	TenantID     string
	DefaultLimit int32
}

func (q *Queries) IncrementTenantUsageActiveJobs(ctx context.Context, arg IncrementTenantUsageActiveJobsParams) (int32, error) {
	row := q.db.QueryRow(ctx, incrementTenantUsageActiveJobs, arg.Delta, arg.TenantID, arg.DefaultLimit)
	var active_jobs int32
	err := row.Scan(&active_jobs)
	return active_jobs, err
}

const incrementTenantUsageActiveSessions = `-- name: IncrementTenantUsageActiveSessions :one
UPDATE tenant_usages u
SET active_sessions = u.active_sessions + $1::int
WHERE u.tenant_id = $2
  AND COALESCE((SELECT q.active_sessions FROM tenant_quotas q WHERE q.tenant_id = u.tenant_id), $3::int) >= u.active_sessions + $1::int
RETURNING u.active_sessions
`

type IncrementTenantUsageActiveSessionsParams struct {
	Delta        int32
	TenantID     string
	DefaultLimit int32
}

func (q *Queries) IncrementTenantUsageActiveSessions(ctx context.Context, arg IncrementTenantUsageActiveSessionsParams) (int32, error) {
	row := q.db.QueryRow(ctx, incrementTenantUsageActiveSessions, arg.Delta, arg.TenantID, arg.DefaultLimit)
	var active_sessions int32
	err := row.Scan(&active_sessions)
	return active_sessions, err
}

const incrementTenantUsageAgents = `-- name: IncrementTenantUsageAgents :one
UPDATE tenant_usages u
SET agents = u.agents + $1::int
WHERE u.tenant_id = $2
  AND COALESCE((SELECT q.agents FROM tenant_quotas q WHERE q.tenant_id = u.tenant_id), $3::int) >= u.agents + $1::int
RETURNING u.agents
`

type IncrementTenantUsageAgentsParams struct {
	Delta        int32
	TenantID     string
	DefaultLimit int32
}

func (q *Queries) IncrementTenantUsageAgents(ctx context.Context, arg IncrementTenantUsageAgentsParams) (int32, error) {
	row := q.db.QueryRow(ctx, incrementTenantUsageAgents, arg.Delta, arg.TenantID, arg.DefaultLimit)
	var agents int32
	err := row.Scan(&agents)
	return agents, err
}

const incrementTenantUsageApplications = `-- name: IncrementTenantUsageApplications :one
UPDATE tenant_usages u
SET applications = u.applications + $1::int
WHERE u.tenant_id = $2
  AND COALESCE((SELECT q.applications FROM tenant_quotas q WHERE q.tenant_id = u.tenant_id), $3::int) >= u.applications + $1::int
RETURNING u.applications
`

type IncrementTenantUsageApplicationsParams struct {
	Delta        int32
	TenantID     string
	DefaultLimit int32
}

func (q *Queries) IncrementTenantUsageApplications(ctx context.Context, arg IncrementTenantUsageApplicationsParams) (int32, error) {
	row := q.db.QueryRow(ctx, incrementTenantUsageApplications, arg.Delta, arg.TenantID, arg.DefaultLimit)
	var applications int32
	err := row.Scan(&applications)
	return applications, err
}

const incrementTenantUsageAuditEventsRetained = `-- name: IncrementTenantUsageAuditEventsRetained :one
UPDATE tenant_usages u
SET audit_events_retained = u.audit_events_retained + $1::int
WHERE u.tenant_id = $2
  AND COALESCE((SELECT q.audit_events_retained FROM tenant_quotas q WHERE q.tenant_id = u.tenant_id), $3::int) >= u.audit_events_retained + $1::int
RETURNING u.audit_events_retained
`

type IncrementTenantUsageAuditEventsRetainedParams struct {
	Delta        int32
	TenantID     string
	DefaultLimit int32
}

func (q *Queries) IncrementTenantUsageAuditEventsRetained(ctx context.Context, arg IncrementTenantUsageAuditEventsRetainedParams) (int32, error) {
	row := q.db.QueryRow(ctx, incrementTenantUsageAuditEventsRetained, arg.Delta, arg.TenantID, arg.DefaultLimit)
	var audit_events_retained int32
	err := row.Scan(&audit_events_retained)
	return audit_events_retained, err
}

const incrementTenantUsageConsents = `-- name: IncrementTenantUsageConsents :one
UPDATE tenant_usages u
SET consents = u.consents + $1::int
WHERE u.tenant_id = $2
  AND COALESCE((SELECT q.consents FROM tenant_quotas q WHERE q.tenant_id = u.tenant_id), $3::int) >= u.consents + $1::int
RETURNING u.consents
`

type IncrementTenantUsageConsentsParams struct {
	Delta        int32
	TenantID     string
	DefaultLimit int32
}

func (q *Queries) IncrementTenantUsageConsents(ctx context.Context, arg IncrementTenantUsageConsentsParams) (int32, error) {
	row := q.db.QueryRow(ctx, incrementTenantUsageConsents, arg.Delta, arg.TenantID, arg.DefaultLimit)
	var consents int32
	err := row.Scan(&consents)
	return consents, err
}

const incrementTenantUsageExportArtifactsBytes = `-- name: IncrementTenantUsageExportArtifactsBytes :one
UPDATE tenant_usages u
SET export_artifacts_bytes = u.export_artifacts_bytes + $1::int
WHERE u.tenant_id = $2
  AND COALESCE((SELECT q.export_artifacts_bytes FROM tenant_quotas q WHERE q.tenant_id = u.tenant_id), $3::int) >= u.export_artifacts_bytes + $1::int
RETURNING u.export_artifacts_bytes
`

type IncrementTenantUsageExportArtifactsBytesParams struct {
	Delta        int32
	TenantID     string
	DefaultLimit int32
}

func (q *Queries) IncrementTenantUsageExportArtifactsBytes(ctx context.Context, arg IncrementTenantUsageExportArtifactsBytesParams) (int32, error) {
	row := q.db.QueryRow(ctx, incrementTenantUsageExportArtifactsBytes, arg.Delta, arg.TenantID, arg.DefaultLimit)
	var export_artifacts_bytes int32
	err := row.Scan(&export_artifacts_bytes)
	return export_artifacts_bytes, err
}

const incrementTenantUsageGroups = `-- name: IncrementTenantUsageGroups :one
UPDATE tenant_usages u
SET groups = u.groups + $1::int
WHERE u.tenant_id = $2
  AND COALESCE((SELECT q.groups FROM tenant_quotas q WHERE q.tenant_id = u.tenant_id), $3::int) >= u.groups + $1::int
RETURNING u.groups
`

type IncrementTenantUsageGroupsParams struct {
	Delta        int32
	TenantID     string
	DefaultLimit int32
}

func (q *Queries) IncrementTenantUsageGroups(ctx context.Context, arg IncrementTenantUsageGroupsParams) (int32, error) {
	row := q.db.QueryRow(ctx, incrementTenantUsageGroups, arg.Delta, arg.TenantID, arg.DefaultLimit)
	var groups int32
	err := row.Scan(&groups)
	return groups, err
}

const incrementTenantUsageOAuth2Clients = `-- name: IncrementTenantUsageOAuth2Clients :one
UPDATE tenant_usages u
SET oauth2_clients = u.oauth2_clients + $1::int
WHERE u.tenant_id = $2
  AND COALESCE((SELECT q.oauth2_clients FROM tenant_quotas q WHERE q.tenant_id = u.tenant_id), $3::int) >= u.oauth2_clients + $1::int
RETURNING u.oauth2_clients
`

type IncrementTenantUsageOAuth2ClientsParams struct {
	Delta        int32
	TenantID     string
	DefaultLimit int32
}

func (q *Queries) IncrementTenantUsageOAuth2Clients(ctx context.Context, arg IncrementTenantUsageOAuth2ClientsParams) (int32, error) {
	row := q.db.QueryRow(ctx, incrementTenantUsageOAuth2Clients, arg.Delta, arg.TenantID, arg.DefaultLimit)
	var oauth2_clients int32
	err := row.Scan(&oauth2_clients)
	return oauth2_clients, err
}

const incrementTenantUsageSsfStreams = `-- name: IncrementTenantUsageSsfStreams :one
UPDATE tenant_usages u
SET ssf_streams = u.ssf_streams + $1::int
WHERE u.tenant_id = $2
  AND COALESCE((SELECT q.ssf_streams FROM tenant_quotas q WHERE q.tenant_id = u.tenant_id), $3::int) >= u.ssf_streams + $1::int
RETURNING u.ssf_streams
`

type IncrementTenantUsageSsfStreamsParams struct {
	Delta        int32
	TenantID     string
	DefaultLimit int32
}

func (q *Queries) IncrementTenantUsageSsfStreams(ctx context.Context, arg IncrementTenantUsageSsfStreamsParams) (int32, error) {
	row := q.db.QueryRow(ctx, incrementTenantUsageSsfStreams, arg.Delta, arg.TenantID, arg.DefaultLimit)
	var ssf_streams int32
	err := row.Scan(&ssf_streams)
	return ssf_streams, err
}

const incrementTenantUsageUsers = `-- name: IncrementTenantUsageUsers :one
UPDATE tenant_usages u
SET users = u.users + $1::int
WHERE u.tenant_id = $2
  AND COALESCE((SELECT q.users FROM tenant_quotas q WHERE q.tenant_id = u.tenant_id), $3::int) >= u.users + $1::int
RETURNING u.users
`

type IncrementTenantUsageUsersParams struct {
	Delta        int32
	TenantID     string
	DefaultLimit int32
}

func (q *Queries) IncrementTenantUsageUsers(ctx context.Context, arg IncrementTenantUsageUsersParams) (int32, error) {
	row := q.db.QueryRow(ctx, incrementTenantUsageUsers, arg.Delta, arg.TenantID, arg.DefaultLimit)
	var users int32
	err := row.Scan(&users)
	return users, err
}
