// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db_postgres

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type Agent struct {
	ID          string
	TenantID    string
	Name        string
	Description pgtype.Text
	Kind        string
	OwnerUserID string
	Status      string
	Roles       []byte
	CreatedAt   time.Time
	UpdatedAt   time.Time
	DisabledAt  pgtype.Timestamptz
	KilledAt    pgtype.Timestamptz
}

type AgentCredentialBinding struct {
	AgentID   string
	ClientID  string
	CreatedAt time.Time
}
