// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db_postgres

import (
	"context"
)

type Querier interface {
	AddAgentBinding(ctx context.Context, arg AddAgentBindingParams) (int64, error)
	DeleteAgent(ctx context.Context, arg DeleteAgentParams) error
	FindAgentByClientID(ctx context.Context, arg FindAgentByClientIDParams) (*Agent, error)
	FindAgentByID(ctx context.Context, arg FindAgentByIDParams) (*Agent, error)
	ListAgentBindingsByAgent(ctx context.Context, arg ListAgentBindingsByAgentParams) ([]*AgentCredentialBinding, error)
	ListAgentsByTenant(ctx context.Context, tenantID string) ([]*Agent, error)
	RemoveAgentBinding(ctx context.Context, arg RemoveAgentBindingParams) (int64, error)
	SaveAgent(ctx context.Context, arg SaveAgentParams) error
}

var _ Querier = (*Queries)(nil)
