// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: revocation_epochs.sql

package db_postgres

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const advanceAgentRevocationEpoch = `-- name: AdvanceAgentRevocationEpoch :one
INSERT INTO agent_revocation_epochs (agent_id,tenant_id,epoch,reason,advanced_at,source_event_id)
VALUES ($1,$2,$3,$4,$5,$6)
ON CONFLICT (agent_id) DO UPDATE SET
 epoch=EXCLUDED.epoch,reason=EXCLUDED.reason,advanced_at=EXCLUDED.advanced_at,
 source_event_id=EXCLUDED.source_event_id
 WHERE EXCLUDED.epoch >= agent_revocation_epochs.epoch
RETURNING agent_id,tenant_id,epoch,reason,advanced_at,source_event_id
`

type AdvanceAgentRevocationEpochParams struct {
	AgentID       string
	TenantID      string
	Epoch         time.Time
	Reason        string
	AdvancedAt    time.Time
	SourceEventID pgtype.Text
}

func (q *Queries) AdvanceAgentRevocationEpoch(ctx context.Context, arg AdvanceAgentRevocationEpochParams) (*AgentRevocationEpoch, error) {
	row := q.db.QueryRow(ctx, advanceAgentRevocationEpoch,
		arg.AgentID,
		arg.TenantID,
		arg.Epoch,
		arg.Reason,
		arg.AdvancedAt,
		arg.SourceEventID,
	)
	var i AgentRevocationEpoch
	err := row.Scan(
		&i.AgentID,
		&i.TenantID,
		&i.Epoch,
		&i.Reason,
		&i.AdvancedAt,
		&i.SourceEventID,
	)
	return &i, err
}

const findAgentRevocationEpoch = `-- name: FindAgentRevocationEpoch :one
SELECT agent_id,tenant_id,epoch,reason,advanced_at,source_event_id
FROM agent_revocation_epochs WHERE tenant_id=$1 AND agent_id=$2
`

type FindAgentRevocationEpochParams struct {
	TenantID string
	AgentID  string
}

func (q *Queries) FindAgentRevocationEpoch(ctx context.Context, arg FindAgentRevocationEpochParams) (*AgentRevocationEpoch, error) {
	row := q.db.QueryRow(ctx, findAgentRevocationEpoch, arg.TenantID, arg.AgentID)
	var i AgentRevocationEpoch
	err := row.Scan(
		&i.AgentID,
		&i.TenantID,
		&i.Epoch,
		&i.Reason,
		&i.AdvancedAt,
		&i.SourceEventID,
	)
	return &i, err
}
