// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: wsfed_relying_parties.sql

package db_postgres

import (
	"context"
	"time"
)

const deleteWsFedRelyingParty = `-- name: DeleteWsFedRelyingParty :exec
DELETE FROM wsfed_relying_parties WHERE tenant_id = $1 AND wtrealm = $2
`

type DeleteWsFedRelyingPartyParams struct {
	TenantID string
	Wtrealm  string
}

func (q *Queries) DeleteWsFedRelyingParty(ctx context.Context, arg DeleteWsFedRelyingPartyParams) error {
	_, err := q.db.Exec(ctx, deleteWsFedRelyingParty, arg.TenantID, arg.Wtrealm)
	return err
}

const getWsFedRelyingParty = `-- name: GetWsFedRelyingParty :one
SELECT tenant_id, wtrealm, application_id, application_protocol_type, display_name, reply_urls, audience, token_type, claim_policy, entra_profile, created_at, updated_at
FROM wsfed_relying_parties WHERE tenant_id = $1 AND wtrealm = $2
`

type GetWsFedRelyingPartyParams struct {
	TenantID string
	Wtrealm  string
}

func (q *Queries) GetWsFedRelyingParty(ctx context.Context, arg GetWsFedRelyingPartyParams) (*WsfedRelyingParty, error) {
	row := q.db.QueryRow(ctx, getWsFedRelyingParty, arg.TenantID, arg.Wtrealm)
	var i WsfedRelyingParty
	err := row.Scan(
		&i.TenantID,
		&i.Wtrealm,
		&i.ApplicationID,
		&i.ApplicationProtocolType,
		&i.DisplayName,
		&i.ReplyUrls,
		&i.Audience,
		&i.TokenType,
		&i.ClaimPolicy,
		&i.EntraProfile,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const listWsFedRelyingPartiesByTenant = `-- name: ListWsFedRelyingPartiesByTenant :many
SELECT tenant_id, wtrealm, application_id, application_protocol_type, display_name, reply_urls, audience, token_type, claim_policy, entra_profile, created_at, updated_at
FROM wsfed_relying_parties WHERE tenant_id = $1 ORDER BY wtrealm
`

func (q *Queries) ListWsFedRelyingPartiesByTenant(ctx context.Context, tenantID string) ([]*WsfedRelyingParty, error) {
	rows, err := q.db.Query(ctx, listWsFedRelyingPartiesByTenant, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*WsfedRelyingParty
	for rows.Next() {
		var i WsfedRelyingParty
		if err := rows.Scan(
			&i.TenantID,
			&i.Wtrealm,
			&i.ApplicationID,
			&i.ApplicationProtocolType,
			&i.DisplayName,
			&i.ReplyUrls,
			&i.Audience,
			&i.TokenType,
			&i.ClaimPolicy,
			&i.EntraProfile,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertWsFedRelyingParty = `-- name: UpsertWsFedRelyingParty :exec
INSERT INTO wsfed_relying_parties (tenant_id, wtrealm, display_name, reply_urls, audience, token_type, claim_policy, entra_profile, created_at, updated_at)
VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10)
ON CONFLICT (tenant_id,wtrealm) DO UPDATE SET display_name=EXCLUDED.display_name, reply_urls=EXCLUDED.reply_urls,
 audience=EXCLUDED.audience, token_type=EXCLUDED.token_type, claim_policy=EXCLUDED.claim_policy,
 entra_profile=EXCLUDED.entra_profile, updated_at=EXCLUDED.updated_at
`

type UpsertWsFedRelyingPartyParams struct {
	TenantID     string
	Wtrealm      string
	DisplayName  string
	ReplyUrls    []byte
	Audience     string
	TokenType    string
	ClaimPolicy  []byte
	EntraProfile []byte
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

func (q *Queries) UpsertWsFedRelyingParty(ctx context.Context, arg UpsertWsFedRelyingPartyParams) error {
	_, err := q.db.Exec(ctx, upsertWsFedRelyingParty,
		arg.TenantID,
		arg.Wtrealm,
		arg.DisplayName,
		arg.ReplyUrls,
		arg.Audience,
		arg.TokenType,
		arg.ClaimPolicy,
		arg.EntraProfile,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}
