// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: scim_user_refs.sql

package db_postgres

import (
	"context"
)

const deleteScimUserRef = `-- name: DeleteScimUserRef :exec
DELETE FROM scim_user_refs WHERE tenant_id = $1 AND scim_id = $2
`

type DeleteScimUserRefParams struct {
	TenantID string
	ScimID   string
}

func (q *Queries) DeleteScimUserRef(ctx context.Context, arg DeleteScimUserRefParams) error {
	_, err := q.db.Exec(ctx, deleteScimUserRef, arg.TenantID, arg.ScimID)
	return err
}

const findScimUserRefByScimID = `-- name: FindScimUserRefByScimID :one
SELECT tenant_id, scim_id, user_id FROM scim_user_refs WHERE tenant_id = $1 AND scim_id = $2
`

type FindScimUserRefByScimIDParams struct {
	TenantID string
	ScimID   string
}

type FindScimUserRefByScimIDRow struct {
	TenantID string
	ScimID   string
	UserID   string
}

func (q *Queries) FindScimUserRefByScimID(ctx context.Context, arg FindScimUserRefByScimIDParams) (*FindScimUserRefByScimIDRow, error) {
	row := q.db.QueryRow(ctx, findScimUserRefByScimID, arg.TenantID, arg.ScimID)
	var i FindScimUserRefByScimIDRow
	err := row.Scan(&i.TenantID, &i.ScimID, &i.UserID)
	return &i, err
}

const findScimUserRefByUserID = `-- name: FindScimUserRefByUserID :one
SELECT tenant_id, scim_id, user_id FROM scim_user_refs WHERE tenant_id = $1 AND user_id = $2
`

type FindScimUserRefByUserIDParams struct {
	TenantID string
	UserID   string
}

type FindScimUserRefByUserIDRow struct {
	TenantID string
	ScimID   string
	UserID   string
}

func (q *Queries) FindScimUserRefByUserID(ctx context.Context, arg FindScimUserRefByUserIDParams) (*FindScimUserRefByUserIDRow, error) {
	row := q.db.QueryRow(ctx, findScimUserRefByUserID, arg.TenantID, arg.UserID)
	var i FindScimUserRefByUserIDRow
	err := row.Scan(&i.TenantID, &i.ScimID, &i.UserID)
	return &i, err
}

const saveScimUserRef = `-- name: SaveScimUserRef :exec
INSERT INTO scim_user_refs (tenant_id, scim_id, user_id)
VALUES ($1, $2, $3)
ON CONFLICT (tenant_id, scim_id) DO UPDATE SET
    user_id=EXCLUDED.user_id,
    updated_at=now()
`

type SaveScimUserRefParams struct {
	TenantID string
	ScimID   string
	UserID   string
}

func (q *Queries) SaveScimUserRef(ctx context.Context, arg SaveScimUserRefParams) error {
	_, err := q.db.Exec(ctx, saveScimUserRef, arg.TenantID, arg.ScimID, arg.UserID)
	return err
}
