// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: data_keys.sql

package db_postgres

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const countNonDestroyedDataKeys = `-- name: CountNonDestroyedDataKeys :one
SELECT count(*) FROM tenant_data_encryption_keys
WHERE tenant_id=$1 AND status!='destroyed'
`

func (q *Queries) CountNonDestroyedDataKeys(ctx context.Context, tenantID string) (int64, error) {
	row := q.db.QueryRow(ctx, countNonDestroyedDataKeys, tenantID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const destroyDataKey = `-- name: DestroyDataKey :exec
UPDATE tenant_data_encryption_keys
SET status='destroyed', wrapped_dek=NULL, destroyed_at=$3, updated_at=$3
WHERE tenant_id=$1 AND version=$2
`

type DestroyDataKeyParams struct {
	TenantID    string
	Version     int32
	DestroyedAt pgtype.Timestamptz
}

func (q *Queries) DestroyDataKey(ctx context.Context, arg DestroyDataKeyParams) error {
	_, err := q.db.Exec(ctx, destroyDataKey, arg.TenantID, arg.Version, arg.DestroyedAt)
	return err
}

const disableDataKey = `-- name: DisableDataKey :exec
UPDATE tenant_data_encryption_keys
SET status='disabled', disabled_at=$3, updated_at=$3
WHERE tenant_id=$1 AND version=$2
`

type DisableDataKeyParams struct {
	TenantID   string
	Version    int32
	DisabledAt pgtype.Timestamptz
}

func (q *Queries) DisableDataKey(ctx context.Context, arg DisableDataKeyParams) error {
	_, err := q.db.Exec(ctx, disableDataKey, arg.TenantID, arg.Version, arg.DisabledAt)
	return err
}

const getActiveDataKey = `-- name: GetActiveDataKey :one
SELECT id,tenant_id,version,status,wrapped_dek,master_key_id,created_at,activated_at,disabled_at,destroyed_at
FROM tenant_data_encryption_keys
WHERE tenant_id=$1 AND status='active' LIMIT 1
`

type GetActiveDataKeyRow struct {
	ID          string
	TenantID    string
	Version     int32
	Status      string
	WrappedDek  []byte
	MasterKeyID string
	CreatedAt   time.Time
	ActivatedAt pgtype.Timestamptz
	DisabledAt  pgtype.Timestamptz
	DestroyedAt pgtype.Timestamptz
}

func (q *Queries) GetActiveDataKey(ctx context.Context, tenantID string) (*GetActiveDataKeyRow, error) {
	row := q.db.QueryRow(ctx, getActiveDataKey, tenantID)
	var i GetActiveDataKeyRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Version,
		&i.Status,
		&i.WrappedDek,
		&i.MasterKeyID,
		&i.CreatedAt,
		&i.ActivatedAt,
		&i.DisabledAt,
		&i.DestroyedAt,
	)
	return &i, err
}

const getDataKeyByVersion = `-- name: GetDataKeyByVersion :one
SELECT id,tenant_id,version,status,wrapped_dek,master_key_id,created_at,activated_at,disabled_at,destroyed_at
FROM tenant_data_encryption_keys
WHERE tenant_id=$1 AND version=$2
`

type GetDataKeyByVersionParams struct {
	TenantID string
	Version  int32
}

type GetDataKeyByVersionRow struct {
	ID          string
	TenantID    string
	Version     int32
	Status      string
	WrappedDek  []byte
	MasterKeyID string
	CreatedAt   time.Time
	ActivatedAt pgtype.Timestamptz
	DisabledAt  pgtype.Timestamptz
	DestroyedAt pgtype.Timestamptz
}

func (q *Queries) GetDataKeyByVersion(ctx context.Context, arg GetDataKeyByVersionParams) (*GetDataKeyByVersionRow, error) {
	row := q.db.QueryRow(ctx, getDataKeyByVersion, arg.TenantID, arg.Version)
	var i GetDataKeyByVersionRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Version,
		&i.Status,
		&i.WrappedDek,
		&i.MasterKeyID,
		&i.CreatedAt,
		&i.ActivatedAt,
		&i.DisabledAt,
		&i.DestroyedAt,
	)
	return &i, err
}

const insertDataKey = `-- name: InsertDataKey :exec
INSERT INTO tenant_data_encryption_keys (
  id, tenant_id, version, status, wrapped_dek, master_key_id, created_at, updated_at, activated_at
) VALUES (
  $1, $2, $3, 'active', $4, $5, $6, $6, $6
)
`

type InsertDataKeyParams struct {
	ID          string
	TenantID    string
	Version     int32
	WrappedDek  []byte
	MasterKeyID string
	CreatedAt   time.Time
}

func (q *Queries) InsertDataKey(ctx context.Context, arg InsertDataKeyParams) error {
	_, err := q.db.Exec(ctx, insertDataKey,
		arg.ID,
		arg.TenantID,
		arg.Version,
		arg.WrappedDek,
		arg.MasterKeyID,
		arg.CreatedAt,
	)
	return err
}

const listDataKeysByTenant = `-- name: ListDataKeysByTenant :many
SELECT id,tenant_id,version,status,wrapped_dek,master_key_id,created_at,activated_at,disabled_at,destroyed_at
FROM tenant_data_encryption_keys
WHERE tenant_id=$1 ORDER BY version DESC
`

type ListDataKeysByTenantRow struct {
	ID          string
	TenantID    string
	Version     int32
	Status      string
	WrappedDek  []byte
	MasterKeyID string
	CreatedAt   time.Time
	ActivatedAt pgtype.Timestamptz
	DisabledAt  pgtype.Timestamptz
	DestroyedAt pgtype.Timestamptz
}

func (q *Queries) ListDataKeysByTenant(ctx context.Context, tenantID string) ([]*ListDataKeysByTenantRow, error) {
	rows, err := q.db.Query(ctx, listDataKeysByTenant, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*ListDataKeysByTenantRow
	for rows.Next() {
		var i ListDataKeysByTenantRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Version,
			&i.Status,
			&i.WrappedDek,
			&i.MasterKeyID,
			&i.CreatedAt,
			&i.ActivatedAt,
			&i.DisabledAt,
			&i.DestroyedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockDataKeyRotation = `-- name: LockDataKeyRotation :exec
SELECT pg_advisory_xact_lock(hashtext('idmagic-datakey:'||$1))
`

func (q *Queries) LockDataKeyRotation(ctx context.Context, dollar_1 pgtype.Text) error {
	_, err := q.db.Exec(ctx, lockDataKeyRotation, dollar_1)
	return err
}

const maxDataKeyVersion = `-- name: MaxDataKeyVersion :one
SELECT COALESCE(MAX(version),0)::int FROM tenant_data_encryption_keys
WHERE tenant_id=$1
`

func (q *Queries) MaxDataKeyVersion(ctx context.Context, tenantID string) (int32, error) {
	row := q.db.QueryRow(ctx, maxDataKeyVersion, tenantID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const retireActiveDataKey = `-- name: RetireActiveDataKey :exec
UPDATE tenant_data_encryption_keys
SET status='retiring', updated_at=$2
WHERE tenant_id=$1 AND status='active'
`

type RetireActiveDataKeyParams struct {
	TenantID  string
	UpdatedAt time.Time
}

func (q *Queries) RetireActiveDataKey(ctx context.Context, arg RetireActiveDataKeyParams) error {
	_, err := q.db.Exec(ctx, retireActiveDataKey, arg.TenantID, arg.UpdatedAt)
	return err
}
