// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: authorization.sql

package db_postgres

import (
	"context"
	"time"
)

const bumpAuthorizationWriteVersion = `-- name: BumpAuthorizationWriteVersion :one
INSERT INTO authorization_write_versions (tenant_id,version,updated_at)
VALUES ($1,1,now())
ON CONFLICT (tenant_id) DO UPDATE
 SET version=authorization_write_versions.version+1,updated_at=now()
RETURNING version
`

func (q *Queries) BumpAuthorizationWriteVersion(ctx context.Context, tenantID string) (int64, error) {
	row := q.db.QueryRow(ctx, bumpAuthorizationWriteVersion, tenantID)
	var version int64
	err := row.Scan(&version)
	return version, err
}

const deleteRelationTuple = `-- name: DeleteRelationTuple :execrows
DELETE FROM authorization_relation_tuples
WHERE tenant_id=$1 AND resource_type=$2 AND resource_id=$3 AND relation=$4
  AND subject_type=$5 AND subject_id=$6 AND subject_relation=$7
`

type DeleteRelationTupleParams struct {
	TenantID        string
	ResourceType    string
	ResourceID      string
	Relation        string
	SubjectType     string
	SubjectID       string
	SubjectRelation string
}

func (q *Queries) DeleteRelationTuple(ctx context.Context, arg DeleteRelationTupleParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteRelationTuple,
		arg.TenantID,
		arg.ResourceType,
		arg.ResourceID,
		arg.Relation,
		arg.SubjectType,
		arg.SubjectID,
		arg.SubjectRelation,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteRelationTuplesForObject = `-- name: DeleteRelationTuplesForObject :execrows
DELETE FROM authorization_relation_tuples
WHERE tenant_id=$1
  AND ((resource_type=$2 AND resource_id=$3) OR (subject_type=$2 AND subject_id=$3))
`

type DeleteRelationTuplesForObjectParams struct {
	TenantID     string
	ResourceType string
	ResourceID   string
}

func (q *Queries) DeleteRelationTuplesForObject(ctx context.Context, arg DeleteRelationTuplesForObjectParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteRelationTuplesForObject, arg.TenantID, arg.ResourceType, arg.ResourceID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getAuthorizationModelByVersion = `-- name: GetAuthorizationModelByVersion :one
SELECT id,tenant_id,version,definition,created_at
FROM authorization_models WHERE tenant_id=$1 AND version=$2
`

type GetAuthorizationModelByVersionParams struct {
	TenantID string
	Version  int32
}

func (q *Queries) GetAuthorizationModelByVersion(ctx context.Context, arg GetAuthorizationModelByVersionParams) (*AuthorizationModel, error) {
	row := q.db.QueryRow(ctx, getAuthorizationModelByVersion, arg.TenantID, arg.Version)
	var i AuthorizationModel
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Version,
		&i.Definition,
		&i.CreatedAt,
	)
	return &i, err
}

const getAuthorizationWriteVersion = `-- name: GetAuthorizationWriteVersion :one
SELECT version FROM authorization_write_versions WHERE tenant_id=$1
`

func (q *Queries) GetAuthorizationWriteVersion(ctx context.Context, tenantID string) (int64, error) {
	row := q.db.QueryRow(ctx, getAuthorizationWriteVersion, tenantID)
	var version int64
	err := row.Scan(&version)
	return version, err
}

const getLatestAuthorizationModel = `-- name: GetLatestAuthorizationModel :one
SELECT id,tenant_id,version,definition,created_at
FROM authorization_models WHERE tenant_id=$1 ORDER BY version DESC LIMIT 1
`

func (q *Queries) GetLatestAuthorizationModel(ctx context.Context, tenantID string) (*AuthorizationModel, error) {
	row := q.db.QueryRow(ctx, getLatestAuthorizationModel, tenantID)
	var i AuthorizationModel
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Version,
		&i.Definition,
		&i.CreatedAt,
	)
	return &i, err
}

const insertAuthorizationModel = `-- name: InsertAuthorizationModel :one
INSERT INTO authorization_models (id,tenant_id,version,definition,created_at)
VALUES (
 $1,$2,
 (SELECT COALESCE(MAX(version),0)+1 FROM authorization_models WHERE tenant_id=$2),
 $3,$4
)
RETURNING id,tenant_id,version,definition,created_at
`

type InsertAuthorizationModelParams struct {
	ID         string
	TenantID   string
	Definition []byte
	CreatedAt  time.Time
}

func (q *Queries) InsertAuthorizationModel(ctx context.Context, arg InsertAuthorizationModelParams) (*AuthorizationModel, error) {
	row := q.db.QueryRow(ctx, insertAuthorizationModel,
		arg.ID,
		arg.TenantID,
		arg.Definition,
		arg.CreatedAt,
	)
	var i AuthorizationModel
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Version,
		&i.Definition,
		&i.CreatedAt,
	)
	return &i, err
}

const insertRelationTuple = `-- name: InsertRelationTuple :execrows
INSERT INTO authorization_relation_tuples
 (tenant_id,resource_type,resource_id,relation,subject_type,subject_id,subject_relation)
VALUES ($1,$2,$3,$4,$5,$6,$7)
ON CONFLICT DO NOTHING
`

type InsertRelationTupleParams struct {
	TenantID        string
	ResourceType    string
	ResourceID      string
	Relation        string
	SubjectType     string
	SubjectID       string
	SubjectRelation string
}

func (q *Queries) InsertRelationTuple(ctx context.Context, arg InsertRelationTupleParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertRelationTuple,
		arg.TenantID,
		arg.ResourceType,
		arg.ResourceID,
		arg.Relation,
		arg.SubjectType,
		arg.SubjectID,
		arg.SubjectRelation,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listRelationTupleResourceIDs = `-- name: ListRelationTupleResourceIDs :many
SELECT DISTINCT resource_id
FROM authorization_relation_tuples
WHERE tenant_id=$1 AND resource_type=$2
ORDER BY resource_id
LIMIT $3
`

type ListRelationTupleResourceIDsParams struct {
	TenantID     string
	ResourceType string
	Limit        int32
}

func (q *Queries) ListRelationTupleResourceIDs(ctx context.Context, arg ListRelationTupleResourceIDsParams) ([]string, error) {
	rows, err := q.db.Query(ctx, listRelationTupleResourceIDs, arg.TenantID, arg.ResourceType, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var resource_id string
		if err := rows.Scan(&resource_id); err != nil {
			return nil, err
		}
		items = append(items, resource_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRelationTupleSubjects = `-- name: ListRelationTupleSubjects :many
SELECT subject_type,subject_id,subject_relation
FROM authorization_relation_tuples
WHERE tenant_id=$1 AND resource_type=$2 AND resource_id=$3 AND relation=$4
ORDER BY subject_type,subject_id,subject_relation
`

type ListRelationTupleSubjectsParams struct {
	TenantID     string
	ResourceType string
	ResourceID   string
	Relation     string
}

type ListRelationTupleSubjectsRow struct {
	SubjectType     string
	SubjectID       string
	SubjectRelation string
}

func (q *Queries) ListRelationTupleSubjects(ctx context.Context, arg ListRelationTupleSubjectsParams) ([]*ListRelationTupleSubjectsRow, error) {
	rows, err := q.db.Query(ctx, listRelationTupleSubjects,
		arg.TenantID,
		arg.ResourceType,
		arg.ResourceID,
		arg.Relation,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*ListRelationTupleSubjectsRow
	for rows.Next() {
		var i ListRelationTupleSubjectsRow
		if err := rows.Scan(&i.SubjectType, &i.SubjectID, &i.SubjectRelation); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRelationTuples = `-- name: ListRelationTuples :many
SELECT resource_type,resource_id,relation,subject_type,subject_id,subject_relation
FROM authorization_relation_tuples
WHERE tenant_id=$1
  AND ($2 = '' OR resource_type=$2)
  AND ($3 = '' OR resource_id=$3)
  AND ($4 = '' OR relation=$4)
  AND ($5 = '' OR subject_type=$5)
  AND ($6 = '' OR subject_id=$6)
ORDER BY resource_type,resource_id,relation,subject_type,subject_id,subject_relation
LIMIT $7
`

type ListRelationTuplesParams struct {
	TenantID string
	Column2  interface{}
	Column3  interface{}
	Column4  interface{}
	Column5  interface{}
	Column6  interface{}
	Limit    int32
}

type ListRelationTuplesRow struct {
	ResourceType    string
	ResourceID      string
	Relation        string
	SubjectType     string
	SubjectID       string
	SubjectRelation string
}

func (q *Queries) ListRelationTuples(ctx context.Context, arg ListRelationTuplesParams) ([]*ListRelationTuplesRow, error) {
	rows, err := q.db.Query(ctx, listRelationTuples,
		arg.TenantID,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Column5,
		arg.Column6,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*ListRelationTuplesRow
	for rows.Next() {
		var i ListRelationTuplesRow
		if err := rows.Scan(
			&i.ResourceType,
			&i.ResourceID,
			&i.Relation,
			&i.SubjectType,
			&i.SubjectID,
			&i.SubjectRelation,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
