// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db_postgres

import (
	"time"
)

type AuthorizationModel struct {
	ID         string
	TenantID   string
	Version    int32
	Definition []byte
	CreatedAt  time.Time
}
