// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"context"
)

type Querier interface {
	FindAllTenants(ctx context.Context) ([]*Tenant, error)
	FindTenantByID(ctx context.Context, id string) (*Tenant, error)
	FindTenantByRealm(ctx context.Context, realm string) (*Tenant, error)
	SaveTenant(ctx context.Context, arg SaveTenantParams) error
}

var _ Querier = (*Queries)(nil)
