// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: scim_tokens.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteScimToken = `-- name: DeleteScimToken :exec
DELETE FROM scim_tokens WHERE tenant_id = $1 AND id = $2
`

type DeleteScimTokenParams struct {
	TenantID string
	ID       string
}

func (q *Queries) DeleteScimToken(ctx context.Context, arg DeleteScimTokenParams) error {
	_, err := q.db.Exec(ctx, deleteScimToken, arg.TenantID, arg.ID)
	return err
}

const findScimTokenByHash = `-- name: FindScimTokenByHash :one
SELECT id, tenant_id, token_hash, description, created_at, expires_at
FROM scim_tokens WHERE token_hash = $1
`

type FindScimTokenByHashRow struct {
	ID          string
	TenantID    string
	TokenHash   string
	Description pgtype.Text
	CreatedAt   time.Time
	ExpiresAt   pgtype.Timestamptz
}

func (q *Queries) FindScimTokenByHash(ctx context.Context, tokenHash string) (*FindScimTokenByHashRow, error) {
	row := q.db.QueryRow(ctx, findScimTokenByHash, tokenHash)
	var i FindScimTokenByHashRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.TokenHash,
		&i.Description,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return &i, err
}

const listScimTokensByTenant = `-- name: ListScimTokensByTenant :many
SELECT id, tenant_id, token_hash, description, created_at, expires_at
FROM scim_tokens WHERE tenant_id = $1
`

type ListScimTokensByTenantRow struct {
	ID          string
	TenantID    string
	TokenHash   string
	Description pgtype.Text
	CreatedAt   time.Time
	ExpiresAt   pgtype.Timestamptz
}

func (q *Queries) ListScimTokensByTenant(ctx context.Context, tenantID string) ([]*ListScimTokensByTenantRow, error) {
	rows, err := q.db.Query(ctx, listScimTokensByTenant, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*ListScimTokensByTenantRow
	for rows.Next() {
		var i ListScimTokensByTenantRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.TokenHash,
			&i.Description,
			&i.CreatedAt,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const saveScimToken = `-- name: SaveScimToken :exec
INSERT INTO scim_tokens (id, tenant_id, token_hash, description, created_at, expires_at)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (id) DO UPDATE SET
    token_hash=EXCLUDED.token_hash,
    description=EXCLUDED.description,
    expires_at=EXCLUDED.expires_at,
    updated_at=now()
`

type SaveScimTokenParams struct {
	ID          string
	TenantID    string
	TokenHash   string
	Description pgtype.Text
	CreatedAt   time.Time
	ExpiresAt   pgtype.Timestamptz
}

func (q *Queries) SaveScimToken(ctx context.Context, arg SaveScimTokenParams) error {
	_, err := q.db.Exec(ctx, saveScimToken,
		arg.ID,
		arg.TenantID,
		arg.TokenHash,
		arg.Description,
		arg.CreatedAt,
		arg.ExpiresAt,
	)
	return err
}
