// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"context"
)

type Querier interface {
	DeleteRecoveryCodesForSub(ctx context.Context, userID string) error
	InsertRecoveryCode(ctx context.Context, arg InsertRecoveryCodeParams) error
	ListRecoveryCodesBySub(ctx context.Context, userID string) ([]*RecoveryCode, error)
	MarkRecoveryCodeConsumed(ctx context.Context, arg MarkRecoveryCodeConsumedParams) (int64, error)
}

var _ Querier = (*Queries)(nil)
