// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: application_categories.sql

package sqlcgen

import (
	"context"
	"time"
)

const deleteApplicationCategory = `-- name: DeleteApplicationCategory :exec
DELETE FROM application_categories WHERE tenant_id = $1 AND category_id = $2
`

type DeleteApplicationCategoryParams struct {
	TenantID   string
	CategoryID string
}

func (q *Queries) DeleteApplicationCategory(ctx context.Context, arg DeleteApplicationCategoryParams) error {
	_, err := q.db.Exec(ctx, deleteApplicationCategory, arg.TenantID, arg.CategoryID)
	return err
}

const getApplicationCategoryByID = `-- name: GetApplicationCategoryByID :one
SELECT tenant_id, category_id, name, position, created_at, updated_at
FROM application_categories
WHERE tenant_id = $1 AND category_id = $2
`

type GetApplicationCategoryByIDParams struct {
	TenantID   string
	CategoryID string
}

func (q *Queries) GetApplicationCategoryByID(ctx context.Context, arg GetApplicationCategoryByIDParams) (*ApplicationCategory, error) {
	row := q.db.QueryRow(ctx, getApplicationCategoryByID, arg.TenantID, arg.CategoryID)
	var i ApplicationCategory
	err := row.Scan(
		&i.TenantID,
		&i.CategoryID,
		&i.Name,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const listApplicationCategoriesByTenant = `-- name: ListApplicationCategoriesByTenant :many
SELECT tenant_id, category_id, name, position, created_at, updated_at
FROM application_categories
WHERE tenant_id = $1
ORDER BY position, name
`

func (q *Queries) ListApplicationCategoriesByTenant(ctx context.Context, tenantID string) ([]*ApplicationCategory, error) {
	rows, err := q.db.Query(ctx, listApplicationCategoriesByTenant, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*ApplicationCategory
	for rows.Next() {
		var i ApplicationCategory
		if err := rows.Scan(
			&i.TenantID,
			&i.CategoryID,
			&i.Name,
			&i.Position,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertApplicationCategory = `-- name: UpsertApplicationCategory :exec
INSERT INTO application_categories (tenant_id, category_id, name, position, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (tenant_id, category_id) DO UPDATE SET
  name = EXCLUDED.name,
  position = EXCLUDED.position,
  updated_at = EXCLUDED.updated_at
`

type UpsertApplicationCategoryParams struct {
	TenantID   string
	CategoryID string
	Name       string
	Position   int32
	CreatedAt  time.Time
	UpdatedAt  time.Time
}

func (q *Queries) UpsertApplicationCategory(ctx context.Context, arg UpsertApplicationCategoryParams) error {
	_, err := q.db.Exec(ctx, upsertApplicationCategory,
		arg.TenantID,
		arg.CategoryID,
		arg.Name,
		arg.Position,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}
