// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"context"
)

type Querier interface {
	DeletePasswordHistoryForSub(ctx context.Context, userID string) error
	InsertPasswordHistory(ctx context.Context, arg InsertPasswordHistoryParams) error
	RecentPasswordHistory(ctx context.Context, arg RecentPasswordHistoryParams) ([]*RecentPasswordHistoryRow, error)
}

var _ Querier = (*Queries)(nil)
