// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db_postgres

import (
	"time"
)

type NotificationPreference struct {
	UserID             string
	DisabledCategories []string
	UpdatedAt          time.Time
}
