// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db_postgres

import (
	"context"
	"time"
)

type Querier interface {
	DeleteIdleKnownSignInDevices(ctx context.Context, lastSeenAt time.Time) (int64, error)
	FindNotificationPreference(ctx context.Context, userID string) (*NotificationPreference, error)
	// InsertKnownSignInDevice は行が無いときだけ挿入し、挿入した行数を返す。1 なら
	// 「初めて見る端末」であり、0 なら既知である。判定を 1 文の upsert に畳まないのは、
	// 同一時刻の 2 回目を新規と誤らないようにするためで、競合しても挿入に成功するのは
	// ちょうど 1 つの呼び出しだけである。
	InsertKnownSignInDevice(ctx context.Context, arg InsertKnownSignInDeviceParams) (int64, error)
	TouchKnownSignInDevice(ctx context.Context, arg TouchKnownSignInDeviceParams) error
	UpsertNotificationPreference(ctx context.Context, arg UpsertNotificationPreferenceParams) error
}

var _ Querier = (*Queries)(nil)
