// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: security_notification.sql

package db_postgres

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteIdleKnownSignInDevices = `-- name: DeleteIdleKnownSignInDevices :execrows
DELETE FROM known_sign_in_devices WHERE last_seen_at < $1
`

func (q *Queries) DeleteIdleKnownSignInDevices(ctx context.Context, lastSeenAt time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, deleteIdleKnownSignInDevices, lastSeenAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const findNotificationPreference = `-- name: FindNotificationPreference :one
SELECT user_id, disabled_categories, updated_at FROM notification_preferences WHERE user_id = $1
`

func (q *Queries) FindNotificationPreference(ctx context.Context, userID string) (*NotificationPreference, error) {
	row := q.db.QueryRow(ctx, findNotificationPreference, userID)
	var i NotificationPreference
	err := row.Scan(&i.UserID, &i.DisabledCategories, &i.UpdatedAt)
	return &i, err
}

const insertKnownSignInDevice = `-- name: InsertKnownSignInDevice :execrows
INSERT INTO known_sign_in_devices (user_id, device_hash, label, first_seen_at, last_seen_at)
VALUES ($1, $2, $3, $4, $4)
ON CONFLICT (user_id, device_hash) DO NOTHING
`

type InsertKnownSignInDeviceParams struct {
	UserID      string
	DeviceHash  string
	Label       pgtype.Text
	FirstSeenAt time.Time
}

// InsertKnownSignInDevice は行が無いときだけ挿入し、挿入した行数を返す。1 なら
// 「初めて見る端末」であり、0 なら既知である。判定を 1 文の upsert に畳まないのは、
// 同一時刻の 2 回目を新規と誤らないようにするためで、競合しても挿入に成功するのは
// ちょうど 1 つの呼び出しだけである。
func (q *Queries) InsertKnownSignInDevice(ctx context.Context, arg InsertKnownSignInDeviceParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertKnownSignInDevice,
		arg.UserID,
		arg.DeviceHash,
		arg.Label,
		arg.FirstSeenAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const touchKnownSignInDevice = `-- name: TouchKnownSignInDevice :exec
UPDATE known_sign_in_devices
SET last_seen_at = $3, label = COALESCE($4, label)
WHERE user_id = $1 AND device_hash = $2
`

type TouchKnownSignInDeviceParams struct {
	UserID     string
	DeviceHash string
	LastSeenAt time.Time
	Label      pgtype.Text
}

func (q *Queries) TouchKnownSignInDevice(ctx context.Context, arg TouchKnownSignInDeviceParams) error {
	_, err := q.db.Exec(ctx, touchKnownSignInDevice,
		arg.UserID,
		arg.DeviceHash,
		arg.LastSeenAt,
		arg.Label,
	)
	return err
}

const upsertNotificationPreference = `-- name: UpsertNotificationPreference :exec
INSERT INTO notification_preferences (user_id, disabled_categories, updated_at)
VALUES ($1, $2, $3)
ON CONFLICT (user_id) DO UPDATE
    SET disabled_categories = EXCLUDED.disabled_categories,
        updated_at = EXCLUDED.updated_at
`

type UpsertNotificationPreferenceParams struct {
	UserID             string
	DisabledCategories []string
	UpdatedAt          time.Time
}

func (q *Queries) UpsertNotificationPreference(ctx context.Context, arg UpsertNotificationPreferenceParams) error {
	_, err := q.db.Exec(ctx, upsertNotificationPreference, arg.UserID, arg.DisabledCategories, arg.UpdatedAt)
	return err
}
