apiVersion: v1
kind: ServiceAccount
metadata:
  name: idmagic-alloy
  labels:
    app.kubernetes.io/name: idmagic
    app.kubernetes.io/component: alloy
    app.kubernetes.io/part-of: idmagic
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: idmagic-alloy
  labels:
    app.kubernetes.io/name: idmagic
    app.kubernetes.io/component: alloy
    app.kubernetes.io/part-of: idmagic
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: idmagic-alloy
  labels:
    app.kubernetes.io/name: idmagic
    app.kubernetes.io/component: alloy
    app.kubernetes.io/part-of: idmagic
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: idmagic-alloy
subjects:
  - kind: ServiceAccount
    name: idmagic-alloy
    namespace: default
