apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - loki-configmap.yaml
  - loki-statefulset.yaml
  - loki-networkpolicy.yaml
  - alloy-rbac.yaml
  - alloy-daemonset.yaml
  - grafana-loki-datasource.yaml
configMapGenerator:
  - name: idmagic-alloy
    files:
      - config.alloy=alloy-config.alloy
    options:
      labels:
        app.kubernetes.io/name: idmagic
        app.kubernetes.io/component: alloy
        app.kubernetes.io/part-of: idmagic
generatorOptions:
  disableNameSuffixHash: true
