// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db_postgres

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type RecoveryCode struct {
	UserID      string
	CodeHash    string
	GeneratedAt time.Time
	ConsumedAt  pgtype.Timestamptz
}
