// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: application_sign_in_policies.sql

package sqlcgen

import (
	"context"
	"time"
)

const deleteAppSignInPolicy = `-- name: DeleteAppSignInPolicy :exec
DELETE FROM application_sign_in_policies WHERE tenant_id = $1 AND application_id = $2
`

type DeleteAppSignInPolicyParams struct {
	TenantID      string
	ApplicationID string
}

func (q *Queries) DeleteAppSignInPolicy(ctx context.Context, arg DeleteAppSignInPolicyParams) error {
	_, err := q.db.Exec(ctx, deleteAppSignInPolicy, arg.TenantID, arg.ApplicationID)
	return err
}

const getAppSignInPolicy = `-- name: GetAppSignInPolicy :one
SELECT tenant_id, application_id, rules, created_at, updated_at
FROM application_sign_in_policies
WHERE tenant_id = $1 AND application_id = $2
`

type GetAppSignInPolicyParams struct {
	TenantID      string
	ApplicationID string
}

func (q *Queries) GetAppSignInPolicy(ctx context.Context, arg GetAppSignInPolicyParams) (*ApplicationSignInPolicy, error) {
	row := q.db.QueryRow(ctx, getAppSignInPolicy, arg.TenantID, arg.ApplicationID)
	var i ApplicationSignInPolicy
	err := row.Scan(
		&i.TenantID,
		&i.ApplicationID,
		&i.Rules,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const getTenantDefaultSignInPolicy = `-- name: GetTenantDefaultSignInPolicy :one
SELECT tenant_id, rules, created_at, updated_at
FROM tenant_default_sign_in_policies
WHERE tenant_id = $1
`

func (q *Queries) GetTenantDefaultSignInPolicy(ctx context.Context, tenantID string) (*TenantDefaultSignInPolicy, error) {
	row := q.db.QueryRow(ctx, getTenantDefaultSignInPolicy, tenantID)
	var i TenantDefaultSignInPolicy
	err := row.Scan(
		&i.TenantID,
		&i.Rules,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const listAppSignInPoliciesByTenant = `-- name: ListAppSignInPoliciesByTenant :many
SELECT tenant_id, application_id, rules, created_at, updated_at
FROM application_sign_in_policies
WHERE tenant_id = $1
`

func (q *Queries) ListAppSignInPoliciesByTenant(ctx context.Context, tenantID string) ([]*ApplicationSignInPolicy, error) {
	rows, err := q.db.Query(ctx, listAppSignInPoliciesByTenant, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*ApplicationSignInPolicy
	for rows.Next() {
		var i ApplicationSignInPolicy
		if err := rows.Scan(
			&i.TenantID,
			&i.ApplicationID,
			&i.Rules,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertAppSignInPolicy = `-- name: UpsertAppSignInPolicy :exec
INSERT INTO application_sign_in_policies (tenant_id, application_id, rules, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (tenant_id, application_id) DO UPDATE SET
  rules = EXCLUDED.rules,
  updated_at = EXCLUDED.updated_at
`

type UpsertAppSignInPolicyParams struct {
	TenantID      string
	ApplicationID string
	Rules         []byte
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

func (q *Queries) UpsertAppSignInPolicy(ctx context.Context, arg UpsertAppSignInPolicyParams) error {
	_, err := q.db.Exec(ctx, upsertAppSignInPolicy,
		arg.TenantID,
		arg.ApplicationID,
		arg.Rules,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const upsertTenantDefaultSignInPolicy = `-- name: UpsertTenantDefaultSignInPolicy :exec
INSERT INTO tenant_default_sign_in_policies (tenant_id, rules, created_at, updated_at)
VALUES ($1, $2, $3, $4)
ON CONFLICT (tenant_id) DO UPDATE SET
  rules = EXCLUDED.rules,
  updated_at = EXCLUDED.updated_at
`

type UpsertTenantDefaultSignInPolicyParams struct {
	TenantID  string
	Rules     []byte
	CreatedAt time.Time
	UpdatedAt time.Time
}

func (q *Queries) UpsertTenantDefaultSignInPolicy(ctx context.Context, arg UpsertTenantDefaultSignInPolicyParams) error {
	_, err := q.db.Exec(ctx, upsertTenantDefaultSignInPolicy,
		arg.TenantID,
		arg.Rules,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}
