// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: authentication_event_buckets.sql

package db_postgres

import (
	"context"
	"time"
)

const deleteAuthEventBucketsOlderThan = `-- name: DeleteAuthEventBucketsOlderThan :execrows
DELETE FROM authentication_event_buckets WHERE window_start < $1
`

func (q *Queries) DeleteAuthEventBucketsOlderThan(ctx context.Context, windowStart time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, deleteAuthEventBucketsOlderThan, windowStart)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listAuthEventBuckets = `-- name: ListAuthEventBuckets :many
SELECT tenant_id, kind, key_hash, window_start, count, first_seen, last_seen
FROM authentication_event_buckets
WHERE ($1::text = '' OR tenant_id = $1::text)
ORDER BY window_start DESC, kind DESC, key_hash DESC
LIMIT $2
`

type ListAuthEventBucketsParams struct {
	Column1 string
	Limit   int32
}

type ListAuthEventBucketsRow struct {
	TenantID    string
	Kind        string
	KeyHash     string
	WindowStart time.Time
	Count       int64
	FirstSeen   time.Time
	LastSeen    time.Time
}

func (q *Queries) ListAuthEventBuckets(ctx context.Context, arg ListAuthEventBucketsParams) ([]*ListAuthEventBucketsRow, error) {
	rows, err := q.db.Query(ctx, listAuthEventBuckets, arg.Column1, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*ListAuthEventBucketsRow
	for rows.Next() {
		var i ListAuthEventBucketsRow
		if err := rows.Scan(
			&i.TenantID,
			&i.Kind,
			&i.KeyHash,
			&i.WindowStart,
			&i.Count,
			&i.FirstSeen,
			&i.LastSeen,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuthEventBucketsAfter = `-- name: ListAuthEventBucketsAfter :many
SELECT tenant_id, kind, key_hash, window_start, count, first_seen, last_seen
FROM authentication_event_buckets
WHERE ($1::text = '' OR tenant_id = $1::text)
  AND (window_start, kind, key_hash) < ($2::timestamptz, $3::text, $4::text)
ORDER BY window_start DESC, kind DESC, key_hash DESC
LIMIT $5
`

type ListAuthEventBucketsAfterParams struct {
	Column1          string
	AfterWindowStart time.Time
	AfterKind        string
	AfterKeyHash     string
	PageLimit        int32
}

type ListAuthEventBucketsAfterRow struct {
	TenantID    string
	Kind        string
	KeyHash     string
	WindowStart time.Time
	Count       int64
	FirstSeen   time.Time
	LastSeen    time.Time
}

// Continuation page for ListAuthenticationEventBuckets keyset pagination
// (wi-159, ADR-158): resumes strictly after the (window_start, kind,
// key_hash) keyset of the last row the caller saw. kind/key_hash (not
// count, which isn't unique) is the tie-break matching the table's own
// PRIMARY KEY (tenant_id, kind, key_hash, window_start); all three columns
// sort DESC so the row-value comparison below matches ORDER BY exactly.
func (q *Queries) ListAuthEventBucketsAfter(ctx context.Context, arg ListAuthEventBucketsAfterParams) ([]*ListAuthEventBucketsAfterRow, error) {
	rows, err := q.db.Query(ctx, listAuthEventBucketsAfter,
		arg.Column1,
		arg.AfterWindowStart,
		arg.AfterKind,
		arg.AfterKeyHash,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*ListAuthEventBucketsAfterRow
	for rows.Next() {
		var i ListAuthEventBucketsAfterRow
		if err := rows.Scan(
			&i.TenantID,
			&i.Kind,
			&i.KeyHash,
			&i.WindowStart,
			&i.Count,
			&i.FirstSeen,
			&i.LastSeen,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuthEventBucketsBefore = `-- name: ListAuthEventBucketsBefore :many
SELECT tenant_id, kind, key_hash, window_start, count, first_seen, last_seen
FROM authentication_event_buckets
WHERE ($1::text = '' OR tenant_id = $1::text)
  AND (window_start, kind, key_hash) > ($2::timestamptz, $3::text, $4::text)
ORDER BY window_start ASC, kind ASC, key_hash ASC
LIMIT $5
`

type ListAuthEventBucketsBeforeParams struct {
	Column1           string
	BeforeWindowStart time.Time
	BeforeKind        string
	BeforeKeyHash     string
	PageLimit         int32
}

type ListAuthEventBucketsBeforeRow struct {
	TenantID    string
	Kind        string
	KeyHash     string
	WindowStart time.Time
	Count       int64
	FirstSeen   time.Time
	LastSeen    time.Time
}

func (q *Queries) ListAuthEventBucketsBefore(ctx context.Context, arg ListAuthEventBucketsBeforeParams) ([]*ListAuthEventBucketsBeforeRow, error) {
	rows, err := q.db.Query(ctx, listAuthEventBucketsBefore,
		arg.Column1,
		arg.BeforeWindowStart,
		arg.BeforeKind,
		arg.BeforeKeyHash,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*ListAuthEventBucketsBeforeRow
	for rows.Next() {
		var i ListAuthEventBucketsBeforeRow
		if err := rows.Scan(
			&i.TenantID,
			&i.Kind,
			&i.KeyHash,
			&i.WindowStart,
			&i.Count,
			&i.FirstSeen,
			&i.LastSeen,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordAuthEventBucket = `-- name: RecordAuthEventBucket :one
INSERT INTO authentication_event_buckets (tenant_id, kind, key_hash, window_start, count, first_seen, last_seen)
VALUES ($1, $2, $3, $4, 1, $5, $5)
ON CONFLICT (tenant_id, kind, key_hash, window_start)
DO UPDATE SET count = authentication_event_buckets.count + 1, last_seen = EXCLUDED.last_seen, updated_at = now()
RETURNING count, first_seen, last_seen, (xmax = 0) AS inserted
`

type RecordAuthEventBucketParams struct {
	TenantID    string
	Kind        string
	KeyHash     string
	WindowStart time.Time
	FirstSeen   time.Time
}

type RecordAuthEventBucketRow struct {
	Count     int64
	FirstSeen time.Time
	LastSeen  time.Time
	Inserted  bool
}

func (q *Queries) RecordAuthEventBucket(ctx context.Context, arg RecordAuthEventBucketParams) (*RecordAuthEventBucketRow, error) {
	row := q.db.QueryRow(ctx, recordAuthEventBucket,
		arg.TenantID,
		arg.Kind,
		arg.KeyHash,
		arg.WindowStart,
		arg.FirstSeen,
	)
	var i RecordAuthEventBucketRow
	err := row.Scan(
		&i.Count,
		&i.FirstSeen,
		&i.LastSeen,
		&i.Inserted,
	)
	return &i, err
}
