// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db_postgres

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type AuditEvent struct {
	ID         string
	TenantID   string
	Type       string
	UserID     pgtype.UUID
	CreatedAt  time.Time
	OccurredAt time.Time
	Payload    []byte
}
