// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: applications.sql

package sqlcgen

import (
	"context"
	"time"
)

const deleteApplication = `-- name: DeleteApplication :exec
DELETE FROM applications WHERE tenant_id = $1 AND application_id = $2
`

type DeleteApplicationParams struct {
	TenantID      string
	ApplicationID string
}

func (q *Queries) DeleteApplication(ctx context.Context, arg DeleteApplicationParams) error {
	_, err := q.db.Exec(ctx, deleteApplication, arg.TenantID, arg.ApplicationID)
	return err
}

const getApplicationByID = `-- name: GetApplicationByID :one
SELECT tenant_id, application_id, name, kind, status, icon_url, icon_object_key, launch_url, bindings, category_ids, created_at, updated_at
FROM applications
WHERE tenant_id = $1 AND application_id = $2
`

type GetApplicationByIDParams struct {
	TenantID      string
	ApplicationID string
}

func (q *Queries) GetApplicationByID(ctx context.Context, arg GetApplicationByIDParams) (*Application, error) {
	row := q.db.QueryRow(ctx, getApplicationByID, arg.TenantID, arg.ApplicationID)
	var i Application
	err := row.Scan(
		&i.TenantID,
		&i.ApplicationID,
		&i.Name,
		&i.Kind,
		&i.Status,
		&i.IconUrl,
		&i.IconObjectKey,
		&i.LaunchUrl,
		&i.Bindings,
		&i.CategoryIds,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const listApplicationsByTenant = `-- name: ListApplicationsByTenant :many
SELECT tenant_id, application_id, name, kind, status, icon_url, icon_object_key, launch_url, bindings, category_ids, created_at, updated_at
FROM applications
WHERE tenant_id = $1
ORDER BY name
`

func (q *Queries) ListApplicationsByTenant(ctx context.Context, tenantID string) ([]*Application, error) {
	rows, err := q.db.Query(ctx, listApplicationsByTenant, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*Application
	for rows.Next() {
		var i Application
		if err := rows.Scan(
			&i.TenantID,
			&i.ApplicationID,
			&i.Name,
			&i.Kind,
			&i.Status,
			&i.IconUrl,
			&i.IconObjectKey,
			&i.LaunchUrl,
			&i.Bindings,
			&i.CategoryIds,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeApplicationCategory = `-- name: RemoveApplicationCategory :exec
UPDATE applications SET category_ids = array_remove(category_ids, $2), updated_at = now()
WHERE tenant_id = $1 AND $2 = ANY(category_ids)
`

type RemoveApplicationCategoryParams struct {
	TenantID    string
	ArrayRemove interface{}
}

func (q *Queries) RemoveApplicationCategory(ctx context.Context, arg RemoveApplicationCategoryParams) error {
	_, err := q.db.Exec(ctx, removeApplicationCategory, arg.TenantID, arg.ArrayRemove)
	return err
}

const upsertApplication = `-- name: UpsertApplication :exec
INSERT INTO applications (tenant_id, application_id, name, kind, status, icon_url, icon_object_key, launch_url, bindings, category_ids, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
ON CONFLICT (application_id) DO UPDATE SET
  name = EXCLUDED.name,
  kind = EXCLUDED.kind,
  status = EXCLUDED.status,
  icon_url = EXCLUDED.icon_url,
  icon_object_key = EXCLUDED.icon_object_key,
  launch_url = EXCLUDED.launch_url,
  bindings = EXCLUDED.bindings,
  category_ids = EXCLUDED.category_ids,
  updated_at = EXCLUDED.updated_at
`

type UpsertApplicationParams struct {
	TenantID      string
	ApplicationID string
	Name          string
	Kind          string
	Status        string
	IconUrl       string
	IconObjectKey string
	LaunchUrl     string
	Bindings      []byte
	CategoryIds   []string
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

func (q *Queries) UpsertApplication(ctx context.Context, arg UpsertApplicationParams) error {
	_, err := q.db.Exec(ctx, upsertApplication,
		arg.TenantID,
		arg.ApplicationID,
		arg.Name,
		arg.Kind,
		arg.Status,
		arg.IconUrl,
		arg.IconObjectKey,
		arg.LaunchUrl,
		arg.Bindings,
		arg.CategoryIds,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}
