// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: application_icons.sql

package sqlcgen

import (
	"context"
	"time"
)

const deleteApplicationIconsByApplication = `-- name: DeleteApplicationIconsByApplication :exec
DELETE FROM application_icons i WHERE i.application_id = $2
  AND EXISTS (SELECT 1 FROM applications a WHERE a.tenant_id = $1 AND a.application_id = $2)
`

type DeleteApplicationIconsByApplicationParams struct {
	TenantID      string
	ApplicationID string
}

func (q *Queries) DeleteApplicationIconsByApplication(ctx context.Context, arg DeleteApplicationIconsByApplicationParams) error {
	_, err := q.db.Exec(ctx, deleteApplicationIconsByApplication, arg.TenantID, arg.ApplicationID)
	return err
}

const getApplicationIcon = `-- name: GetApplicationIcon :one
SELECT a.tenant_id, i.application_id, i.object_key, i.content_type, i.size_bytes, i.data, i.created_at, i.updated_at
FROM application_icons i JOIN applications a ON a.application_id = i.application_id
WHERE a.tenant_id = $1 AND i.application_id = $2 AND i.object_key = $3
`

type GetApplicationIconParams struct {
	TenantID      string
	ApplicationID string
	ObjectKey     string
}

type GetApplicationIconRow struct {
	TenantID      string
	ApplicationID string
	ObjectKey     string
	ContentType   string
	SizeBytes     int32
	Data          []byte
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

func (q *Queries) GetApplicationIcon(ctx context.Context, arg GetApplicationIconParams) (*GetApplicationIconRow, error) {
	row := q.db.QueryRow(ctx, getApplicationIcon, arg.TenantID, arg.ApplicationID, arg.ObjectKey)
	var i GetApplicationIconRow
	err := row.Scan(
		&i.TenantID,
		&i.ApplicationID,
		&i.ObjectKey,
		&i.ContentType,
		&i.SizeBytes,
		&i.Data,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const upsertApplicationIcon = `-- name: UpsertApplicationIcon :exec
INSERT INTO application_icons (application_id, object_key, content_type, size_bytes, data, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (application_id, object_key) DO UPDATE SET
  content_type = EXCLUDED.content_type,
  size_bytes = EXCLUDED.size_bytes,
  data = EXCLUDED.data,
  updated_at = EXCLUDED.updated_at
`

type UpsertApplicationIconParams struct {
	ApplicationID string
	ObjectKey     string
	ContentType   string
	SizeBytes     int32
	Data          []byte
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

func (q *Queries) UpsertApplicationIcon(ctx context.Context, arg UpsertApplicationIconParams) error {
	_, err := q.db.Exec(ctx, upsertApplicationIcon,
		arg.ApplicationID,
		arg.ObjectKey,
		arg.ContentType,
		arg.SizeBytes,
		arg.Data,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}
