// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db_postgres

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type TenantUserAttributeSchema struct {
	TenantID   string
	Attributes []byte
	CreatedAt  time.Time
	UpdatedAt  time.Time
}

type User struct {
	ID                string
	TenantID          string
	PreferredUsername string
	PasswordHash      string
	Name              pgtype.Text
	GivenName         pgtype.Text
	FamilyName        pgtype.Text
	Email             pgtype.Text
	EmailVerified     bool
	MfaEnrolled       bool
	CreatedAt         time.Time
	UpdatedAt         time.Time
	Roles             []byte
	Lifecycle         []byte
	Attributes        []byte
	SearchText        pgtype.Text
}
