// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db_postgres

import (
	"context"
)

type Querier interface {
	CountUsersByTenant(ctx context.Context, tenantID string) (int64, error)
	CountUsersByTenantFiltered(ctx context.Context, arg CountUsersByTenantFilteredParams) (int64, error)
	DeleteEmailChangeTokensForSub(ctx context.Context, userID string) error
	DeleteTenantUserAttributeSchema(ctx context.Context, tenantID string) error
	FindTenantUserAttributeSchemaByTenant(ctx context.Context, tenantID string) (*TenantUserAttributeSchema, error)
	FindUnusedEmailChangeToken(ctx context.Context, tokenHash string) (*FindUnusedEmailChangeTokenRow, error)
	FindUserByEmail(ctx context.Context, arg FindUserByEmailParams) (*User, error)
	FindUserBySub(ctx context.Context, id string) (*User, error)
	FindUserBySubIncludingDeleted(ctx context.Context, id string) (*User, error)
	FindUserByUsername(ctx context.Context, arg FindUserByUsernameParams) (*User, error)
	InsertEmailChangeToken(ctx context.Context, arg InsertEmailChangeTokenParams) error
	// CSV インポートの行の確定と同じトランザクションで、所有モジュールの外のテーブルへ書く。
	InsertImportedPasswordHistory(ctx context.Context, arg InsertImportedPasswordHistoryParams) error
	InsertUserImportAuditEvent(ctx context.Context, arg InsertUserImportAuditEventParams) error
	// Pending deletions and tombstones whose purge has not finished. The grace
	// period is decided by the caller.
	ListUserPurgeCandidates(ctx context.Context, tenantID string) ([]*User, error)
	ListUsersByTenant(ctx context.Context, tenantID string) ([]*User, error)
	// First page of ListAdminUsers keyset pagination (wi-159): stable
	// sort by (preferred_username, id) so admins see the pre-existing alphabetical
	// order, with id as tie-break for uniqueness.
	ListUsersByTenantPage(ctx context.Context, arg ListUsersByTenantPageParams) ([]*User, error)
	// Continuation page: resumes strictly after the (preferred_username, id) keyset
	// of the last row the caller saw.
	ListUsersByTenantPageAfter(ctx context.Context, arg ListUsersByTenantPageAfterParams) ([]*User, error)
	ListUsersByTenantPageAfterFiltered(ctx context.Context, arg ListUsersByTenantPageAfterFilteredParams) ([]*User, error)
	ListUsersByTenantPageBefore(ctx context.Context, arg ListUsersByTenantPageBeforeParams) ([]*User, error)
	ListUsersByTenantPageBeforeFiltered(ctx context.Context, arg ListUsersByTenantPageBeforeFilteredParams) ([]*User, error)
	ListUsersByTenantPageEnd(ctx context.Context, arg ListUsersByTenantPageEndParams) ([]*User, error)
	ListUsersByTenantPageEndFiltered(ctx context.Context, arg ListUsersByTenantPageEndFilteredParams) ([]*User, error)
	ListUsersByTenantPageFiltered(ctx context.Context, arg ListUsersByTenantPageFilteredParams) ([]*User, error)
	MarkEmailChangeTokenUsed(ctx context.Context, arg MarkEmailChangeTokenUsedParams) (*MarkEmailChangeTokenUsedRow, error)
	SaveTenantUserAttributeSchema(ctx context.Context, arg SaveTenantUserAttributeSchemaParams) error
	SaveUser(ctx context.Context, arg SaveUserParams) error
}

var _ Querier = (*Queries)(nil)
