// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db_postgres

import (
	"context"
)

type Querier interface {
	ConsumeEmailChangeToken(ctx context.Context, tokenHash string) (*ConsumeEmailChangeTokenRow, error)
	DeleteEmailChangeTokensForSub(ctx context.Context, userID string) error
	DeleteTenantUserAttributeSchema(ctx context.Context, tenantID string) error
	FindTenantUserAttributeSchemaByTenant(ctx context.Context, tenantID string) (*TenantUserAttributeSchema, error)
	FindUserByEmail(ctx context.Context, arg FindUserByEmailParams) (*User, error)
	FindUserBySub(ctx context.Context, id string) (*User, error)
	FindUserBySubIncludingDeleted(ctx context.Context, id string) (*User, error)
	FindUserByUsername(ctx context.Context, arg FindUserByUsernameParams) (*User, error)
	InsertEmailChangeToken(ctx context.Context, arg InsertEmailChangeTokenParams) error
	ListUsersByTenant(ctx context.Context, tenantID string) ([]*User, error)
	// First page of ListAdminUsers keyset pagination (wi-159, ADR-158): stable
	// sort by (preferred_username, id) so admins see the pre-existing alphabetical
	// order, with id as tie-break for uniqueness.
	ListUsersByTenantPage(ctx context.Context, arg ListUsersByTenantPageParams) ([]*User, error)
	// Continuation page: resumes strictly after the (preferred_username, id) keyset
	// of the last row the caller saw.
	ListUsersByTenantPageAfter(ctx context.Context, arg ListUsersByTenantPageAfterParams) ([]*User, error)
	ListUsersByTenantPageAfterFiltered(ctx context.Context, arg ListUsersByTenantPageAfterFilteredParams) ([]*User, error)
	ListUsersByTenantPageBefore(ctx context.Context, arg ListUsersByTenantPageBeforeParams) ([]*User, error)
	ListUsersByTenantPageBeforeFiltered(ctx context.Context, arg ListUsersByTenantPageBeforeFilteredParams) ([]*User, error)
	ListUsersByTenantPageFiltered(ctx context.Context, arg ListUsersByTenantPageFilteredParams) ([]*User, error)
	SaveTenantUserAttributeSchema(ctx context.Context, arg SaveTenantUserAttributeSchemaParams) error
	SaveUser(ctx context.Context, arg SaveUserParams) error
}

var _ Querier = (*Queries)(nil)
