// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user_import.sql

package db_postgres

import (
	"context"
	"time"
)

const insertImportedPasswordHistory = `-- name: InsertImportedPasswordHistory :exec
INSERT INTO password_history (id, user_id, encoded, created_at) VALUES ($1, $2, $3, $4)
`

type InsertImportedPasswordHistoryParams struct {
	ID        string
	UserID    string
	Encoded   string
	CreatedAt time.Time
}

// CSV インポートの行の確定と同じトランザクションで、所有 Context の外のテーブルへ書く。
func (q *Queries) InsertImportedPasswordHistory(ctx context.Context, arg InsertImportedPasswordHistoryParams) error {
	_, err := q.db.Exec(ctx, insertImportedPasswordHistory,
		arg.ID,
		arg.UserID,
		arg.Encoded,
		arg.CreatedAt,
	)
	return err
}

const insertUserImportAuditEvent = `-- name: InsertUserImportAuditEvent :exec
INSERT INTO audit_events (id, tenant_id, type, user_id, occurred_at, payload)
VALUES ($1, $2, $3, $4::uuid, $5, $6)
`

type InsertUserImportAuditEventParams struct {
	ID         string
	TenantID   string
	Type       string
	UserID     string
	OccurredAt time.Time
	Payload    []byte
}

func (q *Queries) InsertUserImportAuditEvent(ctx context.Context, arg InsertUserImportAuditEventParams) error {
	_, err := q.db.Exec(ctx, insertUserImportAuditEvent,
		arg.ID,
		arg.TenantID,
		arg.Type,
		arg.UserID,
		arg.OccurredAt,
		arg.Payload,
	)
	return err
}
