// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package db_postgres

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const countUsersByTenant = `-- name: CountUsersByTenant :one
SELECT count(*) FROM users
WHERE tenant_id=$1 AND (lifecycle->>'status' IS DISTINCT FROM 'deleted')
`

func (q *Queries) CountUsersByTenant(ctx context.Context, tenantID string) (int64, error) {
	row := q.db.QueryRow(ctx, countUsersByTenant, tenantID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUsersByTenantFiltered = `-- name: CountUsersByTenantFiltered :one
SELECT count(*) FROM users
WHERE tenant_id=$1 AND (lifecycle->>'status' IS DISTINCT FROM 'deleted')
  AND ($2::text = '' OR search_text ILIKE '%' || lower($2::text) || '%' ESCAPE '\')
  AND ($3::text = '' OR coalesce(lifecycle->>'status', 'active') = $3::text)
`

type CountUsersByTenantFilteredParams struct {
	TenantID     string
	FilterQuery  string
	FilterStatus string
}

func (q *Queries) CountUsersByTenantFiltered(ctx context.Context, arg CountUsersByTenantFilteredParams) (int64, error) {
	row := q.db.QueryRow(ctx, countUsersByTenantFiltered, arg.TenantID, arg.FilterQuery, arg.FilterStatus)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const findUserByEmail = `-- name: FindUserByEmail :one
SELECT id,tenant_id,preferred_username,password_hash,name,given_name,family_name,email,
email_verified,mfa_enrolled,created_at,updated_at,roles,lifecycle,attributes,search_text FROM users
WHERE tenant_id=$1 AND lower(email)=lower($2) AND (lifecycle->>'status' IS DISTINCT FROM 'deleted')
LIMIT 1
`

type FindUserByEmailParams struct {
	TenantID string
	Lower    string
}

func (q *Queries) FindUserByEmail(ctx context.Context, arg FindUserByEmailParams) (*User, error) {
	row := q.db.QueryRow(ctx, findUserByEmail, arg.TenantID, arg.Lower)
	var i User
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.PreferredUsername,
		&i.PasswordHash,
		&i.Name,
		&i.GivenName,
		&i.FamilyName,
		&i.Email,
		&i.EmailVerified,
		&i.MfaEnrolled,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Roles,
		&i.Lifecycle,
		&i.Attributes,
		&i.SearchText,
	)
	return &i, err
}

const findUserBySub = `-- name: FindUserBySub :one
SELECT id,tenant_id,preferred_username,password_hash,name,given_name,family_name,email,
email_verified,mfa_enrolled,created_at,updated_at,roles,lifecycle,attributes,search_text FROM users
WHERE id=$1 AND (lifecycle->>'status' IS DISTINCT FROM 'deleted')
`

func (q *Queries) FindUserBySub(ctx context.Context, id string) (*User, error) {
	row := q.db.QueryRow(ctx, findUserBySub, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.PreferredUsername,
		&i.PasswordHash,
		&i.Name,
		&i.GivenName,
		&i.FamilyName,
		&i.Email,
		&i.EmailVerified,
		&i.MfaEnrolled,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Roles,
		&i.Lifecycle,
		&i.Attributes,
		&i.SearchText,
	)
	return &i, err
}

const findUserBySubIncludingDeleted = `-- name: FindUserBySubIncludingDeleted :one
SELECT id,tenant_id,preferred_username,password_hash,name,given_name,family_name,email,
email_verified,mfa_enrolled,created_at,updated_at,roles,lifecycle,attributes,search_text FROM users
WHERE id=$1
`

func (q *Queries) FindUserBySubIncludingDeleted(ctx context.Context, id string) (*User, error) {
	row := q.db.QueryRow(ctx, findUserBySubIncludingDeleted, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.PreferredUsername,
		&i.PasswordHash,
		&i.Name,
		&i.GivenName,
		&i.FamilyName,
		&i.Email,
		&i.EmailVerified,
		&i.MfaEnrolled,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Roles,
		&i.Lifecycle,
		&i.Attributes,
		&i.SearchText,
	)
	return &i, err
}

const findUserByUsername = `-- name: FindUserByUsername :one
SELECT id,tenant_id,preferred_username,password_hash,name,given_name,family_name,email,
email_verified,mfa_enrolled,created_at,updated_at,roles,lifecycle,attributes,search_text FROM users
WHERE tenant_id=$1 AND preferred_username=$2 AND (lifecycle->>'status' IS DISTINCT FROM 'deleted')
`

type FindUserByUsernameParams struct {
	TenantID          string
	PreferredUsername string
}

func (q *Queries) FindUserByUsername(ctx context.Context, arg FindUserByUsernameParams) (*User, error) {
	row := q.db.QueryRow(ctx, findUserByUsername, arg.TenantID, arg.PreferredUsername)
	var i User
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.PreferredUsername,
		&i.PasswordHash,
		&i.Name,
		&i.GivenName,
		&i.FamilyName,
		&i.Email,
		&i.EmailVerified,
		&i.MfaEnrolled,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Roles,
		&i.Lifecycle,
		&i.Attributes,
		&i.SearchText,
	)
	return &i, err
}

const listUsersByTenant = `-- name: ListUsersByTenant :many
SELECT id,tenant_id,preferred_username,password_hash,name,given_name,family_name,email,
email_verified,mfa_enrolled,created_at,updated_at,roles,lifecycle,attributes,search_text FROM users
WHERE tenant_id=$1 AND (lifecycle->>'status' IS DISTINCT FROM 'deleted')
ORDER BY preferred_username
`

func (q *Queries) ListUsersByTenant(ctx context.Context, tenantID string) ([]*User, error) {
	rows, err := q.db.Query(ctx, listUsersByTenant, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.PreferredUsername,
			&i.PasswordHash,
			&i.Name,
			&i.GivenName,
			&i.FamilyName,
			&i.Email,
			&i.EmailVerified,
			&i.MfaEnrolled,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Roles,
			&i.Lifecycle,
			&i.Attributes,
			&i.SearchText,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsersByTenantPage = `-- name: ListUsersByTenantPage :many
SELECT id,tenant_id,preferred_username,password_hash,name,given_name,family_name,email,
email_verified,mfa_enrolled,created_at,updated_at,roles,lifecycle,attributes,search_text FROM users
WHERE tenant_id=$1 AND (lifecycle->>'status' IS DISTINCT FROM 'deleted')
ORDER BY preferred_username, id
LIMIT $2
`

type ListUsersByTenantPageParams struct {
	TenantID string
	Limit    int32
}

// First page of ListAdminUsers keyset pagination (wi-159): stable
// sort by (preferred_username, id) so admins see the pre-existing alphabetical
// order, with id as tie-break for uniqueness.
func (q *Queries) ListUsersByTenantPage(ctx context.Context, arg ListUsersByTenantPageParams) ([]*User, error) {
	rows, err := q.db.Query(ctx, listUsersByTenantPage, arg.TenantID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.PreferredUsername,
			&i.PasswordHash,
			&i.Name,
			&i.GivenName,
			&i.FamilyName,
			&i.Email,
			&i.EmailVerified,
			&i.MfaEnrolled,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Roles,
			&i.Lifecycle,
			&i.Attributes,
			&i.SearchText,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsersByTenantPageAfter = `-- name: ListUsersByTenantPageAfter :many
SELECT id,tenant_id,preferred_username,password_hash,name,given_name,family_name,email,
email_verified,mfa_enrolled,created_at,updated_at,roles,lifecycle,attributes,search_text FROM users
WHERE tenant_id=$1 AND (lifecycle->>'status' IS DISTINCT FROM 'deleted')
  AND (preferred_username, id) > ($2::text, $3::uuid)
ORDER BY preferred_username, id
LIMIT $4
`

type ListUsersByTenantPageAfterParams struct {
	TenantID      string
	AfterUsername string
	AfterID       string
	PageLimit     int32
}

// Continuation page: resumes strictly after the (preferred_username, id) keyset
// of the last row the caller saw.
func (q *Queries) ListUsersByTenantPageAfter(ctx context.Context, arg ListUsersByTenantPageAfterParams) ([]*User, error) {
	rows, err := q.db.Query(ctx, listUsersByTenantPageAfter,
		arg.TenantID,
		arg.AfterUsername,
		arg.AfterID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.PreferredUsername,
			&i.PasswordHash,
			&i.Name,
			&i.GivenName,
			&i.FamilyName,
			&i.Email,
			&i.EmailVerified,
			&i.MfaEnrolled,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Roles,
			&i.Lifecycle,
			&i.Attributes,
			&i.SearchText,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsersByTenantPageAfterFiltered = `-- name: ListUsersByTenantPageAfterFiltered :many
SELECT id,tenant_id,preferred_username,password_hash,name,given_name,family_name,email,
email_verified,mfa_enrolled,created_at,updated_at,roles,lifecycle,attributes,search_text FROM users
WHERE tenant_id=$1 AND (lifecycle->>'status' IS DISTINCT FROM 'deleted')
  AND ($2::text = '' OR search_text ILIKE '%' || lower($2::text) || '%' ESCAPE '\')
  AND ($3::text = '' OR coalesce(lifecycle->>'status', 'active') = $3::text)
  AND (preferred_username, id) > ($4::text, $5::uuid)
ORDER BY preferred_username, id
LIMIT $6
`

type ListUsersByTenantPageAfterFilteredParams struct {
	TenantID      string
	FilterQuery   string
	FilterStatus  string
	AfterUsername string
	AfterID       string
	PageLimit     int32
}

func (q *Queries) ListUsersByTenantPageAfterFiltered(ctx context.Context, arg ListUsersByTenantPageAfterFilteredParams) ([]*User, error) {
	rows, err := q.db.Query(ctx, listUsersByTenantPageAfterFiltered,
		arg.TenantID,
		arg.FilterQuery,
		arg.FilterStatus,
		arg.AfterUsername,
		arg.AfterID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.PreferredUsername,
			&i.PasswordHash,
			&i.Name,
			&i.GivenName,
			&i.FamilyName,
			&i.Email,
			&i.EmailVerified,
			&i.MfaEnrolled,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Roles,
			&i.Lifecycle,
			&i.Attributes,
			&i.SearchText,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsersByTenantPageBefore = `-- name: ListUsersByTenantPageBefore :many
SELECT id,tenant_id,preferred_username,password_hash,name,given_name,family_name,email,
email_verified,mfa_enrolled,created_at,updated_at,roles,lifecycle,attributes,search_text FROM users
WHERE tenant_id=$1 AND (lifecycle->>'status' IS DISTINCT FROM 'deleted')
  AND (preferred_username, id) < ($2::text, $3::uuid)
ORDER BY preferred_username DESC, id DESC
LIMIT $4
`

type ListUsersByTenantPageBeforeParams struct {
	TenantID       string
	BeforeUsername string
	BeforeID       string
	PageLimit      int32
}

func (q *Queries) ListUsersByTenantPageBefore(ctx context.Context, arg ListUsersByTenantPageBeforeParams) ([]*User, error) {
	rows, err := q.db.Query(ctx, listUsersByTenantPageBefore,
		arg.TenantID,
		arg.BeforeUsername,
		arg.BeforeID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.PreferredUsername,
			&i.PasswordHash,
			&i.Name,
			&i.GivenName,
			&i.FamilyName,
			&i.Email,
			&i.EmailVerified,
			&i.MfaEnrolled,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Roles,
			&i.Lifecycle,
			&i.Attributes,
			&i.SearchText,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsersByTenantPageBeforeFiltered = `-- name: ListUsersByTenantPageBeforeFiltered :many
SELECT id,tenant_id,preferred_username,password_hash,name,given_name,family_name,email,
email_verified,mfa_enrolled,created_at,updated_at,roles,lifecycle,attributes,search_text FROM users
WHERE tenant_id=$1 AND (lifecycle->>'status' IS DISTINCT FROM 'deleted')
  AND ($2::text = '' OR search_text ILIKE '%' || lower($2::text) || '%' ESCAPE '\')
  AND ($3::text = '' OR coalesce(lifecycle->>'status', 'active') = $3::text)
  AND (preferred_username, id) < ($4::text, $5::uuid)
ORDER BY preferred_username DESC, id DESC
LIMIT $6
`

type ListUsersByTenantPageBeforeFilteredParams struct {
	TenantID       string
	FilterQuery    string
	FilterStatus   string
	BeforeUsername string
	BeforeID       string
	PageLimit      int32
}

func (q *Queries) ListUsersByTenantPageBeforeFiltered(ctx context.Context, arg ListUsersByTenantPageBeforeFilteredParams) ([]*User, error) {
	rows, err := q.db.Query(ctx, listUsersByTenantPageBeforeFiltered,
		arg.TenantID,
		arg.FilterQuery,
		arg.FilterStatus,
		arg.BeforeUsername,
		arg.BeforeID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.PreferredUsername,
			&i.PasswordHash,
			&i.Name,
			&i.GivenName,
			&i.FamilyName,
			&i.Email,
			&i.EmailVerified,
			&i.MfaEnrolled,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Roles,
			&i.Lifecycle,
			&i.Attributes,
			&i.SearchText,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsersByTenantPageEnd = `-- name: ListUsersByTenantPageEnd :many
SELECT id,tenant_id,preferred_username,password_hash,name,given_name,family_name,email,
email_verified,mfa_enrolled,created_at,updated_at,roles,lifecycle,attributes,search_text FROM users
WHERE tenant_id=$1 AND (lifecycle->>'status' IS DISTINCT FROM 'deleted')
ORDER BY preferred_username DESC, id DESC
LIMIT $2
`

type ListUsersByTenantPageEndParams struct {
	TenantID  string
	PageLimit int32
}

func (q *Queries) ListUsersByTenantPageEnd(ctx context.Context, arg ListUsersByTenantPageEndParams) ([]*User, error) {
	rows, err := q.db.Query(ctx, listUsersByTenantPageEnd, arg.TenantID, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.PreferredUsername,
			&i.PasswordHash,
			&i.Name,
			&i.GivenName,
			&i.FamilyName,
			&i.Email,
			&i.EmailVerified,
			&i.MfaEnrolled,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Roles,
			&i.Lifecycle,
			&i.Attributes,
			&i.SearchText,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsersByTenantPageEndFiltered = `-- name: ListUsersByTenantPageEndFiltered :many
SELECT id,tenant_id,preferred_username,password_hash,name,given_name,family_name,email,
email_verified,mfa_enrolled,created_at,updated_at,roles,lifecycle,attributes,search_text FROM users
WHERE tenant_id=$1 AND (lifecycle->>'status' IS DISTINCT FROM 'deleted')
  AND ($2::text = '' OR search_text ILIKE '%' || lower($2::text) || '%' ESCAPE '\')
  AND ($3::text = '' OR coalesce(lifecycle->>'status', 'active') = $3::text)
ORDER BY preferred_username DESC, id DESC
LIMIT $4
`

type ListUsersByTenantPageEndFilteredParams struct {
	TenantID     string
	FilterQuery  string
	FilterStatus string
	PageLimit    int32
}

func (q *Queries) ListUsersByTenantPageEndFiltered(ctx context.Context, arg ListUsersByTenantPageEndFilteredParams) ([]*User, error) {
	rows, err := q.db.Query(ctx, listUsersByTenantPageEndFiltered,
		arg.TenantID,
		arg.FilterQuery,
		arg.FilterStatus,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.PreferredUsername,
			&i.PasswordHash,
			&i.Name,
			&i.GivenName,
			&i.FamilyName,
			&i.Email,
			&i.EmailVerified,
			&i.MfaEnrolled,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Roles,
			&i.Lifecycle,
			&i.Attributes,
			&i.SearchText,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsersByTenantPageFiltered = `-- name: ListUsersByTenantPageFiltered :many
SELECT id,tenant_id,preferred_username,password_hash,name,given_name,family_name,email,
email_verified,mfa_enrolled,created_at,updated_at,roles,lifecycle,attributes,search_text FROM users
WHERE tenant_id=$1 AND (lifecycle->>'status' IS DISTINCT FROM 'deleted')
  AND ($2::text = '' OR search_text ILIKE '%' || lower($2::text) || '%' ESCAPE '\')
  AND ($3::text = '' OR coalesce(lifecycle->>'status', 'active') = $3::text)
ORDER BY preferred_username, id
LIMIT $4
`

type ListUsersByTenantPageFilteredParams struct {
	TenantID     string
	FilterQuery  string
	FilterStatus string
	PageLimit    int32
}

func (q *Queries) ListUsersByTenantPageFiltered(ctx context.Context, arg ListUsersByTenantPageFilteredParams) ([]*User, error) {
	rows, err := q.db.Query(ctx, listUsersByTenantPageFiltered,
		arg.TenantID,
		arg.FilterQuery,
		arg.FilterStatus,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.PreferredUsername,
			&i.PasswordHash,
			&i.Name,
			&i.GivenName,
			&i.FamilyName,
			&i.Email,
			&i.EmailVerified,
			&i.MfaEnrolled,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Roles,
			&i.Lifecycle,
			&i.Attributes,
			&i.SearchText,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const saveUser = `-- name: SaveUser :exec
INSERT INTO users (id,tenant_id,preferred_username,password_hash,name,given_name,family_name,email,
 email_verified,mfa_enrolled,created_at,updated_at,roles,lifecycle,attributes)
VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15)
ON CONFLICT (id) DO UPDATE SET preferred_username=EXCLUDED.preferred_username,
 password_hash=EXCLUDED.password_hash,name=EXCLUDED.name,given_name=EXCLUDED.given_name,
 family_name=EXCLUDED.family_name,email=EXCLUDED.email,email_verified=EXCLUDED.email_verified,
 mfa_enrolled=EXCLUDED.mfa_enrolled,roles=EXCLUDED.roles,lifecycle=EXCLUDED.lifecycle,
 attributes=EXCLUDED.attributes,updated_at=EXCLUDED.updated_at
`

type SaveUserParams struct {
	ID                string
	TenantID          string
	PreferredUsername string
	PasswordHash      string
	Name              pgtype.Text
	GivenName         pgtype.Text
	FamilyName        pgtype.Text
	Email             pgtype.Text
	EmailVerified     bool
	MfaEnrolled       bool
	CreatedAt         time.Time
	UpdatedAt         time.Time
	Roles             []byte
	Lifecycle         []byte
	Attributes        []byte
}

func (q *Queries) SaveUser(ctx context.Context, arg SaveUserParams) error {
	_, err := q.db.Exec(ctx, saveUser,
		arg.ID,
		arg.TenantID,
		arg.PreferredUsername,
		arg.PasswordHash,
		arg.Name,
		arg.GivenName,
		arg.FamilyName,
		arg.Email,
		arg.EmailVerified,
		arg.MfaEnrolled,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.Roles,
		arg.Lifecycle,
		arg.Attributes,
	)
	return err
}
