// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"context"
)

type Querier interface {
	DeleteWsFedRelyingParty(ctx context.Context, arg DeleteWsFedRelyingPartyParams) error
	GetWsFedRelyingParty(ctx context.Context, arg GetWsFedRelyingPartyParams) (*WsfedRelyingParty, error)
	ListWsFedRelyingPartiesByTenant(ctx context.Context, tenantID string) ([]*WsfedRelyingParty, error)
	UpsertWsFedRelyingParty(ctx context.Context, arg UpsertWsFedRelyingPartyParams) error
}

var _ Querier = (*Queries)(nil)
