// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db_postgres

import (
	"context"
)

type Querier interface {
	DeleteExpiredRateLimitCountersBatch(ctx context.Context, arg DeleteExpiredRateLimitCountersBatchParams) (int64, error)
	// Allow の read-modify-write を直列化する行ロック取得。
	LockRateLimitCounter(ctx context.Context, arg LockRateLimitCounterParams) (*LockRateLimitCounterRow, error)
	UpsertRateLimitCounter(ctx context.Context, arg UpsertRateLimitCounterParams) error
}

var _ Querier = (*Queries)(nil)
