// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: rate_limiter.sql

package db_postgres

import (
	"context"
	"time"
)

const deleteExpiredRateLimitCountersBatch = `-- name: DeleteExpiredRateLimitCountersBatch :execrows
DELETE FROM endpoint_rate_limit_counters AS o
WHERE (o.tenant_id, o.policy_id, o.key_hash) IN (
    SELECT s.tenant_id, s.policy_id, s.key_hash
    FROM endpoint_rate_limit_counters AS s
    WHERE s.window_expires_at < $1
    LIMIT $2
)
`

type DeleteExpiredRateLimitCountersBatchParams struct {
	Cutoff     time.Time
	BatchLimit int32
}

func (q *Queries) DeleteExpiredRateLimitCountersBatch(ctx context.Context, arg DeleteExpiredRateLimitCountersBatchParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredRateLimitCountersBatch, arg.Cutoff, arg.BatchLimit)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const lockRateLimitCounter = `-- name: LockRateLimitCounter :one
SELECT count, window_expires_at FROM endpoint_rate_limit_counters
WHERE tenant_id = $1 AND policy_id = $2 AND key_hash = $3
FOR UPDATE
`

type LockRateLimitCounterParams struct {
	TenantID string
	PolicyID string
	KeyHash  string
}

type LockRateLimitCounterRow struct {
	Count           int32
	WindowExpiresAt time.Time
}

// Allow の read-modify-write を直列化する行ロック取得。
func (q *Queries) LockRateLimitCounter(ctx context.Context, arg LockRateLimitCounterParams) (*LockRateLimitCounterRow, error) {
	row := q.db.QueryRow(ctx, lockRateLimitCounter, arg.TenantID, arg.PolicyID, arg.KeyHash)
	var i LockRateLimitCounterRow
	err := row.Scan(&i.Count, &i.WindowExpiresAt)
	return &i, err
}

const upsertRateLimitCounter = `-- name: UpsertRateLimitCounter :exec
INSERT INTO endpoint_rate_limit_counters (tenant_id, policy_id, key_hash, count, window_expires_at)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (tenant_id, policy_id, key_hash) DO UPDATE
    SET count = EXCLUDED.count, window_expires_at = EXCLUDED.window_expires_at, updated_at = now()
`

type UpsertRateLimitCounterParams struct {
	TenantID        string
	PolicyID        string
	KeyHash         string
	Count           int32
	WindowExpiresAt time.Time
}

func (q *Queries) UpsertRateLimitCounter(ctx context.Context, arg UpsertRateLimitCounterParams) error {
	_, err := q.db.Exec(ctx, upsertRateLimitCounter,
		arg.TenantID,
		arg.PolicyID,
		arg.KeyHash,
		arg.Count,
		arg.WindowExpiresAt,
	)
	return err
}
