// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: provisioning.sql

package db_postgres

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const attachProvisioningDeliveryJob = `-- name: AttachProvisioningDeliveryJob :execrows
UPDATE provisioning_deliveries SET job_id=$3,updated_at=now() WHERE tenant_id=$1 AND id=$2 AND job_id IS NULL
`

type AttachProvisioningDeliveryJobParams struct {
	TenantID string
	ID       string
	JobID    pgtype.UUID
}

func (q *Queries) AttachProvisioningDeliveryJob(ctx context.Context, arg AttachProvisioningDeliveryJobParams) (int64, error) {
	result, err := q.db.Exec(ctx, attachProvisioningDeliveryJob, arg.TenantID, arg.ID, arg.JobID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteProvisioningConnection = `-- name: DeleteProvisioningConnection :exec
DELETE FROM provisioning_connections WHERE tenant_id=$1 AND application_id=$2
`

type DeleteProvisioningConnectionParams struct {
	TenantID      string
	ApplicationID string
}

func (q *Queries) DeleteProvisioningConnection(ctx context.Context, arg DeleteProvisioningConnectionParams) error {
	_, err := q.db.Exec(ctx, deleteProvisioningConnection, arg.TenantID, arg.ApplicationID)
	return err
}

const findProvisioningConnection = `-- name: FindProvisioningConnection :one
SELECT application_id, tenant_id, status, base_url, credential_id, auth_method,
credential_oauth2_token_url, credential_oauth2_client_id, credential_oauth2_scope,
credential_created_at, credential_rotated_at, capabilities, feature_flags, scope, group_push,
attribute_mappings, matching, deprovision_policy, rate_limit_per_minute, max_attempts,
notification_email, quarantine_after_consecutive_failures, health, consecutive_failure_count,
last_full_sync_at, quarantined_at, quarantine_reason, created_at, updated_at
FROM provisioning_connections WHERE tenant_id=$1 AND application_id=$2
`

type FindProvisioningConnectionParams struct {
	TenantID      string
	ApplicationID string
}

type FindProvisioningConnectionRow struct {
	ApplicationID                      string
	TenantID                           string
	Status                             string
	BaseUrl                            string
	CredentialID                       string
	AuthMethod                         string
	CredentialOauth2TokenUrl           string
	CredentialOauth2ClientID           string
	CredentialOauth2Scope              string
	CredentialCreatedAt                time.Time
	CredentialRotatedAt                pgtype.Timestamptz
	Capabilities                       []byte
	FeatureFlags                       []byte
	Scope                              string
	GroupPush                          []byte
	AttributeMappings                  []byte
	Matching                           []byte
	DeprovisionPolicy                  []byte
	RateLimitPerMinute                 int32
	MaxAttempts                        int32
	NotificationEmail                  pgtype.Text
	QuarantineAfterConsecutiveFailures int32
	Health                             string
	ConsecutiveFailureCount            int32
	LastFullSyncAt                     pgtype.Timestamptz
	QuarantinedAt                      pgtype.Timestamptz
	QuarantineReason                   pgtype.Text
	CreatedAt                          time.Time
	UpdatedAt                          time.Time
}

func (q *Queries) FindProvisioningConnection(ctx context.Context, arg FindProvisioningConnectionParams) (*FindProvisioningConnectionRow, error) {
	row := q.db.QueryRow(ctx, findProvisioningConnection, arg.TenantID, arg.ApplicationID)
	var i FindProvisioningConnectionRow
	err := row.Scan(
		&i.ApplicationID,
		&i.TenantID,
		&i.Status,
		&i.BaseUrl,
		&i.CredentialID,
		&i.AuthMethod,
		&i.CredentialOauth2TokenUrl,
		&i.CredentialOauth2ClientID,
		&i.CredentialOauth2Scope,
		&i.CredentialCreatedAt,
		&i.CredentialRotatedAt,
		&i.Capabilities,
		&i.FeatureFlags,
		&i.Scope,
		&i.GroupPush,
		&i.AttributeMappings,
		&i.Matching,
		&i.DeprovisionPolicy,
		&i.RateLimitPerMinute,
		&i.MaxAttempts,
		&i.NotificationEmail,
		&i.QuarantineAfterConsecutiveFailures,
		&i.Health,
		&i.ConsecutiveFailureCount,
		&i.LastFullSyncAt,
		&i.QuarantinedAt,
		&i.QuarantineReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const findProvisioningDelivery = `-- name: FindProvisioningDelivery :one
SELECT id, tenant_id, connection_id, source_type, source_id, source_version, operation, status, job_id, last_error, created_at, updated_at, completed_at
FROM provisioning_deliveries WHERE tenant_id=$1 AND id=$2
`

type FindProvisioningDeliveryParams struct {
	TenantID string
	ID       string
}

func (q *Queries) FindProvisioningDelivery(ctx context.Context, arg FindProvisioningDeliveryParams) (*ProvisioningDelivery, error) {
	row := q.db.QueryRow(ctx, findProvisioningDelivery, arg.TenantID, arg.ID)
	var i ProvisioningDelivery
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ConnectionID,
		&i.SourceType,
		&i.SourceID,
		&i.SourceVersion,
		&i.Operation,
		&i.Status,
		&i.JobID,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return &i, err
}

const findRemoteResourceLink = `-- name: FindRemoteResourceLink :one
SELECT connection_id,tenant_id,source_type,source_id,remote_id,external_id,etag,last_synced_version,updated_at
FROM provisioning_remote_links WHERE connection_id=$1 AND source_type=$2 AND source_id=$3
`

type FindRemoteResourceLinkParams struct {
	ConnectionID string
	SourceType   string
	SourceID     string
}

func (q *Queries) FindRemoteResourceLink(ctx context.Context, arg FindRemoteResourceLinkParams) (*ProvisioningRemoteLink, error) {
	row := q.db.QueryRow(ctx, findRemoteResourceLink, arg.ConnectionID, arg.SourceType, arg.SourceID)
	var i ProvisioningRemoteLink
	err := row.Scan(
		&i.ConnectionID,
		&i.TenantID,
		&i.SourceType,
		&i.SourceID,
		&i.RemoteID,
		&i.ExternalID,
		&i.Etag,
		&i.LastSyncedVersion,
		&i.UpdatedAt,
	)
	return &i, err
}

const getProvisioningConnectionSecret = `-- name: GetProvisioningConnectionSecret :one
SELECT credential_secret FROM provisioning_connections WHERE tenant_id=$1 AND application_id=$2
`

type GetProvisioningConnectionSecretParams struct {
	TenantID      string
	ApplicationID string
}

func (q *Queries) GetProvisioningConnectionSecret(ctx context.Context, arg GetProvisioningConnectionSecretParams) (string, error) {
	row := q.db.QueryRow(ctx, getProvisioningConnectionSecret, arg.TenantID, arg.ApplicationID)
	var credential_secret string
	err := row.Scan(&credential_secret)
	return credential_secret, err
}

const insertProvisioningConnection = `-- name: InsertProvisioningConnection :one
INSERT INTO provisioning_connections (
  application_id, tenant_id, status, base_url, credential_id, auth_method, credential_secret,
  credential_oauth2_token_url, credential_oauth2_client_id, credential_oauth2_scope,
  credential_created_at, credential_rotated_at, capabilities, feature_flags, scope, group_push,
  attribute_mappings, matching, deprovision_policy, rate_limit_per_minute, max_attempts,
  notification_email, quarantine_after_consecutive_failures, health, consecutive_failure_count,
  last_full_sync_at, quarantined_at, quarantine_reason, created_at, updated_at
) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18,$19,$20,$21,$22,$23,$24,$25,$26,$27,$28,$29,$30)
ON CONFLICT (application_id) DO NOTHING
RETURNING application_id
`

type InsertProvisioningConnectionParams struct {
	ApplicationID                      string
	TenantID                           string
	Status                             string
	BaseUrl                            string
	CredentialID                       string
	AuthMethod                         string
	CredentialSecret                   string
	CredentialOauth2TokenUrl           string
	CredentialOauth2ClientID           string
	CredentialOauth2Scope              string
	CredentialCreatedAt                time.Time
	CredentialRotatedAt                pgtype.Timestamptz
	Capabilities                       []byte
	FeatureFlags                       []byte
	Scope                              string
	GroupPush                          []byte
	AttributeMappings                  []byte
	Matching                           []byte
	DeprovisionPolicy                  []byte
	RateLimitPerMinute                 int32
	MaxAttempts                        int32
	NotificationEmail                  pgtype.Text
	QuarantineAfterConsecutiveFailures int32
	Health                             string
	ConsecutiveFailureCount            int32
	LastFullSyncAt                     pgtype.Timestamptz
	QuarantinedAt                      pgtype.Timestamptz
	QuarantineReason                   pgtype.Text
	CreatedAt                          time.Time
	UpdatedAt                          time.Time
}

func (q *Queries) InsertProvisioningConnection(ctx context.Context, arg InsertProvisioningConnectionParams) (string, error) {
	row := q.db.QueryRow(ctx, insertProvisioningConnection,
		arg.ApplicationID,
		arg.TenantID,
		arg.Status,
		arg.BaseUrl,
		arg.CredentialID,
		arg.AuthMethod,
		arg.CredentialSecret,
		arg.CredentialOauth2TokenUrl,
		arg.CredentialOauth2ClientID,
		arg.CredentialOauth2Scope,
		arg.CredentialCreatedAt,
		arg.CredentialRotatedAt,
		arg.Capabilities,
		arg.FeatureFlags,
		arg.Scope,
		arg.GroupPush,
		arg.AttributeMappings,
		arg.Matching,
		arg.DeprovisionPolicy,
		arg.RateLimitPerMinute,
		arg.MaxAttempts,
		arg.NotificationEmail,
		arg.QuarantineAfterConsecutiveFailures,
		arg.Health,
		arg.ConsecutiveFailureCount,
		arg.LastFullSyncAt,
		arg.QuarantinedAt,
		arg.QuarantineReason,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var application_id string
	err := row.Scan(&application_id)
	return application_id, err
}

const insertProvisioningDelivery = `-- name: InsertProvisioningDelivery :one
INSERT INTO provisioning_deliveries (id, tenant_id, connection_id, source_type, source_id, source_version, operation, status, job_id, last_error, created_at, updated_at, completed_at)
VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13)
ON CONFLICT (tenant_id, connection_id, source_type, source_id, source_version) DO NOTHING
RETURNING id
`

type InsertProvisioningDeliveryParams struct {
	ID            string
	TenantID      string
	ConnectionID  string
	SourceType    string
	SourceID      string
	SourceVersion int64
	Operation     string
	Status        string
	JobID         pgtype.UUID
	LastError     pgtype.Text
	CreatedAt     time.Time
	UpdatedAt     time.Time
	CompletedAt   pgtype.Timestamptz
}

func (q *Queries) InsertProvisioningDelivery(ctx context.Context, arg InsertProvisioningDeliveryParams) (string, error) {
	row := q.db.QueryRow(ctx, insertProvisioningDelivery,
		arg.ID,
		arg.TenantID,
		arg.ConnectionID,
		arg.SourceType,
		arg.SourceID,
		arg.SourceVersion,
		arg.Operation,
		arg.Status,
		arg.JobID,
		arg.LastError,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.CompletedAt,
	)
	var id string
	err := row.Scan(&id)
	return id, err
}

const listProvisioningConnectionsByTenant = `-- name: ListProvisioningConnectionsByTenant :many
SELECT application_id, tenant_id, status, base_url, credential_id, auth_method,
credential_oauth2_token_url, credential_oauth2_client_id, credential_oauth2_scope,
credential_created_at, credential_rotated_at, capabilities, feature_flags, scope, group_push,
attribute_mappings, matching, deprovision_policy, rate_limit_per_minute, max_attempts,
notification_email, quarantine_after_consecutive_failures, health, consecutive_failure_count,
last_full_sync_at, quarantined_at, quarantine_reason, created_at, updated_at
FROM provisioning_connections WHERE tenant_id=$1 ORDER BY application_id
`

type ListProvisioningConnectionsByTenantRow struct {
	ApplicationID                      string
	TenantID                           string
	Status                             string
	BaseUrl                            string
	CredentialID                       string
	AuthMethod                         string
	CredentialOauth2TokenUrl           string
	CredentialOauth2ClientID           string
	CredentialOauth2Scope              string
	CredentialCreatedAt                time.Time
	CredentialRotatedAt                pgtype.Timestamptz
	Capabilities                       []byte
	FeatureFlags                       []byte
	Scope                              string
	GroupPush                          []byte
	AttributeMappings                  []byte
	Matching                           []byte
	DeprovisionPolicy                  []byte
	RateLimitPerMinute                 int32
	MaxAttempts                        int32
	NotificationEmail                  pgtype.Text
	QuarantineAfterConsecutiveFailures int32
	Health                             string
	ConsecutiveFailureCount            int32
	LastFullSyncAt                     pgtype.Timestamptz
	QuarantinedAt                      pgtype.Timestamptz
	QuarantineReason                   pgtype.Text
	CreatedAt                          time.Time
	UpdatedAt                          time.Time
}

func (q *Queries) ListProvisioningConnectionsByTenant(ctx context.Context, tenantID string) ([]*ListProvisioningConnectionsByTenantRow, error) {
	rows, err := q.db.Query(ctx, listProvisioningConnectionsByTenant, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*ListProvisioningConnectionsByTenantRow
	for rows.Next() {
		var i ListProvisioningConnectionsByTenantRow
		if err := rows.Scan(
			&i.ApplicationID,
			&i.TenantID,
			&i.Status,
			&i.BaseUrl,
			&i.CredentialID,
			&i.AuthMethod,
			&i.CredentialOauth2TokenUrl,
			&i.CredentialOauth2ClientID,
			&i.CredentialOauth2Scope,
			&i.CredentialCreatedAt,
			&i.CredentialRotatedAt,
			&i.Capabilities,
			&i.FeatureFlags,
			&i.Scope,
			&i.GroupPush,
			&i.AttributeMappings,
			&i.Matching,
			&i.DeprovisionPolicy,
			&i.RateLimitPerMinute,
			&i.MaxAttempts,
			&i.NotificationEmail,
			&i.QuarantineAfterConsecutiveFailures,
			&i.Health,
			&i.ConsecutiveFailureCount,
			&i.LastFullSyncAt,
			&i.QuarantinedAt,
			&i.QuarantineReason,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProvisioningDeliveriesByConnection = `-- name: ListProvisioningDeliveriesByConnection :many
SELECT id, tenant_id, connection_id, source_type, source_id, source_version, operation, status, job_id, last_error, created_at, updated_at, completed_at
FROM provisioning_deliveries WHERE tenant_id=$1 AND connection_id=$2 ORDER BY created_at DESC LIMIT $3
`

type ListProvisioningDeliveriesByConnectionParams struct {
	TenantID     string
	ConnectionID string
	Limit        int32
}

func (q *Queries) ListProvisioningDeliveriesByConnection(ctx context.Context, arg ListProvisioningDeliveriesByConnectionParams) ([]*ProvisioningDelivery, error) {
	rows, err := q.db.Query(ctx, listProvisioningDeliveriesByConnection, arg.TenantID, arg.ConnectionID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*ProvisioningDelivery
	for rows.Next() {
		var i ProvisioningDelivery
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.ConnectionID,
			&i.SourceType,
			&i.SourceID,
			&i.SourceVersion,
			&i.Operation,
			&i.Status,
			&i.JobID,
			&i.LastError,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProvisioningDeliveriesByConnectionAndStatus = `-- name: ListProvisioningDeliveriesByConnectionAndStatus :many
SELECT id, tenant_id, connection_id, source_type, source_id, source_version, operation, status, job_id, last_error, created_at, updated_at, completed_at
FROM provisioning_deliveries WHERE tenant_id=$1 AND connection_id=$2 AND status=$3 ORDER BY created_at DESC LIMIT $4
`

type ListProvisioningDeliveriesByConnectionAndStatusParams struct {
	TenantID     string
	ConnectionID string
	Status       string
	Limit        int32
}

func (q *Queries) ListProvisioningDeliveriesByConnectionAndStatus(ctx context.Context, arg ListProvisioningDeliveriesByConnectionAndStatusParams) ([]*ProvisioningDelivery, error) {
	rows, err := q.db.Query(ctx, listProvisioningDeliveriesByConnectionAndStatus,
		arg.TenantID,
		arg.ConnectionID,
		arg.Status,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*ProvisioningDelivery
	for rows.Next() {
		var i ProvisioningDelivery
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.ConnectionID,
			&i.SourceType,
			&i.SourceID,
			&i.SourceVersion,
			&i.Operation,
			&i.Status,
			&i.JobID,
			&i.LastError,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProvisioningDeliveriesByConnectionPage = `-- name: ListProvisioningDeliveriesByConnectionPage :many
SELECT id, tenant_id, connection_id, source_type, source_id, source_version, operation, status, job_id, last_error, created_at, updated_at, completed_at
FROM provisioning_deliveries
WHERE tenant_id=$1 AND connection_id=$2
  AND ($3::text = '' OR status=$3::text)
  AND ($4::text = '' OR source_type=$4::text)
ORDER BY created_at DESC, id DESC LIMIT $5
`

type ListProvisioningDeliveriesByConnectionPageParams struct {
	TenantID         string
	ConnectionID     string
	FilterStatus     string
	FilterSourceType string
	PageLimit        int32
}

// First page of ListProvisioningDeliveries keyset pagination (wi-159).
// Empty status/source_type arguments disable that filter.
func (q *Queries) ListProvisioningDeliveriesByConnectionPage(ctx context.Context, arg ListProvisioningDeliveriesByConnectionPageParams) ([]*ProvisioningDelivery, error) {
	rows, err := q.db.Query(ctx, listProvisioningDeliveriesByConnectionPage,
		arg.TenantID,
		arg.ConnectionID,
		arg.FilterStatus,
		arg.FilterSourceType,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*ProvisioningDelivery
	for rows.Next() {
		var i ProvisioningDelivery
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.ConnectionID,
			&i.SourceType,
			&i.SourceID,
			&i.SourceVersion,
			&i.Operation,
			&i.Status,
			&i.JobID,
			&i.LastError,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProvisioningDeliveriesByConnectionPageAfter = `-- name: ListProvisioningDeliveriesByConnectionPageAfter :many
SELECT id, tenant_id, connection_id, source_type, source_id, source_version, operation, status, job_id, last_error, created_at, updated_at, completed_at
FROM provisioning_deliveries WHERE tenant_id=$1 AND connection_id=$2
  AND ($3::text = '' OR status=$3::text)
  AND ($4::text = '' OR source_type=$4::text)
  AND (created_at, id) < ($5::timestamptz, $6::uuid)
ORDER BY created_at DESC, id DESC LIMIT $7
`

type ListProvisioningDeliveriesByConnectionPageAfterParams struct {
	TenantID         string
	ConnectionID     string
	FilterStatus     string
	FilterSourceType string
	AfterCreatedAt   time.Time
	AfterID          string
	PageLimit        int32
}

// Continuation page: resumes strictly after the (created_at, id) keyset of
// the last row the caller saw.
func (q *Queries) ListProvisioningDeliveriesByConnectionPageAfter(ctx context.Context, arg ListProvisioningDeliveriesByConnectionPageAfterParams) ([]*ProvisioningDelivery, error) {
	rows, err := q.db.Query(ctx, listProvisioningDeliveriesByConnectionPageAfter,
		arg.TenantID,
		arg.ConnectionID,
		arg.FilterStatus,
		arg.FilterSourceType,
		arg.AfterCreatedAt,
		arg.AfterID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*ProvisioningDelivery
	for rows.Next() {
		var i ProvisioningDelivery
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.ConnectionID,
			&i.SourceType,
			&i.SourceID,
			&i.SourceVersion,
			&i.Operation,
			&i.Status,
			&i.JobID,
			&i.LastError,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProvisioningDeliveriesByConnectionPageBefore = `-- name: ListProvisioningDeliveriesByConnectionPageBefore :many
SELECT id, tenant_id, connection_id, source_type, source_id, source_version, operation, status, job_id, last_error, created_at, updated_at, completed_at
FROM provisioning_deliveries WHERE tenant_id=$1 AND connection_id=$2
  AND ($3::text = '' OR status=$3::text)
  AND ($4::text = '' OR source_type=$4::text)
  AND (created_at, id) > ($5::timestamptz, $6::uuid)
ORDER BY created_at ASC, id ASC LIMIT $7
`

type ListProvisioningDeliveriesByConnectionPageBeforeParams struct {
	TenantID         string
	ConnectionID     string
	FilterStatus     string
	FilterSourceType string
	BeforeCreatedAt  time.Time
	BeforeID         string
	PageLimit        int32
}

func (q *Queries) ListProvisioningDeliveriesByConnectionPageBefore(ctx context.Context, arg ListProvisioningDeliveriesByConnectionPageBeforeParams) ([]*ProvisioningDelivery, error) {
	rows, err := q.db.Query(ctx, listProvisioningDeliveriesByConnectionPageBefore,
		arg.TenantID,
		arg.ConnectionID,
		arg.FilterStatus,
		arg.FilterSourceType,
		arg.BeforeCreatedAt,
		arg.BeforeID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*ProvisioningDelivery
	for rows.Next() {
		var i ProvisioningDelivery
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.ConnectionID,
			&i.SourceType,
			&i.SourceID,
			&i.SourceVersion,
			&i.Operation,
			&i.Status,
			&i.JobID,
			&i.LastError,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnenqueuedProvisioningDeliveries = `-- name: ListUnenqueuedProvisioningDeliveries :many
SELECT id, tenant_id, connection_id, source_type, source_id, source_version, operation, status, job_id, last_error, created_at, updated_at, completed_at
FROM provisioning_deliveries WHERE status='pending' AND job_id IS NULL ORDER BY created_at LIMIT $1
`

func (q *Queries) ListUnenqueuedProvisioningDeliveries(ctx context.Context, limit int32) ([]*ProvisioningDelivery, error) {
	rows, err := q.db.Query(ctx, listUnenqueuedProvisioningDeliveries, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*ProvisioningDelivery
	for rows.Next() {
		var i ProvisioningDelivery
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.ConnectionID,
			&i.SourceType,
			&i.SourceID,
			&i.SourceVersion,
			&i.Operation,
			&i.Status,
			&i.JobID,
			&i.LastError,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const retryDeadLetterProvisioningDelivery = `-- name: RetryDeadLetterProvisioningDelivery :execrows
UPDATE provisioning_deliveries SET status='pending', job_id=NULL, last_error=NULL, updated_at=now()
WHERE tenant_id=$1 AND id=$2 AND status='dead_letter'
`

type RetryDeadLetterProvisioningDeliveryParams struct {
	TenantID string
	ID       string
}

func (q *Queries) RetryDeadLetterProvisioningDelivery(ctx context.Context, arg RetryDeadLetterProvisioningDeliveryParams) (int64, error) {
	result, err := q.db.Exec(ctx, retryDeadLetterProvisioningDelivery, arg.TenantID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateProvisioningConnection = `-- name: UpdateProvisioningConnection :exec
UPDATE provisioning_connections SET
  status=$3, base_url=$4, capabilities=$5, feature_flags=$6, scope=$7, group_push=$8,
  attribute_mappings=$9, matching=$10, deprovision_policy=$11, rate_limit_per_minute=$12,
  max_attempts=$13, notification_email=$14, quarantine_after_consecutive_failures=$15, health=$16,
  consecutive_failure_count=$17, last_full_sync_at=$18, quarantined_at=$19, quarantine_reason=$20,
  updated_at=$21
WHERE tenant_id=$1 AND application_id=$2
`

type UpdateProvisioningConnectionParams struct {
	TenantID                           string
	ApplicationID                      string
	Status                             string
	BaseUrl                            string
	Capabilities                       []byte
	FeatureFlags                       []byte
	Scope                              string
	GroupPush                          []byte
	AttributeMappings                  []byte
	Matching                           []byte
	DeprovisionPolicy                  []byte
	RateLimitPerMinute                 int32
	MaxAttempts                        int32
	NotificationEmail                  pgtype.Text
	QuarantineAfterConsecutiveFailures int32
	Health                             string
	ConsecutiveFailureCount            int32
	LastFullSyncAt                     pgtype.Timestamptz
	QuarantinedAt                      pgtype.Timestamptz
	QuarantineReason                   pgtype.Text
	UpdatedAt                          time.Time
}

func (q *Queries) UpdateProvisioningConnection(ctx context.Context, arg UpdateProvisioningConnectionParams) error {
	_, err := q.db.Exec(ctx, updateProvisioningConnection,
		arg.TenantID,
		arg.ApplicationID,
		arg.Status,
		arg.BaseUrl,
		arg.Capabilities,
		arg.FeatureFlags,
		arg.Scope,
		arg.GroupPush,
		arg.AttributeMappings,
		arg.Matching,
		arg.DeprovisionPolicy,
		arg.RateLimitPerMinute,
		arg.MaxAttempts,
		arg.NotificationEmail,
		arg.QuarantineAfterConsecutiveFailures,
		arg.Health,
		arg.ConsecutiveFailureCount,
		arg.LastFullSyncAt,
		arg.QuarantinedAt,
		arg.QuarantineReason,
		arg.UpdatedAt,
	)
	return err
}

const updateProvisioningConnectionWithSecret = `-- name: UpdateProvisioningConnectionWithSecret :exec
UPDATE provisioning_connections SET
  status=$3, base_url=$4, credential_id=$5, auth_method=$6, credential_secret=$7,
  credential_oauth2_token_url=$8, credential_oauth2_client_id=$9, credential_oauth2_scope=$10,
  credential_rotated_at=$11, capabilities=$12, feature_flags=$13, scope=$14, group_push=$15,
  attribute_mappings=$16, matching=$17, deprovision_policy=$18, rate_limit_per_minute=$19,
  max_attempts=$20, notification_email=$21, quarantine_after_consecutive_failures=$22, health=$23,
  consecutive_failure_count=$24, last_full_sync_at=$25, quarantined_at=$26, quarantine_reason=$27,
  updated_at=$28
WHERE tenant_id=$1 AND application_id=$2
`

type UpdateProvisioningConnectionWithSecretParams struct {
	TenantID                           string
	ApplicationID                      string
	Status                             string
	BaseUrl                            string
	CredentialID                       string
	AuthMethod                         string
	CredentialSecret                   string
	CredentialOauth2TokenUrl           string
	CredentialOauth2ClientID           string
	CredentialOauth2Scope              string
	CredentialRotatedAt                pgtype.Timestamptz
	Capabilities                       []byte
	FeatureFlags                       []byte
	Scope                              string
	GroupPush                          []byte
	AttributeMappings                  []byte
	Matching                           []byte
	DeprovisionPolicy                  []byte
	RateLimitPerMinute                 int32
	MaxAttempts                        int32
	NotificationEmail                  pgtype.Text
	QuarantineAfterConsecutiveFailures int32
	Health                             string
	ConsecutiveFailureCount            int32
	LastFullSyncAt                     pgtype.Timestamptz
	QuarantinedAt                      pgtype.Timestamptz
	QuarantineReason                   pgtype.Text
	UpdatedAt                          time.Time
}

func (q *Queries) UpdateProvisioningConnectionWithSecret(ctx context.Context, arg UpdateProvisioningConnectionWithSecretParams) error {
	_, err := q.db.Exec(ctx, updateProvisioningConnectionWithSecret,
		arg.TenantID,
		arg.ApplicationID,
		arg.Status,
		arg.BaseUrl,
		arg.CredentialID,
		arg.AuthMethod,
		arg.CredentialSecret,
		arg.CredentialOauth2TokenUrl,
		arg.CredentialOauth2ClientID,
		arg.CredentialOauth2Scope,
		arg.CredentialRotatedAt,
		arg.Capabilities,
		arg.FeatureFlags,
		arg.Scope,
		arg.GroupPush,
		arg.AttributeMappings,
		arg.Matching,
		arg.DeprovisionPolicy,
		arg.RateLimitPerMinute,
		arg.MaxAttempts,
		arg.NotificationEmail,
		arg.QuarantineAfterConsecutiveFailures,
		arg.Health,
		arg.ConsecutiveFailureCount,
		arg.LastFullSyncAt,
		arg.QuarantinedAt,
		arg.QuarantineReason,
		arg.UpdatedAt,
	)
	return err
}

const updateProvisioningDeliveryStatus = `-- name: UpdateProvisioningDeliveryStatus :exec
UPDATE provisioning_deliveries SET status=$3, last_error=$4, updated_at=now(),
  completed_at = CASE WHEN $3 IN ('succeeded','dead_letter') THEN now() ELSE completed_at END
WHERE tenant_id=$1 AND id=$2
`

type UpdateProvisioningDeliveryStatusParams struct {
	TenantID  string
	ID        string
	Status    string
	LastError pgtype.Text
}

func (q *Queries) UpdateProvisioningDeliveryStatus(ctx context.Context, arg UpdateProvisioningDeliveryStatusParams) error {
	_, err := q.db.Exec(ctx, updateProvisioningDeliveryStatus,
		arg.TenantID,
		arg.ID,
		arg.Status,
		arg.LastError,
	)
	return err
}

const upsertRemoteResourceLink = `-- name: UpsertRemoteResourceLink :exec
INSERT INTO provisioning_remote_links (connection_id, tenant_id, source_type, source_id, remote_id, external_id, etag, last_synced_version, updated_at)
VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9)
ON CONFLICT (connection_id, source_type, source_id) DO UPDATE SET
  remote_id=EXCLUDED.remote_id, external_id=EXCLUDED.external_id, etag=EXCLUDED.etag,
  last_synced_version=EXCLUDED.last_synced_version, updated_at=EXCLUDED.updated_at
`

type UpsertRemoteResourceLinkParams struct {
	ConnectionID      string
	TenantID          string
	SourceType        string
	SourceID          string
	RemoteID          string
	ExternalID        string
	Etag              pgtype.Text
	LastSyncedVersion int64
	UpdatedAt         time.Time
}

func (q *Queries) UpsertRemoteResourceLink(ctx context.Context, arg UpsertRemoteResourceLinkParams) error {
	_, err := q.db.Exec(ctx, upsertRemoteResourceLink,
		arg.ConnectionID,
		arg.TenantID,
		arg.SourceType,
		arg.SourceID,
		arg.RemoteID,
		arg.ExternalID,
		arg.Etag,
		arg.LastSyncedVersion,
		arg.UpdatedAt,
	)
	return err
}
