// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db_postgres

import (
	"context"
)

type Querier interface {
	AttachProvisioningDeliveryJob(ctx context.Context, arg AttachProvisioningDeliveryJobParams) (int64, error)
	DeleteProvisioningConnection(ctx context.Context, arg DeleteProvisioningConnectionParams) error
	FindProvisioningConnection(ctx context.Context, arg FindProvisioningConnectionParams) (*FindProvisioningConnectionRow, error)
	FindProvisioningDelivery(ctx context.Context, arg FindProvisioningDeliveryParams) (*ProvisioningDelivery, error)
	FindRemoteResourceLink(ctx context.Context, arg FindRemoteResourceLinkParams) (*ProvisioningRemoteLink, error)
	GetProvisioningConnectionSecret(ctx context.Context, arg GetProvisioningConnectionSecretParams) (string, error)
	InsertProvisioningConnection(ctx context.Context, arg InsertProvisioningConnectionParams) (string, error)
	InsertProvisioningDelivery(ctx context.Context, arg InsertProvisioningDeliveryParams) (string, error)
	ListProvisioningConnectionsByTenant(ctx context.Context, tenantID string) ([]*ListProvisioningConnectionsByTenantRow, error)
	ListProvisioningDeliveriesByConnection(ctx context.Context, arg ListProvisioningDeliveriesByConnectionParams) ([]*ProvisioningDelivery, error)
	ListProvisioningDeliveriesByConnectionAndStatus(ctx context.Context, arg ListProvisioningDeliveriesByConnectionAndStatusParams) ([]*ProvisioningDelivery, error)
	// First page of ListProvisioningDeliveries keyset pagination (wi-159).
	// Empty status/source_type arguments disable that filter.
	ListProvisioningDeliveriesByConnectionPage(ctx context.Context, arg ListProvisioningDeliveriesByConnectionPageParams) ([]*ProvisioningDelivery, error)
	// Continuation page: resumes strictly after the (created_at, id) keyset of
	// the last row the caller saw.
	ListProvisioningDeliveriesByConnectionPageAfter(ctx context.Context, arg ListProvisioningDeliveriesByConnectionPageAfterParams) ([]*ProvisioningDelivery, error)
	ListProvisioningDeliveriesByConnectionPageBefore(ctx context.Context, arg ListProvisioningDeliveriesByConnectionPageBeforeParams) ([]*ProvisioningDelivery, error)
	ListUnenqueuedProvisioningDeliveries(ctx context.Context, limit int32) ([]*ProvisioningDelivery, error)
	RetryDeadLetterProvisioningDelivery(ctx context.Context, arg RetryDeadLetterProvisioningDeliveryParams) (int64, error)
	UpdateProvisioningConnection(ctx context.Context, arg UpdateProvisioningConnectionParams) error
	UpdateProvisioningConnectionWithSecret(ctx context.Context, arg UpdateProvisioningConnectionWithSecretParams) error
	UpdateProvisioningDeliveryStatus(ctx context.Context, arg UpdateProvisioningDeliveryStatusParams) error
	UpsertRemoteResourceLink(ctx context.Context, arg UpsertRemoteResourceLinkParams) error
}

var _ Querier = (*Queries)(nil)
