// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db_postgres

import (
	"context"
)

type Querier interface {
	AttachProvisioningTaskJob(ctx context.Context, arg AttachProvisioningTaskJobParams) (int64, error)
	CancelProvisioningScheduledDeprovisions(ctx context.Context, arg CancelProvisioningScheduledDeprovisionsParams) (int64, error)
	DeleteProvisioningConnection(ctx context.Context, arg DeleteProvisioningConnectionParams) error
	FindProvisioningConnection(ctx context.Context, arg FindProvisioningConnectionParams) (*FindProvisioningConnectionRow, error)
	FindProvisioningTask(ctx context.Context, arg FindProvisioningTaskParams) (*ProvisioningTask, error)
	FindRemoteResourceLink(ctx context.Context, arg FindRemoteResourceLinkParams) (*ProvisioningRemoteLink, error)
	GetProvisioningConnectionSecret(ctx context.Context, arg GetProvisioningConnectionSecretParams) (string, error)
	InsertProvisioningConnection(ctx context.Context, arg InsertProvisioningConnectionParams) (string, error)
	InsertProvisioningScheduledDeprovision(ctx context.Context, arg InsertProvisioningScheduledDeprovisionParams) (int64, error)
	InsertProvisioningTask(ctx context.Context, arg InsertProvisioningTaskParams) (string, error)
	ListDueProvisioningScheduledDeprovisions(ctx context.Context, arg ListDueProvisioningScheduledDeprovisionsParams) ([]*ProvisioningScheduledDeprovision, error)
	ListProvisioningConnectionsByTenant(ctx context.Context, tenantID string) ([]*ListProvisioningConnectionsByTenantRow, error)
	ListProvisioningTasksByConnection(ctx context.Context, arg ListProvisioningTasksByConnectionParams) ([]*ProvisioningTask, error)
	ListProvisioningTasksByConnectionAndStatus(ctx context.Context, arg ListProvisioningTasksByConnectionAndStatusParams) ([]*ProvisioningTask, error)
	// First page of ListProvisioningTasks keyset pagination (wi-159).
	// Empty status/source_type arguments disable that filter.
	ListProvisioningTasksByConnectionPage(ctx context.Context, arg ListProvisioningTasksByConnectionPageParams) ([]*ProvisioningTask, error)
	// Continuation page: resumes strictly after the (created_at, id) keyset of
	// the last row the caller saw.
	ListProvisioningTasksByConnectionPageAfter(ctx context.Context, arg ListProvisioningTasksByConnectionPageAfterParams) ([]*ProvisioningTask, error)
	ListProvisioningTasksByConnectionPageBefore(ctx context.Context, arg ListProvisioningTasksByConnectionPageBeforeParams) ([]*ProvisioningTask, error)
	ListUnenqueuedProvisioningTasks(ctx context.Context, limit int32) ([]*ProvisioningTask, error)
	// 予約の遷移とプロビジョニングタスクの挿入を一文で行い、取消と競合したときにプロビジョニングタスクだけが残らないようにする。
	// 結果は遷移した予約の件数（0 または 1）である。
	MaterializeProvisioningScheduledDeprovision(ctx context.Context, arg MaterializeProvisioningScheduledDeprovisionParams) (int64, error)
	RetryDeadLetterProvisioningTask(ctx context.Context, arg RetryDeadLetterProvisioningTaskParams) (int64, error)
	UpdateProvisioningConnection(ctx context.Context, arg UpdateProvisioningConnectionParams) error
	UpdateProvisioningConnectionWithSecret(ctx context.Context, arg UpdateProvisioningConnectionWithSecretParams) error
	UpdateProvisioningTaskStatus(ctx context.Context, arg UpdateProvisioningTaskStatusParams) error
	UpsertRemoteResourceLink(ctx context.Context, arg UpsertRemoteResourceLinkParams) error
}

var _ Querier = (*Queries)(nil)
