// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: password_reset_tokens.sql

package db_postgres

import (
	"context"
	"time"
)

const consumePasswordResetToken = `-- name: ConsumePasswordResetToken :one
DELETE FROM password_reset_tokens
WHERE token_hash=$1
RETURNING user_id,token_hash,created_at,expires_at
`

type ConsumePasswordResetTokenRow struct {
	UserID    string
	TokenHash string
	CreatedAt time.Time
	ExpiresAt time.Time
}

func (q *Queries) ConsumePasswordResetToken(ctx context.Context, tokenHash string) (*ConsumePasswordResetTokenRow, error) {
	row := q.db.QueryRow(ctx, consumePasswordResetToken, tokenHash)
	var i ConsumePasswordResetTokenRow
	err := row.Scan(
		&i.UserID,
		&i.TokenHash,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return &i, err
}

const deletePasswordResetTokensByUser = `-- name: DeletePasswordResetTokensByUser :exec
DELETE FROM password_reset_tokens WHERE user_id=$1
`

func (q *Queries) DeletePasswordResetTokensByUser(ctx context.Context, userID string) error {
	_, err := q.db.Exec(ctx, deletePasswordResetTokensByUser, userID)
	return err
}

const insertPasswordResetToken = `-- name: InsertPasswordResetToken :exec
INSERT INTO password_reset_tokens (token_hash,user_id,created_at,expires_at) VALUES ($1,$2,$3,$4)
`

type InsertPasswordResetTokenParams struct {
	TokenHash string
	UserID    string
	CreatedAt time.Time
	ExpiresAt time.Time
}

func (q *Queries) InsertPasswordResetToken(ctx context.Context, arg InsertPasswordResetTokenParams) error {
	_, err := q.db.Exec(ctx, insertPasswordResetToken,
		arg.TokenHash,
		arg.UserID,
		arg.CreatedAt,
		arg.ExpiresAt,
	)
	return err
}
