// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db_postgres

import (
	"context"
)

type Querier interface {
	DeletePasswordHistoryForSub(ctx context.Context, userID string) error
	DeletePasswordResetTokensByUser(ctx context.Context, userID string) error
	FindUnusedPasswordResetToken(ctx context.Context, tokenHash string) (*FindUnusedPasswordResetTokenRow, error)
	InsertPasswordHistory(ctx context.Context, arg InsertPasswordHistoryParams) error
	InsertPasswordResetToken(ctx context.Context, arg InsertPasswordResetTokenParams) error
	MarkPasswordResetTokenUsed(ctx context.Context, arg MarkPasswordResetTokenUsedParams) (*MarkPasswordResetTokenUsedRow, error)
	RecentPasswordHistory(ctx context.Context, arg RecentPasswordHistoryParams) ([]*RecentPasswordHistoryRow, error)
}

var _ Querier = (*Queries)(nil)
