// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: lifecycle_workflows.sql

package db_postgres

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const cancelQueuedLifecycleWorkflowRuns = `-- name: CancelQueuedLifecycleWorkflowRuns :many
UPDATE lifecycle_workflow_runs SET status='canceled',updated_at=now() WHERE tenant_id=$1 AND workflow_id=$2 AND status='queued' RETURNING id,target_user_id
`

type CancelQueuedLifecycleWorkflowRunsParams struct {
	TenantID   string
	WorkflowID string
}

type CancelQueuedLifecycleWorkflowRunsRow struct {
	ID           string
	TargetUserID string
}

func (q *Queries) CancelQueuedLifecycleWorkflowRuns(ctx context.Context, arg CancelQueuedLifecycleWorkflowRunsParams) ([]*CancelQueuedLifecycleWorkflowRunsRow, error) {
	rows, err := q.db.Query(ctx, cancelQueuedLifecycleWorkflowRuns, arg.TenantID, arg.WorkflowID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*CancelQueuedLifecycleWorkflowRunsRow
	for rows.Next() {
		var i CancelQueuedLifecycleWorkflowRunsRow
		if err := rows.Scan(&i.ID, &i.TargetUserID); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findLifecycleWorkflow = `-- name: FindLifecycleWorkflow :one
SELECT id,tenant_id,name,description,status,current_revision,enabled_revision,created_at,updated_at FROM lifecycle_workflows WHERE tenant_id=$1 AND id=$2
`

type FindLifecycleWorkflowParams struct {
	TenantID string
	ID       string
}

func (q *Queries) FindLifecycleWorkflow(ctx context.Context, arg FindLifecycleWorkflowParams) (*LifecycleWorkflow, error) {
	row := q.db.QueryRow(ctx, findLifecycleWorkflow, arg.TenantID, arg.ID)
	var i LifecycleWorkflow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Description,
		&i.Status,
		&i.CurrentRevision,
		&i.EnabledRevision,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const findLifecycleWorkflowRevision = `-- name: FindLifecycleWorkflowRevision :one
SELECT workflow_id,tenant_id,revision,trigger,actions,created_at FROM lifecycle_workflow_revisions WHERE tenant_id=$1 AND workflow_id=$2 AND revision=$3
`

type FindLifecycleWorkflowRevisionParams struct {
	TenantID   string
	WorkflowID string
	Revision   int64
}

func (q *Queries) FindLifecycleWorkflowRevision(ctx context.Context, arg FindLifecycleWorkflowRevisionParams) (*LifecycleWorkflowRevision, error) {
	row := q.db.QueryRow(ctx, findLifecycleWorkflowRevision, arg.TenantID, arg.WorkflowID, arg.Revision)
	var i LifecycleWorkflowRevision
	err := row.Scan(
		&i.WorkflowID,
		&i.TenantID,
		&i.Revision,
		&i.Trigger,
		&i.Actions,
		&i.CreatedAt,
	)
	return &i, err
}

const listLifecycleWorkflowRuns = `-- name: ListLifecycleWorkflowRuns :many
SELECT id,tenant_id,workflow_id,revision,source_occurrence_id,target_user_id,trigger_kind,changed_fields,actions,status,job_id,triggered_at FROM lifecycle_workflow_runs WHERE tenant_id=$1 AND workflow_id=$2 ORDER BY triggered_at DESC LIMIT $3
`

type ListLifecycleWorkflowRunsParams struct {
	TenantID   string
	WorkflowID string
	Limit      int32
}

type ListLifecycleWorkflowRunsRow struct {
	ID                 string
	TenantID           string
	WorkflowID         string
	Revision           int64
	SourceOccurrenceID string
	TargetUserID       string
	TriggerKind        string
	ChangedFields      []byte
	Actions            []byte
	Status             string
	JobID              pgtype.UUID
	TriggeredAt        time.Time
}

func (q *Queries) ListLifecycleWorkflowRuns(ctx context.Context, arg ListLifecycleWorkflowRunsParams) ([]*ListLifecycleWorkflowRunsRow, error) {
	rows, err := q.db.Query(ctx, listLifecycleWorkflowRuns, arg.TenantID, arg.WorkflowID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*ListLifecycleWorkflowRunsRow
	for rows.Next() {
		var i ListLifecycleWorkflowRunsRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.WorkflowID,
			&i.Revision,
			&i.SourceOccurrenceID,
			&i.TargetUserID,
			&i.TriggerKind,
			&i.ChangedFields,
			&i.Actions,
			&i.Status,
			&i.JobID,
			&i.TriggeredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLifecycleWorkflowsByTenant = `-- name: ListLifecycleWorkflowsByTenant :many
SELECT id,tenant_id,name,description,status,current_revision,enabled_revision,created_at,updated_at FROM lifecycle_workflows WHERE tenant_id=$1 ORDER BY name
`

func (q *Queries) ListLifecycleWorkflowsByTenant(ctx context.Context, tenantID string) ([]*LifecycleWorkflow, error) {
	rows, err := q.db.Query(ctx, listLifecycleWorkflowsByTenant, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*LifecycleWorkflow
	for rows.Next() {
		var i LifecycleWorkflow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.Description,
			&i.Status,
			&i.CurrentRevision,
			&i.EnabledRevision,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resetFailedLifecycleWorkflowSteps = `-- name: ResetFailedLifecycleWorkflowSteps :exec
UPDATE lifecycle_workflow_steps SET outcome='pending',error_code=NULL,completed_at=NULL WHERE run_id=$1 AND outcome='failed'
`

func (q *Queries) ResetFailedLifecycleWorkflowSteps(ctx context.Context, runID string) error {
	_, err := q.db.Exec(ctx, resetFailedLifecycleWorkflowSteps, runID)
	return err
}

const retryLifecycleWorkflowRun = `-- name: RetryLifecycleWorkflowRun :execrows
UPDATE lifecycle_workflow_runs SET status='queued',job_id=NULL,updated_at=now() WHERE tenant_id=$1 AND id=$2 AND status IN ('failed','partially_failed')
`

type RetryLifecycleWorkflowRunParams struct {
	TenantID string
	ID       string
}

func (q *Queries) RetryLifecycleWorkflowRun(ctx context.Context, arg RetryLifecycleWorkflowRunParams) (int64, error) {
	result, err := q.db.Exec(ctx, retryLifecycleWorkflowRun, arg.TenantID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const saveLifecycleWorkflow = `-- name: SaveLifecycleWorkflow :exec
INSERT INTO lifecycle_workflows (id,tenant_id,name,description,status,current_revision,enabled_revision,created_at,updated_at) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9)
ON CONFLICT (id) DO UPDATE SET name=EXCLUDED.name,description=EXCLUDED.description,status=EXCLUDED.status,current_revision=EXCLUDED.current_revision,enabled_revision=EXCLUDED.enabled_revision,updated_at=EXCLUDED.updated_at WHERE lifecycle_workflows.tenant_id=EXCLUDED.tenant_id
`

type SaveLifecycleWorkflowParams struct {
	ID              string
	TenantID        string
	Name            string
	Description     pgtype.Text
	Status          string
	CurrentRevision int64
	EnabledRevision pgtype.Int8
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

func (q *Queries) SaveLifecycleWorkflow(ctx context.Context, arg SaveLifecycleWorkflowParams) error {
	_, err := q.db.Exec(ctx, saveLifecycleWorkflow,
		arg.ID,
		arg.TenantID,
		arg.Name,
		arg.Description,
		arg.Status,
		arg.CurrentRevision,
		arg.EnabledRevision,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const saveLifecycleWorkflowRevision = `-- name: SaveLifecycleWorkflowRevision :exec
INSERT INTO lifecycle_workflow_revisions (workflow_id,tenant_id,revision,trigger,actions,created_at) VALUES ($1,$2,$3,$4,$5,$6) ON CONFLICT (workflow_id,revision) DO NOTHING
`

type SaveLifecycleWorkflowRevisionParams struct {
	WorkflowID string
	TenantID   string
	Revision   int64
	Trigger    []byte
	Actions    []byte
	CreatedAt  time.Time
}

func (q *Queries) SaveLifecycleWorkflowRevision(ctx context.Context, arg SaveLifecycleWorkflowRevisionParams) error {
	_, err := q.db.Exec(ctx, saveLifecycleWorkflowRevision,
		arg.WorkflowID,
		arg.TenantID,
		arg.Revision,
		arg.Trigger,
		arg.Actions,
		arg.CreatedAt,
	)
	return err
}
