// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db_postgres

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type LifecycleWorkflow struct {
	ID              string
	TenantID        string
	Name            string
	Description     pgtype.Text
	Status          string
	CurrentRevision int64
	EnabledRevision pgtype.Int8
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

type LifecycleWorkflowRevision struct {
	WorkflowID string
	TenantID   string
	Revision   int64
	Trigger    []byte
	Actions    []byte
	CreatedAt  time.Time
}
