// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: csv_artifacts.sql

package db_postgres

import (
	"context"
	"time"
)

const deleteCSVArtifactsCreatedBefore = `-- name: DeleteCSVArtifactsCreatedBefore :execrows
DELETE FROM csv_artifacts WHERE created_at < $1
`

// 保持期限の削除。テナントをまたいで消し、分割片は外部キーの連鎖で消える。
func (q *Queries) DeleteCSVArtifactsCreatedBefore(ctx context.Context, createdAt time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, deleteCSVArtifactsCreatedBefore, createdAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const findCSVArtifact = `-- name: FindCSVArtifact :one
SELECT sha256, byte_size FROM csv_artifacts WHERE tenant_id = $1 AND id = $2
`

type FindCSVArtifactParams struct {
	TenantID string
	ID       string
}

type FindCSVArtifactRow struct {
	Sha256   string
	ByteSize int64
}

func (q *Queries) FindCSVArtifact(ctx context.Context, arg FindCSVArtifactParams) (*FindCSVArtifactRow, error) {
	row := q.db.QueryRow(ctx, findCSVArtifact, arg.TenantID, arg.ID)
	var i FindCSVArtifactRow
	err := row.Scan(&i.Sha256, &i.ByteSize)
	return &i, err
}

const findCSVArtifactPage = `-- name: FindCSVArtifactPage :one
SELECT a.sha256, a.byte_size, c.payload FROM csv_artifacts a
JOIN csv_artifact_chunks c ON c.artifact_id = a.id
WHERE a.tenant_id = $1 AND a.id = $2 AND c.chunk_number = $3
`

type FindCSVArtifactPageParams struct {
	TenantID    string
	ID          string
	ChunkNumber int32
}

type FindCSVArtifactPageRow struct {
	Sha256   string
	ByteSize int64
	Payload  []byte
}

func (q *Queries) FindCSVArtifactPage(ctx context.Context, arg FindCSVArtifactPageParams) (*FindCSVArtifactPageRow, error) {
	row := q.db.QueryRow(ctx, findCSVArtifactPage, arg.TenantID, arg.ID, arg.ChunkNumber)
	var i FindCSVArtifactPageRow
	err := row.Scan(&i.Sha256, &i.ByteSize, &i.Payload)
	return &i, err
}

const insertCSVArtifact = `-- name: InsertCSVArtifact :exec
INSERT INTO csv_artifacts (id, tenant_id, sha256, byte_size) VALUES ($1, $2, $3, $4)
`

type InsertCSVArtifactParams struct {
	ID       string
	TenantID string
	Sha256   string
	ByteSize int64
}

func (q *Queries) InsertCSVArtifact(ctx context.Context, arg InsertCSVArtifactParams) error {
	_, err := q.db.Exec(ctx, insertCSVArtifact,
		arg.ID,
		arg.TenantID,
		arg.Sha256,
		arg.ByteSize,
	)
	return err
}

const insertCSVArtifactChunk = `-- name: InsertCSVArtifactChunk :exec
INSERT INTO csv_artifact_chunks (artifact_id, chunk_number, payload) VALUES ($1, $2, $3)
`

type InsertCSVArtifactChunkParams struct {
	ArtifactID  string
	ChunkNumber int32
	Payload     []byte
}

func (q *Queries) InsertCSVArtifactChunk(ctx context.Context, arg InsertCSVArtifactChunkParams) error {
	_, err := q.db.Exec(ctx, insertCSVArtifactChunk, arg.ArtifactID, arg.ChunkNumber, arg.Payload)
	return err
}

const listCSVArtifactChunkPayloadsFrom = `-- name: ListCSVArtifactChunkPayloadsFrom :many
SELECT payload FROM csv_artifact_chunks
WHERE artifact_id = $1 AND chunk_number >= $2
ORDER BY chunk_number
LIMIT $3
`

type ListCSVArtifactChunkPayloadsFromParams struct {
	ArtifactID      string
	FromChunkNumber int32
	PageLimit       int32
}

func (q *Queries) ListCSVArtifactChunkPayloadsFrom(ctx context.Context, arg ListCSVArtifactChunkPayloadsFromParams) ([][]byte, error) {
	rows, err := q.db.Query(ctx, listCSVArtifactChunkPayloadsFrom, arg.ArtifactID, arg.FromChunkNumber, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items [][]byte
	for rows.Next() {
		var payload []byte
		if err := rows.Scan(&payload); err != nil {
			return nil, err
		}
		items = append(items, payload)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCSVArtifactDigest = `-- name: UpdateCSVArtifactDigest :exec
UPDATE csv_artifacts SET sha256 = $2, byte_size = $3 WHERE id = $1
`

type UpdateCSVArtifactDigestParams struct {
	ID       string
	Sha256   string
	ByteSize int64
}

func (q *Queries) UpdateCSVArtifactDigest(ctx context.Context, arg UpdateCSVArtifactDigestParams) error {
	_, err := q.db.Exec(ctx, updateCSVArtifactDigest, arg.ID, arg.Sha256, arg.ByteSize)
	return err
}
