apiVersion: v1
kind: ConfigMap
metadata:
  name: idmagic-runtime
  labels:
    app.kubernetes.io/name: idmagic
    app.kubernetes.io/part-of: idmagic
data:
  ADDR: :8080
  PERSISTENCE: postgres
  OBSERVABILITY: otel
  OTEL_EXPORTER_OTLP_PROTOCOL: http/protobuf
  BACKEND_ADDRESS: http://idmagic-api:8080
