// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"context"
	"time"
)

type Querier interface {
	DeleteAuthEventBucketsOlderThan(ctx context.Context, windowStart time.Time) (int64, error)
	ListAuthEventBuckets(ctx context.Context, arg ListAuthEventBucketsParams) ([]*ListAuthEventBucketsRow, error)
	RecordAuthEventBucket(ctx context.Context, arg RecordAuthEventBucketParams) (*RecordAuthEventBucketRow, error)
}

var _ Querier = (*Queries)(nil)
