import { describe, expect, it } from 'bun:test'
import { isRawSqlTarget, rawSqlCalls } from './raw-sql.ts'

describe('isRawSqlTarget', () => {
  it('targets hand-written Go under backend', () => {
    expect(isRawSqlTarget('backend/jobs/db_postgres/postgres.go')).toBe(true)
  })

  it('skips tests and code outside backend', () => {
    expect(isRawSqlTarget('backend/jobs/db_postgres/postgres_test.go')).toBe(false)
    expect(isRawSqlTarget('tools/check/src/raw-sql.ts')).toBe(false)
  })
})

describe('rawSqlCalls', () => {
  it('reports a query method that receives SQL after the context', () => {
    const source = [
      'package db_postgres',
      '',
      'func (r *Repo) Find(ctx context.Context) error {',
      '\treturn r.Pool.QueryRow(ctx, `SELECT 1`).Scan(&n)',
      '}',
    ].join('\n')
    expect(rawSqlCalls(source)).toEqual([{ line: 4, problem: 'unmarked' }])
  })

  it('reports every query method name and a context argument on the next line', () => {
    const source = [
      '_, err := tx.Exec(ctx, q)',
      'rows, err := db.Query(qctx, q)',
      'res := pool.SendBatch(ctx, batch)',
      'n, err := conn.CopyFrom(',
      '\tctx, pgx.Identifier{"t"}, cols, src)',
      'db.Exec(context.Background(), q)',
    ].join('\n')
    expect(rawSqlCalls(source).map((call) => call.line)).toEqual([1, 2, 3, 4, 6])
  })

  it('ignores a query method that takes no context', () => {
    expect(rawSqlCalls('query := u.Query()\ncode := redirect.Query().Get("code")')).toEqual([])
  })

  it('skips a generated file', () => {
    const source = [
      '// Code generated by sqlc. DO NOT EDIT.',
      'package db_postgres',
      'func (q *Queries) F(ctx context.Context) error { _, err := q.db.Exec(ctx, f); return err }',
    ].join('\n')
    expect(rawSqlCalls(source)).toEqual([])
  })

  it('accepts a call whose preceding line gives a reason', () => {
    const source = [
      '//sql:raw 絞り込み式の数が要求ごとに変わる',
      'rows, err := r.Pool.Query(ctx, query, args...)',
    ].join('\n')
    expect(rawSqlCalls(source)).toEqual([])
  })

  it('accepts an indented marker', () => {
    const source = ['\t//sql:raw DDL を適用する', '\t_, err := pool.Exec(ctx, schema)'].join('\n')
    expect(rawSqlCalls(source)).toEqual([])
  })

  it('rejects a marker without a reason', () => {
    const source = ['//sql:raw', 'rows, err := r.Pool.Query(ctx, query, args...)'].join('\n')
    expect(rawSqlCalls(source)).toEqual([{ line: 2, problem: 'missing-reason' }])
  })

  it('does not let a marker reach past the next line', () => {
    const source = [
      '//sql:raw 絞り込み式の数が要求ごとに変わる',
      'where := build()',
      'rows, err := r.Pool.Query(ctx, query, args...)',
    ].join('\n')
    expect(rawSqlCalls(source)).toEqual([{ line: 3, problem: 'unmarked' }])
  })
})
