// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db_postgres

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type DynamicGroupRule struct {
	GroupID              string
	TenantID             string
	Expression           string
	Enabled              bool
	Version              int64
	ReferencedAttributes []byte
	CreatedAt            time.Time
	UpdatedAt            time.Time
}

type Group struct {
	ID             string
	TenantID       string
	Name           string
	Description    pgtype.Text
	Email          pgtype.Text
	Attributes     []byte
	Roles          []byte
	MembershipType string
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

type TenantGroupAttributeSchema struct {
	TenantID   string
	Attributes []byte
	CreatedAt  time.Time
	UpdatedAt  time.Time
}
