// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db_postgres

import (
	"context"
)

type Querier interface {
	AddGroupMember(ctx context.Context, arg AddGroupMemberParams) (int64, error)
	CountGroupMembers(ctx context.Context, arg CountGroupMembersParams) (int64, error)
	DeleteGroup(ctx context.Context, arg DeleteGroupParams) error
	FindGroupByID(ctx context.Context, arg FindGroupByIDParams) (*Group, error)
	ListGroupMembersByGroup(ctx context.Context, arg ListGroupMembersByGroupParams) ([]*ListGroupMembersByGroupRow, error)
	ListGroupsByTenant(ctx context.Context, tenantID string) ([]*Group, error)
	ListGroupsByUser(ctx context.Context, arg ListGroupsByUserParams) ([]*Group, error)
	RemoveGroupMember(ctx context.Context, arg RemoveGroupMemberParams) (int64, error)
	SaveGroup(ctx context.Context, arg SaveGroupParams) error
}

var _ Querier = (*Queries)(nil)
