// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tenant_group_attribute_schemas.sql

package db_postgres

import (
	"context"
	"time"
)

const deleteTenantGroupAttributeSchema = `-- name: DeleteTenantGroupAttributeSchema :exec
DELETE FROM tenant_group_attribute_schemas WHERE tenant_id=$1
`

func (q *Queries) DeleteTenantGroupAttributeSchema(ctx context.Context, tenantID string) error {
	_, err := q.db.Exec(ctx, deleteTenantGroupAttributeSchema, tenantID)
	return err
}

const findTenantGroupAttributeSchemaByTenant = `-- name: FindTenantGroupAttributeSchemaByTenant :one
SELECT tenant_id,attributes,created_at,updated_at FROM tenant_group_attribute_schemas
WHERE tenant_id=$1
`

func (q *Queries) FindTenantGroupAttributeSchemaByTenant(ctx context.Context, tenantID string) (*TenantGroupAttributeSchema, error) {
	row := q.db.QueryRow(ctx, findTenantGroupAttributeSchemaByTenant, tenantID)
	var i TenantGroupAttributeSchema
	err := row.Scan(
		&i.TenantID,
		&i.Attributes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const saveTenantGroupAttributeSchema = `-- name: SaveTenantGroupAttributeSchema :exec
INSERT INTO tenant_group_attribute_schemas (tenant_id,attributes,created_at,updated_at)
VALUES ($1,$2,$3,$4)
ON CONFLICT (tenant_id) DO UPDATE SET attributes=EXCLUDED.attributes,updated_at=EXCLUDED.updated_at
`

type SaveTenantGroupAttributeSchemaParams struct {
	TenantID   string
	Attributes []byte
	CreatedAt  time.Time
	UpdatedAt  time.Time
}

func (q *Queries) SaveTenantGroupAttributeSchema(ctx context.Context, arg SaveTenantGroupAttributeSchemaParams) error {
	_, err := q.db.Exec(ctx, saveTenantGroupAttributeSchema,
		arg.TenantID,
		arg.Attributes,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}
