// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: mfa_factors.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteMfaFactor = `-- name: DeleteMfaFactor :exec
DELETE FROM mfa_factors WHERE user_id = $1 AND type = $2
`

type DeleteMfaFactorParams struct {
	UserID string
	Type   string
}

func (q *Queries) DeleteMfaFactor(ctx context.Context, arg DeleteMfaFactorParams) error {
	_, err := q.db.Exec(ctx, deleteMfaFactor, arg.UserID, arg.Type)
	return err
}

const deleteMfaFactorsForSub = `-- name: DeleteMfaFactorsForSub :exec
DELETE FROM mfa_factors WHERE user_id = $1
`

func (q *Queries) DeleteMfaFactorsForSub(ctx context.Context, userID string) error {
	_, err := q.db.Exec(ctx, deleteMfaFactorsForSub, userID)
	return err
}

const getMfaFactor = `-- name: GetMfaFactor :one
SELECT user_id, type, secret, label, created_at, last_used_at
FROM mfa_factors
WHERE user_id = $1 AND type = $2
`

type GetMfaFactorParams struct {
	UserID string
	Type   string
}

type GetMfaFactorRow struct {
	UserID     string
	Type       string
	Secret     pgtype.Text
	Label      pgtype.Text
	CreatedAt  time.Time
	LastUsedAt pgtype.Timestamptz
}

func (q *Queries) GetMfaFactor(ctx context.Context, arg GetMfaFactorParams) (*GetMfaFactorRow, error) {
	row := q.db.QueryRow(ctx, getMfaFactor, arg.UserID, arg.Type)
	var i GetMfaFactorRow
	err := row.Scan(
		&i.UserID,
		&i.Type,
		&i.Secret,
		&i.Label,
		&i.CreatedAt,
		&i.LastUsedAt,
	)
	return &i, err
}

const listMfaFactorsBySub = `-- name: ListMfaFactorsBySub :many
SELECT user_id, type, secret, label, created_at, last_used_at
FROM mfa_factors
WHERE user_id = $1
ORDER BY created_at
`

type ListMfaFactorsBySubRow struct {
	UserID     string
	Type       string
	Secret     pgtype.Text
	Label      pgtype.Text
	CreatedAt  time.Time
	LastUsedAt pgtype.Timestamptz
}

func (q *Queries) ListMfaFactorsBySub(ctx context.Context, userID string) ([]*ListMfaFactorsBySubRow, error) {
	rows, err := q.db.Query(ctx, listMfaFactorsBySub, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*ListMfaFactorsBySubRow
	for rows.Next() {
		var i ListMfaFactorsBySubRow
		if err := rows.Scan(
			&i.UserID,
			&i.Type,
			&i.Secret,
			&i.Label,
			&i.CreatedAt,
			&i.LastUsedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertMfaFactor = `-- name: UpsertMfaFactor :exec
INSERT INTO mfa_factors (user_id, type, secret, label, created_at, last_used_at)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (user_id, type) DO UPDATE SET
    secret = EXCLUDED.secret,
    label = EXCLUDED.label,
    last_used_at = EXCLUDED.last_used_at,
    updated_at = now()
`

type UpsertMfaFactorParams struct {
	UserID     string
	Type       string
	Secret     pgtype.Text
	Label      pgtype.Text
	CreatedAt  time.Time
	LastUsedAt pgtype.Timestamptz
}

func (q *Queries) UpsertMfaFactor(ctx context.Context, arg UpsertMfaFactorParams) error {
	_, err := q.db.Exec(ctx, upsertMfaFactor,
		arg.UserID,
		arg.Type,
		arg.Secret,
		arg.Label,
		arg.CreatedAt,
		arg.LastUsedAt,
	)
	return err
}
