// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"context"
	"time"
)

type Querier interface {
	ConsumeEmailChangeToken(ctx context.Context, tokenHash string) (*ConsumeEmailChangeTokenRow, error)
	DeleteAuthEventBucketsOlderThan(ctx context.Context, windowStart time.Time) (int64, error)
	DeleteEmailChangeTokensForSub(ctx context.Context, userID string) error
	DeleteMfaFactor(ctx context.Context, arg DeleteMfaFactorParams) error
	DeleteMfaFactorsForSub(ctx context.Context, userID string) error
	DeletePasswordHistoryForSub(ctx context.Context, userID string) error
	DeleteRecoveryCodesForSub(ctx context.Context, userID string) error
	DeleteWebAuthnCredential(ctx context.Context, arg DeleteWebAuthnCredentialParams) error
	DeleteWebAuthnCredentialsForSub(ctx context.Context, userID string) error
	GetMfaFactor(ctx context.Context, arg GetMfaFactorParams) (*GetMfaFactorRow, error)
	GetWebAuthnCredentialByID(ctx context.Context, credentialID string) (*GetWebAuthnCredentialByIDRow, error)
	InsertEmailChangeToken(ctx context.Context, arg InsertEmailChangeTokenParams) error
	InsertPasswordHistory(ctx context.Context, arg InsertPasswordHistoryParams) error
	InsertRecoveryCode(ctx context.Context, arg InsertRecoveryCodeParams) error
	ListAuthEventBuckets(ctx context.Context, arg ListAuthEventBucketsParams) ([]*ListAuthEventBucketsRow, error)
	ListMfaFactorsBySub(ctx context.Context, userID string) ([]*ListMfaFactorsBySubRow, error)
	ListRecoveryCodesBySub(ctx context.Context, userID string) ([]*RecoveryCode, error)
	ListWebAuthnCredentialsBySub(ctx context.Context, userID string) ([]*ListWebAuthnCredentialsBySubRow, error)
	MarkRecoveryCodeConsumed(ctx context.Context, arg MarkRecoveryCodeConsumedParams) (int64, error)
	RecentPasswordHistory(ctx context.Context, arg RecentPasswordHistoryParams) ([]*RecentPasswordHistoryRow, error)
	RecordAuthEventBucket(ctx context.Context, arg RecordAuthEventBucketParams) (*RecordAuthEventBucketRow, error)
	UpdateWebAuthnCredentialSignCount(ctx context.Context, arg UpdateWebAuthnCredentialSignCountParams) error
	UpsertMfaFactor(ctx context.Context, arg UpsertMfaFactorParams) error
	UpsertWebAuthnCredential(ctx context.Context, arg UpsertWebAuthnCredentialParams) error
}

var _ Querier = (*Queries)(nil)
