// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: authnrequest_replay_store.sql

package db_postgres

import (
	"context"
	"time"
)

const deleteExpiredSamlAuthnRequestReplaysBatch = `-- name: DeleteExpiredSamlAuthnRequestReplaysBatch :execrows
DELETE FROM saml_authnrequest_replays AS o
WHERE (o.tenant_id, o.entity_id, o.request_id) IN (
    SELECT s.tenant_id, s.entity_id, s.request_id
    FROM saml_authnrequest_replays AS s
    WHERE s.expires_at < $1
    LIMIT $2
)
`

type DeleteExpiredSamlAuthnRequestReplaysBatchParams struct {
	Cutoff     time.Time
	BatchLimit int32
}

// housekeeping cleanup。PK を選んで小 batch で削除する (正しさは read 側の expires_at 述語が担保)。
func (q *Queries) DeleteExpiredSamlAuthnRequestReplaysBatch(ctx context.Context, arg DeleteExpiredSamlAuthnRequestReplaysBatchParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredSamlAuthnRequestReplaysBatch, arg.Cutoff, arg.BatchLimit)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const reserveSamlAuthnRequestReplay = `-- name: ReserveSamlAuthnRequestReplay :one
INSERT INTO saml_authnrequest_replays (tenant_id, entity_id, request_id, expires_at)
VALUES ($1, $2, $3, $4)
ON CONFLICT (tenant_id, entity_id, request_id) DO UPDATE
    SET expires_at = EXCLUDED.expires_at, created_at = now()
    WHERE saml_authnrequest_replays.expires_at <= $5
RETURNING request_id
`

type ReserveSamlAuthnRequestReplayParams struct {
	TenantID     string
	EntityID     string
	RequestID    string
	NewExpiresAt time.Time
	Now          time.Time
}

// TTL 付き単発予約。live な予約が既にあれば ON CONFLICT の
// DO UPDATE ... WHERE が false になり 0 行 (ErrNoRows)、期限切れの残骸なら上書きして 1 行、
// 未存在なら INSERT で 1 行を返す。行が返れば新規予約成功 (重複時は 0 行 = 予約失敗)。
func (q *Queries) ReserveSamlAuthnRequestReplay(ctx context.Context, arg ReserveSamlAuthnRequestReplayParams) (string, error) {
	row := q.db.QueryRow(ctx, reserveSamlAuthnRequestReplay,
		arg.TenantID,
		arg.EntityID,
		arg.RequestID,
		arg.NewExpiresAt,
		arg.Now,
	)
	var request_id string
	err := row.Scan(&request_id)
	return request_id, err
}
