// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: groups.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const addGroupMember = `-- name: AddGroupMember :execrows
INSERT INTO group_members (group_id,user_id,created_at) VALUES ($1,$2,$3)
ON CONFLICT (group_id,user_id) DO NOTHING
`

type AddGroupMemberParams struct {
	GroupID   string
	UserID    string
	CreatedAt time.Time
}

func (q *Queries) AddGroupMember(ctx context.Context, arg AddGroupMemberParams) (int64, error) {
	result, err := q.db.Exec(ctx, addGroupMember, arg.GroupID, arg.UserID, arg.CreatedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const countGroupMembers = `-- name: CountGroupMembers :one
SELECT count(*) FROM group_members gm JOIN groups g ON g.id=gm.group_id
WHERE g.tenant_id=$1 AND gm.group_id=$2
`

type CountGroupMembersParams struct {
	TenantID string
	GroupID  string
}

func (q *Queries) CountGroupMembers(ctx context.Context, arg CountGroupMembersParams) (int64, error) {
	row := q.db.QueryRow(ctx, countGroupMembers, arg.TenantID, arg.GroupID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteGroup = `-- name: DeleteGroup :exec
DELETE FROM groups WHERE tenant_id=$1 AND id=$2
`

type DeleteGroupParams struct {
	TenantID string
	ID       string
}

func (q *Queries) DeleteGroup(ctx context.Context, arg DeleteGroupParams) error {
	_, err := q.db.Exec(ctx, deleteGroup, arg.TenantID, arg.ID)
	return err
}

const findGroupByID = `-- name: FindGroupByID :one
SELECT id,tenant_id,name,description,roles,created_at,updated_at FROM groups
WHERE tenant_id=$1 AND id=$2
`

type FindGroupByIDParams struct {
	TenantID string
	ID       string
}

func (q *Queries) FindGroupByID(ctx context.Context, arg FindGroupByIDParams) (*Group, error) {
	row := q.db.QueryRow(ctx, findGroupByID, arg.TenantID, arg.ID)
	var i Group
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Description,
		&i.Roles,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const listGroupMembersByGroup = `-- name: ListGroupMembersByGroup :many
SELECT gm.group_id,gm.user_id,gm.created_at
FROM group_members gm JOIN groups g ON g.id=gm.group_id
WHERE g.tenant_id=$1 AND gm.group_id=$2 ORDER BY gm.user_id
`

type ListGroupMembersByGroupParams struct {
	TenantID string
	GroupID  string
}

func (q *Queries) ListGroupMembersByGroup(ctx context.Context, arg ListGroupMembersByGroupParams) ([]*GroupMember, error) {
	rows, err := q.db.Query(ctx, listGroupMembersByGroup, arg.TenantID, arg.GroupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*GroupMember
	for rows.Next() {
		var i GroupMember
		if err := rows.Scan(&i.GroupID, &i.UserID, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGroupsByTenant = `-- name: ListGroupsByTenant :many
SELECT id,tenant_id,name,description,roles,created_at,updated_at FROM groups
WHERE tenant_id=$1 ORDER BY name
`

func (q *Queries) ListGroupsByTenant(ctx context.Context, tenantID string) ([]*Group, error) {
	rows, err := q.db.Query(ctx, listGroupsByTenant, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*Group
	for rows.Next() {
		var i Group
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.Description,
			&i.Roles,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGroupsByUser = `-- name: ListGroupsByUser :many
SELECT g.id,g.tenant_id,g.name,g.description,g.roles,g.created_at,g.updated_at
FROM groups g JOIN group_members gm ON gm.group_id=g.id
WHERE g.tenant_id=$1 AND gm.user_id=$2 ORDER BY g.name
`

type ListGroupsByUserParams struct {
	TenantID string
	UserID   string
}

func (q *Queries) ListGroupsByUser(ctx context.Context, arg ListGroupsByUserParams) ([]*Group, error) {
	rows, err := q.db.Query(ctx, listGroupsByUser, arg.TenantID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*Group
	for rows.Next() {
		var i Group
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.Description,
			&i.Roles,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeGroupMember = `-- name: RemoveGroupMember :execrows
DELETE FROM group_members
WHERE group_id=$2 AND user_id=$3
  AND group_id IN (SELECT id FROM groups WHERE tenant_id=$1 AND id=$2)
`

type RemoveGroupMemberParams struct {
	TenantID string
	GroupID  string
	UserID   string
}

func (q *Queries) RemoveGroupMember(ctx context.Context, arg RemoveGroupMemberParams) (int64, error) {
	result, err := q.db.Exec(ctx, removeGroupMember, arg.TenantID, arg.GroupID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const saveGroup = `-- name: SaveGroup :exec
INSERT INTO groups (id,tenant_id,name,description,roles,created_at,updated_at)
VALUES ($1,$2,$3,$4,$5,$6,$7)
ON CONFLICT (id) DO UPDATE SET name=EXCLUDED.name,description=EXCLUDED.description,
 roles=EXCLUDED.roles,updated_at=EXCLUDED.updated_at
`

type SaveGroupParams struct {
	ID          string
	TenantID    string
	Name        string
	Description pgtype.Text
	Roles       []byte
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

func (q *Queries) SaveGroup(ctx context.Context, arg SaveGroupParams) error {
	_, err := q.db.Exec(ctx, saveGroup,
		arg.ID,
		arg.TenantID,
		arg.Name,
		arg.Description,
		arg.Roles,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}
