// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type Agent struct {
	ID          string
	TenantID    string
	Name        string
	Description pgtype.Text
	Kind        string
	OwnerUserID string
	Status      string
	Roles       []byte
	CreatedAt   time.Time
	UpdatedAt   time.Time
	DisabledAt  pgtype.Timestamptz
	KilledAt    pgtype.Timestamptz
}

type AgentCredentialBinding struct {
	AgentID   string
	ClientID  string
	CreatedAt time.Time
}

type Application struct {
	TenantID      string
	ApplicationID string
	Name          string
	Kind          string
	Status        string
	IconUrl       string
	IconObjectKey string
	LaunchUrl     string
	Bindings      []byte
	CategoryIds   []string
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

type ApplicationAssignment struct {
	ApplicationID string
	SubjectType   string
	SubjectID     string
	Visibility    string
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

type ApplicationCategory struct {
	TenantID   string
	CategoryID string
	Name       string
	Position   int32
	CreatedAt  time.Time
	UpdatedAt  time.Time
}

type ApplicationIcon struct {
	ApplicationID string
	ObjectKey     string
	ContentType   string
	SizeBytes     int32
	Data          []byte
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

type ApplicationOrdering struct {
	UserID         string
	ApplicationIds []string
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

type ApplicationSignInPolicy struct {
	ApplicationID string
	Rules         []byte
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

type AuditEvent struct {
	ID         string
	TenantID   string
	Type       string
	UserID     pgtype.UUID
	CreatedAt  time.Time
	OccurredAt time.Time
	Payload    []byte
}

type AuditEventSearchAttribute struct {
	EventID    string
	TenantID   string
	AttrName   string
	AttrValue  string
	OccurredAt time.Time
}

type AuthenticationEventBucket struct {
	TenantID    string
	Kind        string
	KeyHash     string
	WindowStart time.Time
	Count       int64
	CreatedAt   time.Time
	UpdatedAt   time.Time
	FirstSeen   time.Time
	LastSeen    time.Time
}

type AuthorizationDetailType struct {
	TenantID        string
	Type            string
	Description     pgtype.Text
	Schema          []byte
	DisplayTemplate string
	State           string
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

type Client struct {
	TenantID                           string
	ClientID                           string
	ClientSecretHash                   pgtype.Text
	ClientName                         pgtype.Text
	ClientType                         string
	RedirectUris                       []byte
	GrantTypes                         []byte
	ResponseTypes                      []byte
	TokenEndpointAuthMethod            string
	Scope                              string
	JwksUri                            pgtype.Text
	Jwks                               []byte
	TlsClientAuthSubjectDn             pgtype.Text
	IDTokenSignedResponseAlg           string
	RequirePushedAuthorizationRequests bool
	DpopBoundAccessTokens              bool
	FapiProfile                        string
	CreatedAt                          time.Time
	UpdatedAt                          time.Time
	FirstParty                         bool
}

type Consent struct {
	UserID    string
	ClientID  string
	Scopes    []byte
	CreatedAt time.Time
	UpdatedAt time.Time
	GrantedAt time.Time
	ExpiresAt time.Time
	RevokedAt pgtype.Timestamptz
}

type DynamicGroupRule struct {
	GroupID              string
	TenantID             string
	Expression           string
	Enabled              bool
	Version              int64
	ReferencedAttributes []byte
	CreatedAt            time.Time
	UpdatedAt            time.Time
}

type EmailChangeToken struct {
	TokenHash string
	UserID    string
	NewEmail  string
	CreatedAt time.Time
	ExpiresAt time.Time
}

type Group struct {
	ID             string
	TenantID       string
	Name           string
	Description    pgtype.Text
	Roles          []byte
	MembershipType string
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

type GroupMember struct {
	GroupID     string
	UserID      string
	CreatedAt   time.Time
	Source      string
	RuleVersion pgtype.Int8
}

type Job struct {
	ID             string
	TenantID       string
	Kind           string
	Status         string
	Params         []byte
	Result         []byte
	Error          pgtype.Text
	Attempts       int32
	MaxAttempts    int32
	DedupKey       pgtype.Text
	LeaseOwner     pgtype.Text
	LeaseExpiresAt pgtype.Timestamptz
	RunAt          time.Time
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

type MfaEnrollmentBypass struct {
	ID         string
	TenantID   string
	UserID     string
	IssuedBy   string
	IssuedAt   time.Time
	ExpiresAt  time.Time
	ConsumedAt pgtype.Timestamptz
	RevokedAt  pgtype.Timestamptz
	ExpiredAt  pgtype.Timestamptz
}

type MfaFactor struct {
	UserID     string
	Type       string
	Secret     pgtype.Text
	Label      pgtype.Text
	CreatedAt  time.Time
	UpdatedAt  time.Time
	LastUsedAt pgtype.Timestamptz
}

type Outbox struct {
	ID          int64
	EventType   string
	Topic       string
	Payload     []byte
	CreatedAt   time.Time
	UpdatedAt   time.Time
	PublishedAt pgtype.Timestamptz
	PublishedTo pgtype.Text
	Attempts    int32
	LastError   pgtype.Text
}

type PasswordHistory struct {
	ID        string
	UserID    string
	Encoded   string
	CreatedAt time.Time
}

type PasswordResetToken struct {
	TokenHash string
	UserID    string
	CreatedAt time.Time
	ExpiresAt time.Time
}

type RecoveryCode struct {
	UserID      string
	CodeHash    string
	GeneratedAt time.Time
	ConsumedAt  pgtype.Timestamptz
}

type RefreshToken struct {
	ID                string
	Hash              string
	FamilyID          string
	ParentID          pgtype.UUID
	ClientID          string
	UserID            string
	Scopes            []byte
	CreatedAt         time.Time
	UpdatedAt         time.Time
	IssuedAt          time.Time
	ExpiresAt         time.Time
	AbsoluteExpiresAt time.Time
	Revoked           bool
	Rotated           bool
	SenderConstraint  []byte
}

type SamlServiceProvider struct {
	TenantID                          string
	EntityID                          string
	DisplayName                       string
	AcsUrls                           []byte
	SloUrl                            string
	Audience                          string
	ClaimPolicy                       []byte
	SignAssertion                     bool
	SignResponse                      bool
	WantAuthnRequestsSigned           bool
	AuthnRequestSigningCertificatePem string
	CreatedAt                         time.Time
	UpdatedAt                         time.Time
}

type ScimGroupRef struct {
	TenantID  string
	ScimID    string
	GroupID   string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type ScimToken struct {
	ID          string
	TenantID    string
	TokenHash   string
	Description pgtype.Text
	CreatedAt   time.Time
	UpdatedAt   time.Time
	ExpiresAt   pgtype.Timestamptz
}

type ScimUserRef struct {
	TenantID  string
	ScimID    string
	UserID    string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type SigningKey struct {
	Kid        string
	TenantID   string
	Alg        string
	Provider   string
	KeyUsage   string
	PublicJwk  []byte
	PrivateJwk []byte
	Active     bool
	CreatedAt  time.Time
	UpdatedAt  time.Time
	RotatedAt  pgtype.Timestamptz
	ArchivedAt pgtype.Timestamptz
}

type Tenant struct {
	ID          string
	Realm       string
	DisplayName string
	Status      string
	CreatedAt   time.Time
	UpdatedAt   time.Time
	DisabledAt  pgtype.Timestamptz
}

type TenantBranding struct {
	TenantID         string
	ProductName      pgtype.Text
	LogoObjectKey    pgtype.Text
	LogoUrl          pgtype.Text
	FaviconObjectKey pgtype.Text
	FaviconUrl       pgtype.Text
	PrimaryColor     pgtype.Text
	AccentColor      pgtype.Text
	FooterLink1Label pgtype.Text
	FooterLink1Url   pgtype.Text
	FooterLink2Label pgtype.Text
	FooterLink2Url   pgtype.Text
	FooterText       pgtype.Text
	CreatedAt        time.Time
	UpdatedAt        time.Time
}

type TenantBrandingAsset struct {
	TenantID    string
	Kind        string
	ObjectKey   string
	ContentType string
	SizeBytes   int32
	Data        []byte
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type TenantCorrelationSalt struct {
	TenantID  string
	Salt      []byte
	CreatedAt time.Time
}

type TenantDefaultSignInPolicy struct {
	TenantID  string
	Rules     []byte
	CreatedAt time.Time
	UpdatedAt time.Time
}

type TenantUserAttributeSchema struct {
	TenantID   string
	Attributes []byte
	CreatedAt  time.Time
	UpdatedAt  time.Time
}

type User struct {
	ID                string
	TenantID          string
	PreferredUsername string
	PasswordHash      string
	Name              pgtype.Text
	GivenName         pgtype.Text
	FamilyName        pgtype.Text
	Email             pgtype.Text
	EmailVerified     bool
	MfaEnrolled       bool
	CreatedAt         time.Time
	UpdatedAt         time.Time
	Roles             []byte
	Lifecycle         []byte
	Attributes        []byte
}

type WebauthnCredential struct {
	CredentialID   string
	UserID         string
	PublicKey      string
	SignCount      int64
	Transports     []string
	Aaguid         pgtype.Text
	Label          pgtype.Text
	BackupEligible bool
	BackupState    bool
	CreatedAt      time.Time
	UpdatedAt      time.Time
	LastUsedAt     pgtype.Timestamptz
}

type WsfedRelyingParty struct {
	TenantID     string
	Wtrealm      string
	DisplayName  string
	ReplyUrls    []byte
	Audience     string
	TokenType    string
	ClaimPolicy  []byte
	EntraProfile []byte
	CreatedAt    time.Time
	UpdatedAt    time.Time
}
