// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"context"
)

type Querier interface {
	AddAgentBinding(ctx context.Context, arg AddAgentBindingParams) (int64, error)
	AddGroupMember(ctx context.Context, arg AddGroupMemberParams) (int64, error)
	CountGroupMembers(ctx context.Context, arg CountGroupMembersParams) (int64, error)
	DeleteAgent(ctx context.Context, arg DeleteAgentParams) error
	DeleteGroup(ctx context.Context, arg DeleteGroupParams) error
	DeleteTenantUserAttributeSchema(ctx context.Context, tenantID string) error
	FindAgentByClientID(ctx context.Context, arg FindAgentByClientIDParams) (*Agent, error)
	FindAgentByID(ctx context.Context, arg FindAgentByIDParams) (*Agent, error)
	FindGroupByID(ctx context.Context, arg FindGroupByIDParams) (*Group, error)
	FindTenantUserAttributeSchemaByTenant(ctx context.Context, tenantID string) (*TenantUserAttributeSchema, error)
	FindUserByEmail(ctx context.Context, arg FindUserByEmailParams) (*User, error)
	FindUserBySub(ctx context.Context, id string) (*User, error)
	FindUserBySubIncludingDeleted(ctx context.Context, id string) (*User, error)
	FindUserByUsername(ctx context.Context, arg FindUserByUsernameParams) (*User, error)
	ListAgentBindingsByAgent(ctx context.Context, arg ListAgentBindingsByAgentParams) ([]*AgentCredentialBinding, error)
	ListAgentsByTenant(ctx context.Context, tenantID string) ([]*Agent, error)
	ListGroupMembersByGroup(ctx context.Context, arg ListGroupMembersByGroupParams) ([]*GroupMember, error)
	ListGroupsByTenant(ctx context.Context, tenantID string) ([]*Group, error)
	ListGroupsByUser(ctx context.Context, arg ListGroupsByUserParams) ([]*Group, error)
	ListUsersByTenant(ctx context.Context, tenantID string) ([]*User, error)
	RemoveAgentBinding(ctx context.Context, arg RemoveAgentBindingParams) (int64, error)
	RemoveGroupMember(ctx context.Context, arg RemoveGroupMemberParams) (int64, error)
	SaveAgent(ctx context.Context, arg SaveAgentParams) error
	SaveGroup(ctx context.Context, arg SaveGroupParams) error
	SaveTenantUserAttributeSchema(ctx context.Context, arg SaveTenantUserAttributeSchemaParams) error
	SaveUser(ctx context.Context, arg SaveUserParams) error
}

var _ Querier = (*Queries)(nil)
