// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db_postgres

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type Application struct {
	TenantID      string
	ID            string
	Name          string
	Kind          string
	Status        string
	ProtocolType  pgtype.Text
	IconUrl       string
	IconObjectKey string
	LaunchUrl     string
	CategoryIds   []string
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

type ApplicationCategory struct {
	TenantID  string
	ID        string
	Name      string
	Position  int32
	CreatedAt time.Time
	UpdatedAt time.Time
}

type ApplicationOrdering struct {
	UserID         string
	ApplicationIds []string
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

type TenantDefaultSignInPolicy struct {
	TenantID  string
	Rules     []byte
	CreatedAt time.Time
	UpdatedAt time.Time
}
