// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: api_tokens.sql

package db_postgres

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const findApiTokenByJTI = `-- name: FindApiTokenByJTI :one
SELECT id, tenant_id, user_id, jti, client_id, scopes, audience, dpop_jkt,
       description, created_at, expires_at, revoked_at
FROM api_tokens WHERE tenant_id = $1 AND jti = $2
`

type FindApiTokenByJTIParams struct {
	TenantID string
	Jti      string
}

type FindApiTokenByJTIRow struct {
	ID          string
	TenantID    string
	UserID      string
	Jti         string
	ClientID    string
	Scopes      []string
	Audience    string
	DpopJkt     pgtype.Text
	Description pgtype.Text
	CreatedAt   time.Time
	ExpiresAt   pgtype.Timestamptz
	RevokedAt   pgtype.Timestamptz
}

func (q *Queries) FindApiTokenByJTI(ctx context.Context, arg FindApiTokenByJTIParams) (*FindApiTokenByJTIRow, error) {
	row := q.db.QueryRow(ctx, findApiTokenByJTI, arg.TenantID, arg.Jti)
	var i FindApiTokenByJTIRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.Jti,
		&i.ClientID,
		&i.Scopes,
		&i.Audience,
		&i.DpopJkt,
		&i.Description,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
	)
	return &i, err
}

const listApiTokensByTenant = `-- name: ListApiTokensByTenant :many
SELECT id, tenant_id, user_id, jti, client_id, scopes, audience, dpop_jkt,
       description, created_at, expires_at, revoked_at
FROM api_tokens WHERE tenant_id = $1 ORDER BY created_at, id
`

type ListApiTokensByTenantRow struct {
	ID          string
	TenantID    string
	UserID      string
	Jti         string
	ClientID    string
	Scopes      []string
	Audience    string
	DpopJkt     pgtype.Text
	Description pgtype.Text
	CreatedAt   time.Time
	ExpiresAt   pgtype.Timestamptz
	RevokedAt   pgtype.Timestamptz
}

func (q *Queries) ListApiTokensByTenant(ctx context.Context, tenantID string) ([]*ListApiTokensByTenantRow, error) {
	rows, err := q.db.Query(ctx, listApiTokensByTenant, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*ListApiTokensByTenantRow
	for rows.Next() {
		var i ListApiTokensByTenantRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.UserID,
			&i.Jti,
			&i.ClientID,
			&i.Scopes,
			&i.Audience,
			&i.DpopJkt,
			&i.Description,
			&i.CreatedAt,
			&i.ExpiresAt,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeApiToken = `-- name: RevokeApiToken :exec
UPDATE api_tokens SET revoked_at = COALESCE(revoked_at, $3), updated_at = now()
WHERE tenant_id = $1 AND id = $2
`

type RevokeApiTokenParams struct {
	TenantID  string
	ID        string
	RevokedAt pgtype.Timestamptz
}

func (q *Queries) RevokeApiToken(ctx context.Context, arg RevokeApiTokenParams) error {
	_, err := q.db.Exec(ctx, revokeApiToken, arg.TenantID, arg.ID, arg.RevokedAt)
	return err
}

const revokeApiTokenByJTI = `-- name: RevokeApiTokenByJTI :exec
UPDATE api_tokens SET revoked_at = COALESCE(revoked_at, $3), updated_at = now()
WHERE tenant_id = $1 AND jti = $2
`

type RevokeApiTokenByJTIParams struct {
	TenantID  string
	Jti       string
	RevokedAt pgtype.Timestamptz
}

func (q *Queries) RevokeApiTokenByJTI(ctx context.Context, arg RevokeApiTokenByJTIParams) error {
	_, err := q.db.Exec(ctx, revokeApiTokenByJTI, arg.TenantID, arg.Jti, arg.RevokedAt)
	return err
}

const saveApiToken = `-- name: SaveApiToken :exec
INSERT INTO api_tokens (
    id, tenant_id, user_id, jti, client_id, scopes, audience, dpop_jkt,
    description, created_at, expires_at, revoked_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
ON CONFLICT (id) DO UPDATE SET
    user_id=EXCLUDED.user_id,
    jti=EXCLUDED.jti,
    client_id=EXCLUDED.client_id,
    scopes=EXCLUDED.scopes,
    audience=EXCLUDED.audience,
    dpop_jkt=EXCLUDED.dpop_jkt,
    description=EXCLUDED.description,
    expires_at=EXCLUDED.expires_at,
    revoked_at=EXCLUDED.revoked_at,
    updated_at=now()
`

type SaveApiTokenParams struct {
	ID          string
	TenantID    string
	UserID      string
	Jti         string
	ClientID    string
	Scopes      []string
	Audience    string
	DpopJkt     pgtype.Text
	Description pgtype.Text
	CreatedAt   time.Time
	ExpiresAt   pgtype.Timestamptz
	RevokedAt   pgtype.Timestamptz
}

func (q *Queries) SaveApiToken(ctx context.Context, arg SaveApiTokenParams) error {
	_, err := q.db.Exec(ctx, saveApiToken,
		arg.ID,
		arg.TenantID,
		arg.UserID,
		arg.Jti,
		arg.ClientID,
		arg.Scopes,
		arg.Audience,
		arg.DpopJkt,
		arg.Description,
		arg.CreatedAt,
		arg.ExpiresAt,
		arg.RevokedAt,
	)
	return err
}
