// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db_postgres

import (
	"context"
)

type Querier interface {
	FindApiTokenByJTI(ctx context.Context, arg FindApiTokenByJTIParams) (*FindApiTokenByJTIRow, error)
	ListApiTokensByTenant(ctx context.Context, tenantID string) ([]*ListApiTokensByTenantRow, error)
	RevokeApiToken(ctx context.Context, arg RevokeApiTokenParams) error
	RevokeApiTokenByJTI(ctx context.Context, arg RevokeApiTokenByJTIParams) error
	SaveApiToken(ctx context.Context, arg SaveApiTokenParams) error
}

var _ Querier = (*Queries)(nil)
