// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db_postgres

import (
	"context"
)

type Querier interface {
	DeleteApiToken(ctx context.Context, arg DeleteApiTokenParams) error
	FindApiTokenByHash(ctx context.Context, tokenHash string) (*FindApiTokenByHashRow, error)
	ListApiTokensByTenant(ctx context.Context, tenantID string) ([]*ListApiTokensByTenantRow, error)
	SaveApiToken(ctx context.Context, arg SaveApiTokenParams) error
}

var _ Querier = (*Queries)(nil)
