package server_http

import (
	"fmt"
	"maps"
	"slices"
	"strings"

	support "github.com/ambi/idmagic/backend/shared/http/support_http"

	"github.com/labstack/echo/v5"
)

// referenceClasses は生成物に並べるクラスの順序。捨てられる順、つまり縮退の
// ステージが早い順に並べる。読み手が最初に知りたいのは「何が最初に落ちるか」である。
var referenceClasses = []struct {
	class    support.PriorityClass
	stage    string
	limitKey string
	behavior string
}{
	{
		class:    support.ClassManagementBulk,
		stage:    "3",
		limitKey: "`ADMISSION_MANAGEMENT_BULK_MAX_CONCURRENT_REQUESTS`",
		behavior: "Refused first. Aggregation, export, import, and full resync.",
	},
	{
		class:    support.ClassManagement,
		stage:    "4",
		limitKey: "`ADMISSION_MANAGEMENT_MAX_CONCURRENT_REQUESTS`",
		behavior: "Refused once the bulk limit no longer relieves the saturation. Everything an existing session's authentication and token processing does not need.",
	},
	{
		class:    support.ClassInteractiveAuth,
		stage:    "5",
		limitKey: "`ADMISSION_MAX_CONCURRENT_REQUESTS`",
		behavior: "Refused last, and only at the process-wide limit.",
	},
	{
		class:    support.ClassInfrastructure,
		stage:    "—",
		limitKey: "—",
		behavior: "Never refused. Refusing a readiness probe takes every saturated replica out of load balancing at once.",
	},
}

// RenderPriorityClassReference renders the operator-facing route priority
// reference from the assembled router and the classification the admission
// middleware actually applies. Nothing here is hand-kept: the routes come from
// Register and the classes from ClassifyRoute, so the document cannot drift
// from the behaviour it describes without `mise run check-route-reference`
// failing (REQ-SYSTEM-019).
//
// It exists because the classification is otherwise readable only as an
// ordered prefix table in Go, where answering "which class is this route in"
// means resolving rule precedence by hand — and getting that wrong is
// invisible until the process saturates.
func RenderPriorityClassReference() string {
	routes := map[support.PriorityClass]map[string]map[string]struct{}{}
	for _, route := range echoRoutes() {
		class := ClassifyRoute(route.Path)
		path := referencePath(route.Path)
		if routes[class] == nil {
			routes[class] = map[string]map[string]struct{}{}
		}
		if routes[class][path] == nil {
			routes[class][path] = map[string]struct{}{}
		}
		routes[class][path][route.Method] = struct{}{}
	}

	var b strings.Builder
	b.WriteString("# Route Priority Reference\n\n")
	b.WriteString("Generated by `mise run generate-route-reference` from the assembled router and the\n")
	b.WriteString("priority classification the admission middleware applies. Do not edit by hand:\n")
	b.WriteString("`mise run check-route-reference` fails when this file and the classification differ.\n\n")
	b.WriteString("When the API process saturates it refuses requests from the lowest priority class\n")
	b.WriteString("upward, with 503, `Retry-After`, and a `urn:idmagic:error:service_overloaded`\n")
	b.WriteString("Problem Details. The refusal happens after routing and before any handler, so a\n")
	b.WriteString("refused request changes no state. Thresholds, defaults, and the operational\n")
	b.WriteString("reasoning live in `docs/contexts/system/decisions.md`; the degradation order they implement is\n")
	b.WriteString("normative in `docs/design/performance/capacity.md`.\n\n")
	b.WriteString("A route reachable both unprefixed and under `/realms/{tenant_id}/…` appears once:\n")
	b.WriteString("both forms carry the same class.\n\n")

	b.WriteString("## Classes\n\n")
	b.WriteString("| Class | Degradation stage | Concurrency limit | Behaviour when saturated |\n")
	b.WriteString("| --- | --- | --- | --- |\n")
	for _, entry := range referenceClasses {
		fmt.Fprintf(&b, "| `%s` | %s | %s | %s |\n", entry.class, entry.stage, entry.limitKey, entry.behavior)
	}

	for _, entry := range referenceClasses {
		paths := routes[entry.class]
		fmt.Fprintf(&b, "\n## `%s`\n\n", entry.class)
		if len(paths) == 0 {
			b.WriteString("No route carries this class.\n")
			continue
		}
		fmt.Fprintf(&b, "%d route(s).\n\n", len(paths))
		b.WriteString("| Route | Methods |\n")
		b.WriteString("| --- | --- |\n")
		for _, path := range slices.Sorted(maps.Keys(paths)) {
			methods := slices.Sorted(maps.Keys(paths[path]))
			fmt.Fprintf(&b, "| `%s` | %s |\n", path, strings.Join(methods, ", "))
		}
	}
	return b.String()
}

// echoRoutes assembles the router with no dependencies and returns the routes
// it registered. Deps only decides what a handler can do, never which routes
// exist, so a zero value enumerates the same set production serves — the same
// assumption TestAssembledRoutesMatchGeneratedOpenAPI already relies on.
func echoRoutes() []echo.RouteInfo {
	e := echo.New()
	Register(e, Deps{})
	assembled := make([]echo.RouteInfo, 0, len(e.Router().Routes()))
	for _, route := range e.Router().Routes() {
		// echo v5.3+ auto-registers an implicit not-found route per group; it
		// is router bookkeeping, not an API operation.
		if route.Method == echo.RouteNotFound {
			continue
		}
		assembled = append(assembled, route)
	}
	return assembled
}

// referencePath renders one route pattern for the generated document: the
// tenant path prefix removed, and echo's `:name` parameters written the way the
// generated OpenAPI writes them.
func referencePath(pattern string) string {
	path := strings.TrimPrefix(pattern, "/realms/:tenant_id")
	if path == "" {
		path = "/"
	}
	segments := strings.Split(path, "/")
	for i, segment := range segments {
		if after, ok := strings.CutPrefix(segment, ":"); ok {
			segments[i] = "{" + after + "}"
		}
	}
	return strings.Join(segments, "/")
}
