// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: login_attempt_throttle.sql

package db_postgres

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteExpiredThrottleCountersBatch = `-- name: DeleteExpiredThrottleCountersBatch :execrows
DELETE FROM login_throttle_counters AS o
WHERE (o.tenant_id, o.kind, o.identifier_hash) IN (
    SELECT s.tenant_id, s.kind, s.identifier_hash
    FROM login_throttle_counters AS s
    WHERE s.window_expires_at < $1 AND (s.locked_until IS NULL OR s.locked_until < $1)
    LIMIT $2
)
`

type DeleteExpiredThrottleCountersBatchParams struct {
	Cutoff     time.Time
	BatchLimit int32
}

// window と lock の双方が過ぎた行だけを回収する (fail-closed 前提を GC で崩さない)。
func (q *Queries) DeleteExpiredThrottleCountersBatch(ctx context.Context, arg DeleteExpiredThrottleCountersBatchParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredThrottleCountersBatch, arg.Cutoff, arg.BatchLimit)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteThrottleCounter = `-- name: DeleteThrottleCounter :exec
DELETE FROM login_throttle_counters
WHERE tenant_id = $1 AND kind = $2 AND identifier_hash = $3
`

type DeleteThrottleCounterParams struct {
	TenantID       string
	Kind           string
	IdentifierHash string
}

func (q *Queries) DeleteThrottleCounter(ctx context.Context, arg DeleteThrottleCounterParams) error {
	_, err := q.db.Exec(ctx, deleteThrottleCounter, arg.TenantID, arg.Kind, arg.IdentifierHash)
	return err
}

const getThrottleLock = `-- name: GetThrottleLock :one
SELECT locked_until FROM login_throttle_counters
WHERE tenant_id = $1 AND kind = $2 AND identifier_hash = $3
`

type GetThrottleLockParams struct {
	TenantID       string
	Kind           string
	IdentifierHash string
}

// TryAcquire 用の read-only lookup。locked_until だけ見て allowed / retry を判定する。
func (q *Queries) GetThrottleLock(ctx context.Context, arg GetThrottleLockParams) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, getThrottleLock, arg.TenantID, arg.Kind, arg.IdentifierHash)
	var locked_until pgtype.Timestamptz
	err := row.Scan(&locked_until)
	return locked_until, err
}

const lockThrottleCounter = `-- name: LockThrottleCounter :one
SELECT failures, window_expires_at, locked_until FROM login_throttle_counters
WHERE tenant_id = $1 AND kind = $2 AND identifier_hash = $3
FOR UPDATE
`

type LockThrottleCounterParams struct {
	TenantID       string
	Kind           string
	IdentifierHash string
}

type LockThrottleCounterRow struct {
	Failures        int32
	WindowExpiresAt time.Time
	LockedUntil     pgtype.Timestamptz
}

// RecordFailure の read-modify-write を直列化する行ロック取得 (Valkey Lua の原子性の写し)。
func (q *Queries) LockThrottleCounter(ctx context.Context, arg LockThrottleCounterParams) (*LockThrottleCounterRow, error) {
	row := q.db.QueryRow(ctx, lockThrottleCounter, arg.TenantID, arg.Kind, arg.IdentifierHash)
	var i LockThrottleCounterRow
	err := row.Scan(&i.Failures, &i.WindowExpiresAt, &i.LockedUntil)
	return &i, err
}

const upsertThrottleCounter = `-- name: UpsertThrottleCounter :exec
INSERT INTO login_throttle_counters (tenant_id, kind, identifier_hash, failures, window_expires_at, locked_until)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (tenant_id, kind, identifier_hash) DO UPDATE
    SET failures = EXCLUDED.failures, window_expires_at = EXCLUDED.window_expires_at,
        locked_until = EXCLUDED.locked_until, updated_at = now()
`

type UpsertThrottleCounterParams struct {
	TenantID        string
	Kind            string
	IdentifierHash  string
	Failures        int32
	WindowExpiresAt time.Time
	LockedUntil     pgtype.Timestamptz
}

func (q *Queries) UpsertThrottleCounter(ctx context.Context, arg UpsertThrottleCounterParams) error {
	_, err := q.db.Exec(ctx, upsertThrottleCounter,
		arg.TenantID,
		arg.Kind,
		arg.IdentifierHash,
		arg.Failures,
		arg.WindowExpiresAt,
		arg.LockedUntil,
	)
	return err
}
