// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: scim_group_refs.sql

package sqlcgen

import (
	"context"
)

const deleteScimGroupRef = `-- name: DeleteScimGroupRef :exec
DELETE FROM scim_group_refs WHERE tenant_id = $1 AND scim_id = $2
`

type DeleteScimGroupRefParams struct {
	TenantID string
	ScimID   string
}

func (q *Queries) DeleteScimGroupRef(ctx context.Context, arg DeleteScimGroupRefParams) error {
	_, err := q.db.Exec(ctx, deleteScimGroupRef, arg.TenantID, arg.ScimID)
	return err
}

const findScimGroupRefByGroupID = `-- name: FindScimGroupRefByGroupID :one
SELECT tenant_id, scim_id, group_id FROM scim_group_refs WHERE tenant_id = $1 AND group_id = $2
`

type FindScimGroupRefByGroupIDParams struct {
	TenantID string
	GroupID  string
}

type FindScimGroupRefByGroupIDRow struct {
	TenantID string
	ScimID   string
	GroupID  string
}

func (q *Queries) FindScimGroupRefByGroupID(ctx context.Context, arg FindScimGroupRefByGroupIDParams) (*FindScimGroupRefByGroupIDRow, error) {
	row := q.db.QueryRow(ctx, findScimGroupRefByGroupID, arg.TenantID, arg.GroupID)
	var i FindScimGroupRefByGroupIDRow
	err := row.Scan(&i.TenantID, &i.ScimID, &i.GroupID)
	return &i, err
}

const findScimGroupRefByScimID = `-- name: FindScimGroupRefByScimID :one
SELECT tenant_id, scim_id, group_id FROM scim_group_refs WHERE tenant_id = $1 AND scim_id = $2
`

type FindScimGroupRefByScimIDParams struct {
	TenantID string
	ScimID   string
}

type FindScimGroupRefByScimIDRow struct {
	TenantID string
	ScimID   string
	GroupID  string
}

func (q *Queries) FindScimGroupRefByScimID(ctx context.Context, arg FindScimGroupRefByScimIDParams) (*FindScimGroupRefByScimIDRow, error) {
	row := q.db.QueryRow(ctx, findScimGroupRefByScimID, arg.TenantID, arg.ScimID)
	var i FindScimGroupRefByScimIDRow
	err := row.Scan(&i.TenantID, &i.ScimID, &i.GroupID)
	return &i, err
}

const saveScimGroupRef = `-- name: SaveScimGroupRef :exec
INSERT INTO scim_group_refs (tenant_id, scim_id, group_id)
VALUES ($1, $2, $3)
ON CONFLICT (tenant_id, scim_id) DO UPDATE SET
    group_id=EXCLUDED.group_id,
    updated_at=now()
`

type SaveScimGroupRefParams struct {
	TenantID string
	ScimID   string
	GroupID  string
}

func (q *Queries) SaveScimGroupRef(ctx context.Context, arg SaveScimGroupRefParams) error {
	_, err := q.db.Exec(ctx, saveScimGroupRef, arg.TenantID, arg.ScimID, arg.GroupID)
	return err
}
