// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db_postgres

import (
	"context"
)

type Querier interface {
	BumpAuthorizationWriteVersion(ctx context.Context, tenantID string) (int64, error)
	DeleteRelationTuple(ctx context.Context, arg DeleteRelationTupleParams) (int64, error)
	DeleteRelationTuplesForObject(ctx context.Context, arg DeleteRelationTuplesForObjectParams) (int64, error)
	GetAuthorizationModelByVersion(ctx context.Context, arg GetAuthorizationModelByVersionParams) (*AuthorizationModel, error)
	GetAuthorizationWriteVersion(ctx context.Context, tenantID string) (int64, error)
	GetLatestAuthorizationModel(ctx context.Context, tenantID string) (*AuthorizationModel, error)
	InsertAuthorizationModel(ctx context.Context, arg InsertAuthorizationModelParams) (*AuthorizationModel, error)
	InsertRelationTuple(ctx context.Context, arg InsertRelationTupleParams) (int64, error)
	ListRelationTupleResourceIDs(ctx context.Context, arg ListRelationTupleResourceIDsParams) ([]string, error)
	ListRelationTupleSubjects(ctx context.Context, arg ListRelationTupleSubjectsParams) ([]*ListRelationTupleSubjectsRow, error)
	ListRelationTuples(ctx context.Context, arg ListRelationTuplesParams) ([]*ListRelationTuplesRow, error)
}

var _ Querier = (*Queries)(nil)
