// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: clients.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteClient = `-- name: DeleteClient :exec
DELETE FROM clients WHERE tenant_id = $1 AND client_id = $2
`

type DeleteClientParams struct {
	TenantID string
	ClientID string
}

func (q *Queries) DeleteClient(ctx context.Context, arg DeleteClientParams) error {
	_, err := q.db.Exec(ctx, deleteClient, arg.TenantID, arg.ClientID)
	return err
}

const getClientByID = `-- name: GetClientByID :one
SELECT tenant_id, client_id, client_secret_hash, client_name, client_type, redirect_uris,
  grant_types, response_types, token_endpoint_auth_method, scope, jwks_uri, jwks,
  tls_client_auth_subject_dn, id_token_signed_response_alg,
  require_pushed_authorization_requests, dpop_bound_access_tokens, fapi_profile,
  created_at, updated_at, first_party
FROM clients
WHERE tenant_id = $1 AND client_id = $2
`

type GetClientByIDParams struct {
	TenantID string
	ClientID string
}

func (q *Queries) GetClientByID(ctx context.Context, arg GetClientByIDParams) (*Client, error) {
	row := q.db.QueryRow(ctx, getClientByID, arg.TenantID, arg.ClientID)
	var i Client
	err := row.Scan(
		&i.TenantID,
		&i.ClientID,
		&i.ClientSecretHash,
		&i.ClientName,
		&i.ClientType,
		&i.RedirectUris,
		&i.GrantTypes,
		&i.ResponseTypes,
		&i.TokenEndpointAuthMethod,
		&i.Scope,
		&i.JwksUri,
		&i.Jwks,
		&i.TlsClientAuthSubjectDn,
		&i.IDTokenSignedResponseAlg,
		&i.RequirePushedAuthorizationRequests,
		&i.DpopBoundAccessTokens,
		&i.FapiProfile,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FirstParty,
	)
	return &i, err
}

const listClientsByTenant = `-- name: ListClientsByTenant :many
SELECT tenant_id, client_id, client_secret_hash, client_name, client_type, redirect_uris,
  grant_types, response_types, token_endpoint_auth_method, scope, jwks_uri, jwks,
  tls_client_auth_subject_dn, id_token_signed_response_alg,
  require_pushed_authorization_requests, dpop_bound_access_tokens, fapi_profile,
  created_at, updated_at, first_party
FROM clients
WHERE tenant_id = $1
ORDER BY created_at
`

func (q *Queries) ListClientsByTenant(ctx context.Context, tenantID string) ([]*Client, error) {
	rows, err := q.db.Query(ctx, listClientsByTenant, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*Client
	for rows.Next() {
		var i Client
		if err := rows.Scan(
			&i.TenantID,
			&i.ClientID,
			&i.ClientSecretHash,
			&i.ClientName,
			&i.ClientType,
			&i.RedirectUris,
			&i.GrantTypes,
			&i.ResponseTypes,
			&i.TokenEndpointAuthMethod,
			&i.Scope,
			&i.JwksUri,
			&i.Jwks,
			&i.TlsClientAuthSubjectDn,
			&i.IDTokenSignedResponseAlg,
			&i.RequirePushedAuthorizationRequests,
			&i.DpopBoundAccessTokens,
			&i.FapiProfile,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.FirstParty,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertClient = `-- name: UpsertClient :exec
INSERT INTO clients (
  tenant_id, client_id, client_secret_hash, client_name, client_type, redirect_uris,
  grant_types, response_types, token_endpoint_auth_method, scope, jwks_uri, jwks,
  tls_client_auth_subject_dn, id_token_signed_response_alg,
  require_pushed_authorization_requests, dpop_bound_access_tokens, fapi_profile,
  created_at, updated_at, first_party
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19, $20)
ON CONFLICT (client_id) DO UPDATE SET
  client_secret_hash = COALESCE(EXCLUDED.client_secret_hash, clients.client_secret_hash),
  client_name = EXCLUDED.client_name,
  client_type = EXCLUDED.client_type,
  redirect_uris = EXCLUDED.redirect_uris,
  grant_types = EXCLUDED.grant_types,
  response_types = EXCLUDED.response_types,
  token_endpoint_auth_method = EXCLUDED.token_endpoint_auth_method,
  scope = EXCLUDED.scope,
  jwks_uri = EXCLUDED.jwks_uri,
  jwks = EXCLUDED.jwks,
  tls_client_auth_subject_dn = EXCLUDED.tls_client_auth_subject_dn,
  id_token_signed_response_alg = EXCLUDED.id_token_signed_response_alg,
  require_pushed_authorization_requests = EXCLUDED.require_pushed_authorization_requests,
  dpop_bound_access_tokens = EXCLUDED.dpop_bound_access_tokens,
  fapi_profile = EXCLUDED.fapi_profile,
  first_party = EXCLUDED.first_party,
  updated_at = EXCLUDED.updated_at
`

type UpsertClientParams struct {
	TenantID                           string
	ClientID                           string
	ClientSecretHash                   pgtype.Text
	ClientName                         pgtype.Text
	ClientType                         string
	RedirectUris                       []byte
	GrantTypes                         []byte
	ResponseTypes                      []byte
	TokenEndpointAuthMethod            string
	Scope                              string
	JwksUri                            pgtype.Text
	Jwks                               []byte
	TlsClientAuthSubjectDn             pgtype.Text
	IDTokenSignedResponseAlg           string
	RequirePushedAuthorizationRequests bool
	DpopBoundAccessTokens              bool
	FapiProfile                        string
	CreatedAt                          time.Time
	UpdatedAt                          time.Time
	FirstParty                         bool
}

func (q *Queries) UpsertClient(ctx context.Context, arg UpsertClientParams) error {
	_, err := q.db.Exec(ctx, upsertClient,
		arg.TenantID,
		arg.ClientID,
		arg.ClientSecretHash,
		arg.ClientName,
		arg.ClientType,
		arg.RedirectUris,
		arg.GrantTypes,
		arg.ResponseTypes,
		arg.TokenEndpointAuthMethod,
		arg.Scope,
		arg.JwksUri,
		arg.Jwks,
		arg.TlsClientAuthSubjectDn,
		arg.IDTokenSignedResponseAlg,
		arg.RequirePushedAuthorizationRequests,
		arg.DpopBoundAccessTokens,
		arg.FapiProfile,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.FirstParty,
	)
	return err
}
