// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"context"
)

type Querier interface {
	DeleteAuthorizationDetailType(ctx context.Context, arg DeleteAuthorizationDetailTypeParams) error
	DeleteClient(ctx context.Context, arg DeleteClientParams) error
	DeleteConsentsForSub(ctx context.Context, userID string) error
	GetAuthorizationDetailType(ctx context.Context, arg GetAuthorizationDetailTypeParams) (*AuthorizationDetailType, error)
	GetClientByID(ctx context.Context, arg GetClientByIDParams) (*Client, error)
	GetConsent(ctx context.Context, arg GetConsentParams) (*Consent, error)
	ListAuthorizationDetailTypesByTenant(ctx context.Context, tenantID string) ([]*AuthorizationDetailType, error)
	ListClientsByTenant(ctx context.Context, tenantID string) ([]*Client, error)
	ListConsentsByTenant(ctx context.Context, tenantID string) ([]*Consent, error)
	RevokeConsent(ctx context.Context, arg RevokeConsentParams) error
	UpsertAuthorizationDetailType(ctx context.Context, arg UpsertAuthorizationDetailTypeParams) error
	UpsertClient(ctx context.Context, arg UpsertClientParams) error
	UpsertConsent(ctx context.Context, arg UpsertConsentParams) error
}

var _ Querier = (*Queries)(nil)
