// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: refresh_tokens.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteRefreshTokensForSub = `-- name: DeleteRefreshTokensForSub :exec
DELETE FROM refresh_tokens
WHERE user_id = $1
`

func (q *Queries) DeleteRefreshTokensForSub(ctx context.Context, userID string) error {
	_, err := q.db.Exec(ctx, deleteRefreshTokensForSub, userID)
	return err
}

const getRefreshTokenByHash = `-- name: GetRefreshTokenByHash :one
SELECT id::text, hash, family_id::text, COALESCE(parent_id::text, '') AS parent_id, client_id, user_id,
  scopes, issued_at, expires_at, absolute_expires_at, revoked, rotated, sender_constraint,
  COALESCE(sid::text, '') AS sid
FROM refresh_tokens
WHERE hash = $1
`

type GetRefreshTokenByHashRow struct {
	ID                string
	Hash              string
	FamilyID          string
	ParentID          interface{}
	ClientID          string
	UserID            string
	Scopes            []byte
	IssuedAt          time.Time
	ExpiresAt         time.Time
	AbsoluteExpiresAt time.Time
	Revoked           bool
	Rotated           bool
	SenderConstraint  []byte
	Sid               interface{}
}

func (q *Queries) GetRefreshTokenByHash(ctx context.Context, hash string) (*GetRefreshTokenByHashRow, error) {
	row := q.db.QueryRow(ctx, getRefreshTokenByHash, hash)
	var i GetRefreshTokenByHashRow
	err := row.Scan(
		&i.ID,
		&i.Hash,
		&i.FamilyID,
		&i.ParentID,
		&i.ClientID,
		&i.UserID,
		&i.Scopes,
		&i.IssuedAt,
		&i.ExpiresAt,
		&i.AbsoluteExpiresAt,
		&i.Revoked,
		&i.Rotated,
		&i.SenderConstraint,
		&i.Sid,
	)
	return &i, err
}

const getRefreshTokenRotationState = `-- name: GetRefreshTokenRotationState :one
SELECT rotated, revoked
FROM refresh_tokens
WHERE id = $1
FOR UPDATE
`

type GetRefreshTokenRotationStateRow struct {
	Rotated bool
	Revoked bool
}

func (q *Queries) GetRefreshTokenRotationState(ctx context.Context, id string) (*GetRefreshTokenRotationStateRow, error) {
	row := q.db.QueryRow(ctx, getRefreshTokenRotationState, id)
	var i GetRefreshTokenRotationStateRow
	err := row.Scan(&i.Rotated, &i.Revoked)
	return &i, err
}

const insertRefreshToken = `-- name: InsertRefreshToken :exec
INSERT INTO refresh_tokens (
  id, hash, family_id, parent_id, client_id, user_id, scopes, issued_at,
  expires_at, absolute_expires_at, revoked, rotated, sender_constraint, sid
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, NULLIF($13, 'null')::jsonb, $14
)
`

type InsertRefreshTokenParams struct {
	ID                string
	Hash              string
	FamilyID          string
	ParentID          pgtype.UUID
	ClientID          string
	UserID            string
	Scopes            []byte
	IssuedAt          time.Time
	ExpiresAt         time.Time
	AbsoluteExpiresAt time.Time
	Revoked           bool
	Rotated           bool
	Column13          interface{}
	Sid               pgtype.UUID
}

func (q *Queries) InsertRefreshToken(ctx context.Context, arg InsertRefreshTokenParams) error {
	_, err := q.db.Exec(ctx, insertRefreshToken,
		arg.ID,
		arg.Hash,
		arg.FamilyID,
		arg.ParentID,
		arg.ClientID,
		arg.UserID,
		arg.Scopes,
		arg.IssuedAt,
		arg.ExpiresAt,
		arg.AbsoluteExpiresAt,
		arg.Revoked,
		arg.Rotated,
		arg.Column13,
		arg.Sid,
	)
	return err
}

const markRefreshTokenRotated = `-- name: MarkRefreshTokenRotated :exec
UPDATE refresh_tokens
SET rotated = TRUE, updated_at = now()
WHERE id = $1
`

func (q *Queries) MarkRefreshTokenRotated(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, markRefreshTokenRotated, id)
	return err
}

const revokeRefreshTokenFamily = `-- name: RevokeRefreshTokenFamily :exec
UPDATE refresh_tokens
SET revoked = TRUE, updated_at = now()
WHERE family_id = $1
`

func (q *Queries) RevokeRefreshTokenFamily(ctx context.Context, familyID string) error {
	_, err := q.db.Exec(ctx, revokeRefreshTokenFamily, familyID)
	return err
}

const revokeRefreshTokensBySid = `-- name: RevokeRefreshTokensBySid :exec
UPDATE refresh_tokens
SET revoked = TRUE, updated_at = now()
WHERE sid = $1
`

func (q *Queries) RevokeRefreshTokensBySid(ctx context.Context, sid pgtype.UUID) error {
	_, err := q.db.Exec(ctx, revokeRefreshTokensBySid, sid)
	return err
}
