// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db_postgres

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type MfaEnrollmentBypass struct {
	ID         string
	TenantID   string
	UserID     string
	IssuedBy   string
	IssuedAt   time.Time
	ExpiresAt  time.Time
	ConsumedAt pgtype.Timestamptz
	RevokedAt  pgtype.Timestamptz
	ExpiredAt  pgtype.Timestamptz
}
