// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: access_token_denylist.sql

package db_postgres

import (
	"context"
	"time"
)

const addOauth2AccessTokenDenylist = `-- name: AddOauth2AccessTokenDenylist :exec
INSERT INTO oauth2_access_token_denylist (tenant_id, jti, expires_at)
VALUES ($1, $2, $3)
ON CONFLICT (tenant_id, jti) DO NOTHING
`

type AddOauth2AccessTokenDenylistParams struct {
	TenantID  string
	Jti       string
	ExpiresAt time.Time
}

// 失効マーカーを追加する。同一 jti は同一トークンを指し exp も決定的なので冪等 (DO NOTHING)。
func (q *Queries) AddOauth2AccessTokenDenylist(ctx context.Context, arg AddOauth2AccessTokenDenylistParams) error {
	_, err := q.db.Exec(ctx, addOauth2AccessTokenDenylist, arg.TenantID, arg.Jti, arg.ExpiresAt)
	return err
}

const deleteExpiredOauth2AccessTokenDenylistBatch = `-- name: DeleteExpiredOauth2AccessTokenDenylistBatch :execrows
DELETE FROM oauth2_access_token_denylist AS o
WHERE (o.tenant_id, o.jti) IN (
    SELECT s.tenant_id, s.jti
    FROM oauth2_access_token_denylist AS s
    WHERE s.expires_at < $1
    LIMIT $2
)
`

type DeleteExpiredOauth2AccessTokenDenylistBatchParams struct {
	Cutoff     time.Time
	BatchLimit int32
}

func (q *Queries) DeleteExpiredOauth2AccessTokenDenylistBatch(ctx context.Context, arg DeleteExpiredOauth2AccessTokenDenylistBatchParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredOauth2AccessTokenDenylistBatch, arg.Cutoff, arg.BatchLimit)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const isOauth2AccessTokenRevoked = `-- name: IsOauth2AccessTokenRevoked :one
SELECT EXISTS(
    SELECT 1 FROM oauth2_access_token_denylist
    WHERE tenant_id = $1 AND jti = $2 AND expires_at > $3
)
`

type IsOauth2AccessTokenRevokedParams struct {
	TenantID string
	Jti      string
	Now      time.Time
}

// 期限切れマーカーは revoked とみなさない (正しさは expires_at > now が担保、GC は空間回収のみ)。
func (q *Queries) IsOauth2AccessTokenRevoked(ctx context.Context, arg IsOauth2AccessTokenRevokedParams) (bool, error) {
	row := q.db.QueryRow(ctx, isOauth2AccessTokenRevoked, arg.TenantID, arg.Jti, arg.Now)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
