// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: approval_request_store.sql

package db_postgres

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const consumeApprovalRequest = `-- name: ConsumeApprovalRequest :one
UPDATE oauth2_approval_requests
SET state = 'consumed',
    payload = jsonb_set(
        jsonb_set(payload, '{state}', '"consumed"'::jsonb),
        '{consumed_at}', to_jsonb($1::timestamptz)
    ),
    updated_at = now()
WHERE auth_req_id_hash = $2 AND tenant_id = $3
  AND state = 'approved' AND expires_at > $1
RETURNING payload, state, interval_seconds, last_polled_at
`

type ConsumeApprovalRequestParams struct {
	ConsumedAt    time.Time
	AuthReqIDHash string
	TenantID      string
}

type ConsumeApprovalRequestRow struct {
	Payload         []byte
	State           string
	IntervalSeconds int32
	LastPolledAt    pgtype.Timestamptz
}

func (q *Queries) ConsumeApprovalRequest(ctx context.Context, arg ConsumeApprovalRequestParams) (*ConsumeApprovalRequestRow, error) {
	row := q.db.QueryRow(ctx, consumeApprovalRequest, arg.ConsumedAt, arg.AuthReqIDHash, arg.TenantID)
	var i ConsumeApprovalRequestRow
	err := row.Scan(
		&i.Payload,
		&i.State,
		&i.IntervalSeconds,
		&i.LastPolledAt,
	)
	return &i, err
}

const decideApprovalRequest = `-- name: DecideApprovalRequest :one
UPDATE oauth2_approval_requests
SET state = $1,
    payload = jsonb_set(
        jsonb_set(payload, '{state}', to_jsonb($1::text)),
        '{decided_at}', to_jsonb($2::timestamptz)
    ),
    updated_at = now()
WHERE id = $3 AND tenant_id = $4 AND user_id = $5
  AND state = 'pending' AND expires_at > $2
RETURNING payload, state, interval_seconds, last_polled_at
`

type DecideApprovalRequestParams struct {
	NextState string
	DecidedAt time.Time
	ID        string
	TenantID  string
	UserID    string
}

type DecideApprovalRequestRow struct {
	Payload         []byte
	State           string
	IntervalSeconds int32
	LastPolledAt    pgtype.Timestamptz
}

func (q *Queries) DecideApprovalRequest(ctx context.Context, arg DecideApprovalRequestParams) (*DecideApprovalRequestRow, error) {
	row := q.db.QueryRow(ctx, decideApprovalRequest,
		arg.NextState,
		arg.DecidedAt,
		arg.ID,
		arg.TenantID,
		arg.UserID,
	)
	var i DecideApprovalRequestRow
	err := row.Scan(
		&i.Payload,
		&i.State,
		&i.IntervalSeconds,
		&i.LastPolledAt,
	)
	return &i, err
}

const deleteApprovalRequestsForUser = `-- name: DeleteApprovalRequestsForUser :exec
DELETE FROM oauth2_approval_requests WHERE tenant_id = $1 AND user_id = $2
`

type DeleteApprovalRequestsForUserParams struct {
	TenantID string
	UserID   string
}

func (q *Queries) DeleteApprovalRequestsForUser(ctx context.Context, arg DeleteApprovalRequestsForUserParams) error {
	_, err := q.db.Exec(ctx, deleteApprovalRequestsForUser, arg.TenantID, arg.UserID)
	return err
}

const deleteExpiredApprovalRequestsBatch = `-- name: DeleteExpiredApprovalRequestsBatch :execrows
DELETE FROM oauth2_approval_requests AS o
WHERE o.id IN (
    SELECT s.id FROM oauth2_approval_requests AS s WHERE s.expires_at < $1 LIMIT $2
)
`

type DeleteExpiredApprovalRequestsBatchParams struct {
	Cutoff     time.Time
	BatchLimit int32
}

func (q *Queries) DeleteExpiredApprovalRequestsBatch(ctx context.Context, arg DeleteExpiredApprovalRequestsBatchParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredApprovalRequestsBatch, arg.Cutoff, arg.BatchLimit)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const expireApprovalRequest = `-- name: ExpireApprovalRequest :one
UPDATE oauth2_approval_requests
SET state = 'expired',
    payload = jsonb_set(payload, '{state}', '"expired"'::jsonb),
    updated_at = now()
WHERE auth_req_id_hash = $1 AND tenant_id = $2
  AND state IN ('pending', 'approved') AND expires_at <= $3
RETURNING payload, state, interval_seconds, last_polled_at
`

type ExpireApprovalRequestParams struct {
	AuthReqIDHash string
	TenantID      string
	ExpiredAt     time.Time
}

type ExpireApprovalRequestRow struct {
	Payload         []byte
	State           string
	IntervalSeconds int32
	LastPolledAt    pgtype.Timestamptz
}

func (q *Queries) ExpireApprovalRequest(ctx context.Context, arg ExpireApprovalRequestParams) (*ExpireApprovalRequestRow, error) {
	row := q.db.QueryRow(ctx, expireApprovalRequest, arg.AuthReqIDHash, arg.TenantID, arg.ExpiredAt)
	var i ExpireApprovalRequestRow
	err := row.Scan(
		&i.Payload,
		&i.State,
		&i.IntervalSeconds,
		&i.LastPolledAt,
	)
	return &i, err
}

const findApprovalRequestByAuthReqIDHash = `-- name: FindApprovalRequestByAuthReqIDHash :one
SELECT payload, state, interval_seconds, last_polled_at FROM oauth2_approval_requests
WHERE auth_req_id_hash = $1 AND tenant_id = $2
`

type FindApprovalRequestByAuthReqIDHashParams struct {
	AuthReqIDHash string
	TenantID      string
}

type FindApprovalRequestByAuthReqIDHashRow struct {
	Payload         []byte
	State           string
	IntervalSeconds int32
	LastPolledAt    pgtype.Timestamptz
}

func (q *Queries) FindApprovalRequestByAuthReqIDHash(ctx context.Context, arg FindApprovalRequestByAuthReqIDHashParams) (*FindApprovalRequestByAuthReqIDHashRow, error) {
	row := q.db.QueryRow(ctx, findApprovalRequestByAuthReqIDHash, arg.AuthReqIDHash, arg.TenantID)
	var i FindApprovalRequestByAuthReqIDHashRow
	err := row.Scan(
		&i.Payload,
		&i.State,
		&i.IntervalSeconds,
		&i.LastPolledAt,
	)
	return &i, err
}

const findApprovalRequestByID = `-- name: FindApprovalRequestByID :one
SELECT payload, state, interval_seconds, last_polled_at FROM oauth2_approval_requests
WHERE id = $1 AND tenant_id = $2
`

type FindApprovalRequestByIDParams struct {
	ID       string
	TenantID string
}

type FindApprovalRequestByIDRow struct {
	Payload         []byte
	State           string
	IntervalSeconds int32
	LastPolledAt    pgtype.Timestamptz
}

func (q *Queries) FindApprovalRequestByID(ctx context.Context, arg FindApprovalRequestByIDParams) (*FindApprovalRequestByIDRow, error) {
	row := q.db.QueryRow(ctx, findApprovalRequestByID, arg.ID, arg.TenantID)
	var i FindApprovalRequestByIDRow
	err := row.Scan(
		&i.Payload,
		&i.State,
		&i.IntervalSeconds,
		&i.LastPolledAt,
	)
	return &i, err
}

const listPendingApprovalRequestsForUser = `-- name: ListPendingApprovalRequestsForUser :many
SELECT payload, state, interval_seconds, last_polled_at FROM oauth2_approval_requests
WHERE tenant_id = $1 AND user_id = $2 AND state = 'pending' AND expires_at > $3
ORDER BY created_at ASC
`

type ListPendingApprovalRequestsForUserParams struct {
	TenantID string
	UserID   string
	Now      time.Time
}

type ListPendingApprovalRequestsForUserRow struct {
	Payload         []byte
	State           string
	IntervalSeconds int32
	LastPolledAt    pgtype.Timestamptz
}

func (q *Queries) ListPendingApprovalRequestsForUser(ctx context.Context, arg ListPendingApprovalRequestsForUserParams) ([]*ListPendingApprovalRequestsForUserRow, error) {
	rows, err := q.db.Query(ctx, listPendingApprovalRequestsForUser, arg.TenantID, arg.UserID, arg.Now)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*ListPendingApprovalRequestsForUserRow
	for rows.Next() {
		var i ListPendingApprovalRequestsForUserRow
		if err := rows.Scan(
			&i.Payload,
			&i.State,
			&i.IntervalSeconds,
			&i.LastPolledAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordApprovalRequestPoll = `-- name: RecordApprovalRequestPoll :one
WITH current_request AS (
    SELECT id,
        state = 'pending' AND last_polled_at IS NOT NULL
            AND $1 < last_polled_at + make_interval(secs => interval_seconds) AS too_fast
    FROM oauth2_approval_requests
    WHERE oauth2_approval_requests.auth_req_id_hash = $2
      AND oauth2_approval_requests.tenant_id = $3
    FOR UPDATE
)
UPDATE oauth2_approval_requests AS request
SET interval_seconds = CASE
        WHEN current_request.too_fast THEN request.interval_seconds + 5
        ELSE request.interval_seconds
    END,
    last_polled_at = CASE WHEN request.state = 'pending' THEN $1 ELSE request.last_polled_at END,
    updated_at = now()
FROM current_request
WHERE request.id = current_request.id
RETURNING request.payload, request.state, request.interval_seconds, request.last_polled_at,
    current_request.too_fast
`

type RecordApprovalRequestPollParams struct {
	Now           pgtype.Timestamptz
	AuthReqIDHash string
	TenantID      string
}

type RecordApprovalRequestPollRow struct {
	Payload         []byte
	State           string
	IntervalSeconds int32
	LastPolledAt    pgtype.Timestamptz
	TooFast         pgtype.Bool
}

func (q *Queries) RecordApprovalRequestPoll(ctx context.Context, arg RecordApprovalRequestPollParams) (*RecordApprovalRequestPollRow, error) {
	row := q.db.QueryRow(ctx, recordApprovalRequestPoll, arg.Now, arg.AuthReqIDHash, arg.TenantID)
	var i RecordApprovalRequestPollRow
	err := row.Scan(
		&i.Payload,
		&i.State,
		&i.IntervalSeconds,
		&i.LastPolledAt,
		&i.TooFast,
	)
	return &i, err
}

const saveApprovalRequest = `-- name: SaveApprovalRequest :exec
INSERT INTO oauth2_approval_requests (id, tenant_id, auth_req_id_hash, client_id, user_id, state, interval_seconds, last_polled_at, expires_at, payload)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
`

type SaveApprovalRequestParams struct {
	ID              string
	TenantID        string
	AuthReqIDHash   string
	ClientID        string
	UserID          string
	State           string
	IntervalSeconds int32
	LastPolledAt    pgtype.Timestamptz
	ExpiresAt       time.Time
	Payload         []byte
}

func (q *Queries) SaveApprovalRequest(ctx context.Context, arg SaveApprovalRequestParams) error {
	_, err := q.db.Exec(ctx, saveApprovalRequest,
		arg.ID,
		arg.TenantID,
		arg.AuthReqIDHash,
		arg.ClientID,
		arg.UserID,
		arg.State,
		arg.IntervalSeconds,
		arg.LastPolledAt,
		arg.ExpiresAt,
		arg.Payload,
	)
	return err
}
