// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: authorization_request_store.sql

package db_postgres

import (
	"context"
	"time"
)

const deleteExpiredAuthorizationRequestsBatch = `-- name: DeleteExpiredAuthorizationRequestsBatch :execrows
DELETE FROM oauth2_authorization_requests AS o
WHERE o.id IN (
    SELECT s.id FROM oauth2_authorization_requests AS s WHERE s.expires_at < $1 LIMIT $2
)
`

type DeleteExpiredAuthorizationRequestsBatchParams struct {
	Cutoff     time.Time
	BatchLimit int32
}

func (q *Queries) DeleteExpiredAuthorizationRequestsBatch(ctx context.Context, arg DeleteExpiredAuthorizationRequestsBatchParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredAuthorizationRequestsBatch, arg.Cutoff, arg.BatchLimit)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const findAuthorizationRequest = `-- name: FindAuthorizationRequest :one
SELECT payload FROM oauth2_authorization_requests
WHERE id = $1 AND tenant_id = $2
`

type FindAuthorizationRequestParams struct {
	ID       string
	TenantID string
}

// 期限フィルタなし (parity)。tenant_id は fail-closed 述語。
func (q *Queries) FindAuthorizationRequest(ctx context.Context, arg FindAuthorizationRequestParams) ([]byte, error) {
	row := q.db.QueryRow(ctx, findAuthorizationRequest, arg.ID, arg.TenantID)
	var payload []byte
	err := row.Scan(&payload)
	return payload, err
}

const lockAuthorizationRequest = `-- name: LockAuthorizationRequest :one
SELECT payload FROM oauth2_authorization_requests
WHERE id = $1 AND tenant_id = $2
FOR UPDATE
`

type LockAuthorizationRequestParams struct {
	ID       string
	TenantID string
}

// tx 内の read-modify-write を直列化するための行ロック取得 (Valkey WATCH 楽観ロックの写し)。
func (q *Queries) LockAuthorizationRequest(ctx context.Context, arg LockAuthorizationRequestParams) ([]byte, error) {
	row := q.db.QueryRow(ctx, lockAuthorizationRequest, arg.ID, arg.TenantID)
	var payload []byte
	err := row.Scan(&payload)
	return payload, err
}

const saveAuthorizationRequest = `-- name: SaveAuthorizationRequest :exec
INSERT INTO oauth2_authorization_requests (id, tenant_id, expires_at, payload)
VALUES ($1, $2, $3, $4)
ON CONFLICT (id) DO UPDATE
    SET tenant_id = EXCLUDED.tenant_id, expires_at = EXCLUDED.expires_at,
        payload = EXCLUDED.payload, updated_at = now()
`

type SaveAuthorizationRequestParams struct {
	ID        string
	TenantID  string
	ExpiresAt time.Time
	Payload   []byte
}

func (q *Queries) SaveAuthorizationRequest(ctx context.Context, arg SaveAuthorizationRequestParams) error {
	_, err := q.db.Exec(ctx, saveAuthorizationRequest,
		arg.ID,
		arg.TenantID,
		arg.ExpiresAt,
		arg.Payload,
	)
	return err
}

const updateAuthorizationRequestPayload = `-- name: UpdateAuthorizationRequestPayload :exec
UPDATE oauth2_authorization_requests
SET payload = $1, updated_at = now()
WHERE id = $2 AND tenant_id = $3
`

type UpdateAuthorizationRequestPayloadParams struct {
	Payload  []byte
	ID       string
	TenantID string
}

func (q *Queries) UpdateAuthorizationRequestPayload(ctx context.Context, arg UpdateAuthorizationRequestPayloadParams) error {
	_, err := q.db.Exec(ctx, updateAuthorizationRequestPayload, arg.Payload, arg.ID, arg.TenantID)
	return err
}
