// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: consents.sql

package db_postgres

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteConsentsForSub = `-- name: DeleteConsentsForSub :exec
DELETE FROM consents WHERE user_id = $1
`

func (q *Queries) DeleteConsentsForSub(ctx context.Context, userID string) error {
	_, err := q.db.Exec(ctx, deleteConsentsForSub, userID)
	return err
}

const getConsent = `-- name: GetConsent :one
SELECT user_id, client_id, scopes, created_at, updated_at, granted_at, expires_at, revoked_at
FROM consents
WHERE user_id = $1 AND client_id = $2
`

type GetConsentParams struct {
	UserID   string
	ClientID string
}

func (q *Queries) GetConsent(ctx context.Context, arg GetConsentParams) (*Consent, error) {
	row := q.db.QueryRow(ctx, getConsent, arg.UserID, arg.ClientID)
	var i Consent
	err := row.Scan(
		&i.UserID,
		&i.ClientID,
		&i.Scopes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.GrantedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
	)
	return &i, err
}

const listConsentsByTenant = `-- name: ListConsentsByTenant :many
SELECT c.user_id, c.client_id, c.scopes, c.created_at, c.updated_at, c.granted_at, c.expires_at, c.revoked_at
FROM consents c
JOIN users u ON c.user_id = u.id
WHERE u.tenant_id = $1
ORDER BY c.user_id, c.client_id
`

func (q *Queries) ListConsentsByTenant(ctx context.Context, tenantID string) ([]*Consent, error) {
	rows, err := q.db.Query(ctx, listConsentsByTenant, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*Consent
	for rows.Next() {
		var i Consent
		if err := rows.Scan(
			&i.UserID,
			&i.ClientID,
			&i.Scopes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.GrantedAt,
			&i.ExpiresAt,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeConsent = `-- name: RevokeConsent :exec
UPDATE consents SET revoked_at = now(), updated_at = now()
WHERE user_id = $1 AND client_id = $2 AND revoked_at IS NULL
`

type RevokeConsentParams struct {
	UserID   string
	ClientID string
}

func (q *Queries) RevokeConsent(ctx context.Context, arg RevokeConsentParams) error {
	_, err := q.db.Exec(ctx, revokeConsent, arg.UserID, arg.ClientID)
	return err
}

const upsertConsent = `-- name: UpsertConsent :exec
INSERT INTO consents (user_id, client_id, scopes, granted_at, expires_at, revoked_at)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (user_id, client_id) DO UPDATE SET
  scopes = EXCLUDED.scopes,
  granted_at = EXCLUDED.granted_at,
  expires_at = EXCLUDED.expires_at,
  revoked_at = EXCLUDED.revoked_at,
  updated_at = now()
`

type UpsertConsentParams struct {
	UserID    string
	ClientID  string
	Scopes    []byte
	GrantedAt time.Time
	ExpiresAt time.Time
	RevokedAt pgtype.Timestamptz
}

func (q *Queries) UpsertConsent(ctx context.Context, arg UpsertConsentParams) error {
	_, err := q.db.Exec(ctx, upsertConsent,
		arg.UserID,
		arg.ClientID,
		arg.Scopes,
		arg.GrantedAt,
		arg.ExpiresAt,
		arg.RevokedAt,
	)
	return err
}
