// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: device_code_store.sql

package db_postgres

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteDeviceCodesForUser = `-- name: DeleteDeviceCodesForUser :exec
DELETE FROM oauth2_device_codes WHERE tenant_id = $1 AND user_id = $2
`

type DeleteDeviceCodesForUserParams struct {
	TenantID string
	UserID   pgtype.UUID
}

func (q *Queries) DeleteDeviceCodesForUser(ctx context.Context, arg DeleteDeviceCodesForUserParams) error {
	_, err := q.db.Exec(ctx, deleteDeviceCodesForUser, arg.TenantID, arg.UserID)
	return err
}

const deleteExpiredDeviceCodesBatch = `-- name: DeleteExpiredDeviceCodesBatch :execrows
DELETE FROM oauth2_device_codes AS o
WHERE o.device_code_hash IN (
    SELECT s.device_code_hash FROM oauth2_device_codes AS s WHERE s.expires_at < $1 LIMIT $2
)
`

type DeleteExpiredDeviceCodesBatchParams struct {
	Cutoff     time.Time
	BatchLimit int32
}

func (q *Queries) DeleteExpiredDeviceCodesBatch(ctx context.Context, arg DeleteExpiredDeviceCodesBatchParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredDeviceCodesBatch, arg.Cutoff, arg.BatchLimit)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const exchangeDeviceCode = `-- name: ExchangeDeviceCode :one
UPDATE oauth2_device_codes
SET state = 'exchanged', updated_at = now()
WHERE device_code_hash = $1 AND tenant_id = $2 AND state = 'approved'
RETURNING payload, state
`

type ExchangeDeviceCodeParams struct {
	DeviceCodeHash string
	TenantID       string
}

type ExchangeDeviceCodeRow struct {
	Payload []byte
	State   string
}

// 単発 exchange の CAS。state='approved' の行だけを exchanged にして 1 行返す。
func (q *Queries) ExchangeDeviceCode(ctx context.Context, arg ExchangeDeviceCodeParams) (*ExchangeDeviceCodeRow, error) {
	row := q.db.QueryRow(ctx, exchangeDeviceCode, arg.DeviceCodeHash, arg.TenantID)
	var i ExchangeDeviceCodeRow
	err := row.Scan(&i.Payload, &i.State)
	return &i, err
}

const findDeviceCodeByHash = `-- name: FindDeviceCodeByHash :one
SELECT payload, state FROM oauth2_device_codes
WHERE device_code_hash = $1 AND tenant_id = $2
`

type FindDeviceCodeByHashParams struct {
	DeviceCodeHash string
	TenantID       string
}

type FindDeviceCodeByHashRow struct {
	Payload []byte
	State   string
}

// 期限フィルタなし (parity)。state を read で payload に overlay する。
func (q *Queries) FindDeviceCodeByHash(ctx context.Context, arg FindDeviceCodeByHashParams) (*FindDeviceCodeByHashRow, error) {
	row := q.db.QueryRow(ctx, findDeviceCodeByHash, arg.DeviceCodeHash, arg.TenantID)
	var i FindDeviceCodeByHashRow
	err := row.Scan(&i.Payload, &i.State)
	return &i, err
}

const findDeviceCodeByUserCode = `-- name: FindDeviceCodeByUserCode :one
SELECT payload, state FROM oauth2_device_codes
WHERE user_code = $1 AND tenant_id = $2
`

type FindDeviceCodeByUserCodeParams struct {
	UserCode string
	TenantID string
}

type FindDeviceCodeByUserCodeRow struct {
	Payload []byte
	State   string
}

func (q *Queries) FindDeviceCodeByUserCode(ctx context.Context, arg FindDeviceCodeByUserCodeParams) (*FindDeviceCodeByUserCodeRow, error) {
	row := q.db.QueryRow(ctx, findDeviceCodeByUserCode, arg.UserCode, arg.TenantID)
	var i FindDeviceCodeByUserCodeRow
	err := row.Scan(&i.Payload, &i.State)
	return &i, err
}

const saveDeviceCode = `-- name: SaveDeviceCode :exec
INSERT INTO oauth2_device_codes (device_code_hash, tenant_id, user_code, user_id, state, expires_at, payload)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (device_code_hash) DO UPDATE
    SET tenant_id = EXCLUDED.tenant_id, user_code = EXCLUDED.user_code, user_id = EXCLUDED.user_id,
        state = EXCLUDED.state, expires_at = EXCLUDED.expires_at, payload = EXCLUDED.payload, updated_at = now()
`

type SaveDeviceCodeParams struct {
	DeviceCodeHash string
	TenantID       string
	UserCode       string
	UserID         pgtype.UUID
	State          string
	ExpiresAt      time.Time
	Payload        []byte
}

// Save / Update 共通の upsert。device_code_hash を PK、(tenant_id,user_code) を UNIQUE 鍵に持つ。
func (q *Queries) SaveDeviceCode(ctx context.Context, arg SaveDeviceCodeParams) error {
	_, err := q.db.Exec(ctx, saveDeviceCode,
		arg.DeviceCodeHash,
		arg.TenantID,
		arg.UserCode,
		arg.UserID,
		arg.State,
		arg.ExpiresAt,
		arg.Payload,
	)
	return err
}
