// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: logout.sql

package db_postgres

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const findLogoutNotificationByID = `-- name: FindLogoutNotificationByID :one
SELECT id, tenant_id, sid, client_id, logout_token_jti, target_uri, state,
       attempts, last_error, job_id, created_at, delivered_at
FROM oauth2_logout_notifications
WHERE tenant_id = $1 AND id = $2
`

type FindLogoutNotificationByIDParams struct {
	TenantID string
	ID       string
}

func (q *Queries) FindLogoutNotificationByID(ctx context.Context, arg FindLogoutNotificationByIDParams) (*Oauth2LogoutNotification, error) {
	row := q.db.QueryRow(ctx, findLogoutNotificationByID, arg.TenantID, arg.ID)
	var i Oauth2LogoutNotification
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Sid,
		&i.ClientID,
		&i.LogoutTokenJti,
		&i.TargetUri,
		&i.State,
		&i.Attempts,
		&i.LastError,
		&i.JobID,
		&i.CreatedAt,
		&i.DeliveredAt,
	)
	return &i, err
}

const listClientSessionsBySid = `-- name: ListClientSessionsBySid :many
SELECT tenant_id, sid, client_id, first_issued_at, last_issued_at
FROM oauth2_client_sessions
WHERE tenant_id = $1 AND sid = $2
ORDER BY client_id
`

type ListClientSessionsBySidParams struct {
	TenantID string
	Sid      string
}

func (q *Queries) ListClientSessionsBySid(ctx context.Context, arg ListClientSessionsBySidParams) ([]*Oauth2ClientSession, error) {
	rows, err := q.db.Query(ctx, listClientSessionsBySid, arg.TenantID, arg.Sid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*Oauth2ClientSession
	for rows.Next() {
		var i Oauth2ClientSession
		if err := rows.Scan(
			&i.TenantID,
			&i.Sid,
			&i.ClientID,
			&i.FirstIssuedAt,
			&i.LastIssuedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const saveLogoutNotification = `-- name: SaveLogoutNotification :exec
INSERT INTO oauth2_logout_notifications (
    id, tenant_id, sid, client_id, logout_token_jti, target_uri, state,
    attempts, last_error, job_id, created_at, delivered_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12
)
ON CONFLICT (id) DO UPDATE SET
    state = EXCLUDED.state,
    attempts = EXCLUDED.attempts,
    last_error = EXCLUDED.last_error,
    job_id = EXCLUDED.job_id,
    delivered_at = EXCLUDED.delivered_at
`

type SaveLogoutNotificationParams struct {
	ID             string
	TenantID       string
	Sid            string
	ClientID       string
	LogoutTokenJti string
	TargetUri      string
	State          string
	Attempts       int64
	LastError      pgtype.Text
	JobID          pgtype.UUID
	CreatedAt      time.Time
	DeliveredAt    pgtype.Timestamptz
}

func (q *Queries) SaveLogoutNotification(ctx context.Context, arg SaveLogoutNotificationParams) error {
	_, err := q.db.Exec(ctx, saveLogoutNotification,
		arg.ID,
		arg.TenantID,
		arg.Sid,
		arg.ClientID,
		arg.LogoutTokenJti,
		arg.TargetUri,
		arg.State,
		arg.Attempts,
		arg.LastError,
		arg.JobID,
		arg.CreatedAt,
		arg.DeliveredAt,
	)
	return err
}

const upsertClientSession = `-- name: UpsertClientSession :exec
INSERT INTO oauth2_client_sessions (
  tenant_id, sid, client_id, first_issued_at, last_issued_at
) VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (tenant_id, sid, client_id) DO UPDATE SET
  last_issued_at = EXCLUDED.last_issued_at
`

type UpsertClientSessionParams struct {
	TenantID      string
	Sid           string
	ClientID      string
	FirstIssuedAt time.Time
	LastIssuedAt  time.Time
}

func (q *Queries) UpsertClientSession(ctx context.Context, arg UpsertClientSessionParams) error {
	_, err := q.db.Exec(ctx, upsertClientSession,
		arg.TenantID,
		arg.Sid,
		arg.ClientID,
		arg.FirstIssuedAt,
		arg.LastIssuedAt,
	)
	return err
}
