// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: mcp_resource_servers.sql

package db_postgres

import (
	"context"
	"time"
)

const deleteMcpResourceServer = `-- name: DeleteMcpResourceServer :exec
DELETE FROM mcp_resource_servers WHERE tenant_id = $1 AND resource_server_id = $2
`

type DeleteMcpResourceServerParams struct {
	TenantID         string
	ResourceServerID string
}

func (q *Queries) DeleteMcpResourceServer(ctx context.Context, arg DeleteMcpResourceServerParams) error {
	_, err := q.db.Exec(ctx, deleteMcpResourceServer, arg.TenantID, arg.ResourceServerID)
	return err
}

const getMcpResourceServer = `-- name: GetMcpResourceServer :one
SELECT tenant_id, resource_server_id, resource, name, scopes, state, created_at, updated_at
FROM mcp_resource_servers
WHERE tenant_id = $1 AND resource_server_id = $2
`

type GetMcpResourceServerParams struct {
	TenantID         string
	ResourceServerID string
}

func (q *Queries) GetMcpResourceServer(ctx context.Context, arg GetMcpResourceServerParams) (*McpResourceServer, error) {
	row := q.db.QueryRow(ctx, getMcpResourceServer, arg.TenantID, arg.ResourceServerID)
	var i McpResourceServer
	err := row.Scan(
		&i.TenantID,
		&i.ResourceServerID,
		&i.Resource,
		&i.Name,
		&i.Scopes,
		&i.State,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const getMcpResourceServerByResource = `-- name: GetMcpResourceServerByResource :one
SELECT tenant_id, resource_server_id, resource, name, scopes, state, created_at, updated_at
FROM mcp_resource_servers
WHERE tenant_id = $1 AND resource = $2
`

type GetMcpResourceServerByResourceParams struct {
	TenantID string
	Resource string
}

func (q *Queries) GetMcpResourceServerByResource(ctx context.Context, arg GetMcpResourceServerByResourceParams) (*McpResourceServer, error) {
	row := q.db.QueryRow(ctx, getMcpResourceServerByResource, arg.TenantID, arg.Resource)
	var i McpResourceServer
	err := row.Scan(
		&i.TenantID,
		&i.ResourceServerID,
		&i.Resource,
		&i.Name,
		&i.Scopes,
		&i.State,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const listMcpResourceServersByTenant = `-- name: ListMcpResourceServersByTenant :many
SELECT tenant_id, resource_server_id, resource, name, scopes, state, created_at, updated_at
FROM mcp_resource_servers
WHERE tenant_id = $1
ORDER BY resource
`

func (q *Queries) ListMcpResourceServersByTenant(ctx context.Context, tenantID string) ([]*McpResourceServer, error) {
	rows, err := q.db.Query(ctx, listMcpResourceServersByTenant, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*McpResourceServer
	for rows.Next() {
		var i McpResourceServer
		if err := rows.Scan(
			&i.TenantID,
			&i.ResourceServerID,
			&i.Resource,
			&i.Name,
			&i.Scopes,
			&i.State,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertMcpResourceServer = `-- name: UpsertMcpResourceServer :exec
INSERT INTO mcp_resource_servers (tenant_id, resource_server_id, resource, name, scopes, state, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
ON CONFLICT (resource_server_id) DO UPDATE SET
  name = EXCLUDED.name,
  scopes = EXCLUDED.scopes,
  state = EXCLUDED.state,
  updated_at = EXCLUDED.updated_at
`

type UpsertMcpResourceServerParams struct {
	TenantID         string
	ResourceServerID string
	Resource         string
	Name             string
	Scopes           []byte
	State            string
	CreatedAt        time.Time
	UpdatedAt        time.Time
}

func (q *Queries) UpsertMcpResourceServer(ctx context.Context, arg UpsertMcpResourceServerParams) error {
	_, err := q.db.Exec(ctx, upsertMcpResourceServer,
		arg.TenantID,
		arg.ResourceServerID,
		arg.Resource,
		arg.Name,
		arg.Scopes,
		arg.State,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}
