// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db_postgres

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type AuthorizationDetailType struct {
	TenantID        string
	Type            string
	Description     pgtype.Text
	Schema          []byte
	DisplayTemplate string
	State           string
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

type Consent struct {
	UserID    string
	ClientID  string
	Scopes    []byte
	CreatedAt time.Time
	UpdatedAt time.Time
	GrantedAt time.Time
	ExpiresAt time.Time
	RevokedAt pgtype.Timestamptz
}

type McpResourceServer struct {
	TenantID  string
	ID        string
	Resource  string
	Name      string
	Scopes    []byte
	State     string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type Oauth2Client struct {
	TenantID                           string
	ClientID                           string
	ApplicationID                      pgtype.UUID
	ApplicationProtocolType            string
	ClientSecretHash                   pgtype.Text
	ClientName                         pgtype.Text
	ClientType                         string
	RedirectUris                       []byte
	GrantTypes                         []byte
	ResponseTypes                      []byte
	TokenEndpointAuthMethod            string
	Scope                              string
	JwksUri                            pgtype.Text
	Jwks                               []byte
	TlsClientAuthSubjectDn             pgtype.Text
	IDTokenSignedResponseAlg           string
	RequirePushedAuthorizationRequests bool
	DpopBoundAccessTokens              bool
	FapiProfile                        string
	BackchannelLogoutUri               pgtype.Text
	BackchannelLogoutSessionRequired   bool
	FrontchannelLogoutUri              pgtype.Text
	FrontchannelLogoutSessionRequired  bool
	CreatedAt                          time.Time
	UpdatedAt                          time.Time
	FirstParty                         bool
	ClaimPolicy                        []byte
}

type Oauth2ClientSecret struct {
	ID         string
	ClientID   string
	SecretHash string
	CreatedAt  time.Time
	ExpiresAt  pgtype.Timestamptz
	RevokedAt  pgtype.Timestamptz
}

type Oauth2ClientSession struct {
	TenantID      string
	Sid           string
	ClientID      string
	FirstIssuedAt time.Time
	LastIssuedAt  time.Time
}

type Oauth2LogoutNotification struct {
	ID             string
	TenantID       string
	Sid            string
	ClientID       string
	LogoutTokenJti string
	TargetUri      string
	State          string
	Attempts       int64
	LastError      pgtype.Text
	JobID          pgtype.UUID
	CreatedAt      time.Time
	DeliveredAt    pgtype.Timestamptz
}
