// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: outbox.sql

package db_postgres

import (
	"context"
)

const appendOutboxEvent = `-- name: AppendOutboxEvent :exec
INSERT INTO outbox (event_type, topic, payload)
VALUES ($1, $2, $3)
`

type AppendOutboxEventParams struct {
	EventType string
	Topic     string
	Payload   []byte
}

func (q *Queries) AppendOutboxEvent(ctx context.Context, arg AppendOutboxEventParams) error {
	_, err := q.db.Exec(ctx, appendOutboxEvent, arg.EventType, arg.Topic, arg.Payload)
	return err
}
