// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db_postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AppendOutboxEvent(ctx context.Context, arg AppendOutboxEventParams) error
	DeleteAuthorizationDetailType(ctx context.Context, arg DeleteAuthorizationDetailTypeParams) error
	DeleteClient(ctx context.Context, arg DeleteClientParams) error
	DeleteConsentsForSub(ctx context.Context, userID string) error
	DeleteMcpResourceServer(ctx context.Context, arg DeleteMcpResourceServerParams) error
	DeleteRefreshTokensForSub(ctx context.Context, userID string) error
	GetAuthorizationDetailType(ctx context.Context, arg GetAuthorizationDetailTypeParams) (*AuthorizationDetailType, error)
	GetClientByID(ctx context.Context, arg GetClientByIDParams) (*Oauth2Client, error)
	GetConsent(ctx context.Context, arg GetConsentParams) (*Consent, error)
	GetMcpResourceServer(ctx context.Context, arg GetMcpResourceServerParams) (*McpResourceServer, error)
	GetMcpResourceServerByResource(ctx context.Context, arg GetMcpResourceServerByResourceParams) (*McpResourceServer, error)
	GetRefreshTokenByHash(ctx context.Context, hash string) (*GetRefreshTokenByHashRow, error)
	GetRefreshTokenRotationState(ctx context.Context, id string) (*GetRefreshTokenRotationStateRow, error)
	InsertClientSecretCredential(ctx context.Context, arg InsertClientSecretCredentialParams) error
	InsertRefreshToken(ctx context.Context, arg InsertRefreshTokenParams) error
	ListAuthorizationDetailTypesByTenant(ctx context.Context, tenantID string) ([]*AuthorizationDetailType, error)
	ListClientSecretCredentials(ctx context.Context, clientID string) ([]*Oauth2ClientSecret, error)
	ListClientsByTenant(ctx context.Context, tenantID string) ([]*Oauth2Client, error)
	ListConsentsByTenant(ctx context.Context, tenantID string) ([]*Consent, error)
	ListMcpResourceServersByTenant(ctx context.Context, tenantID string) ([]*McpResourceServer, error)
	MarkRefreshTokenRotated(ctx context.Context, id string) error
	RevokeConsent(ctx context.Context, arg RevokeConsentParams) error
	RevokeRefreshTokenFamily(ctx context.Context, familyID string) error
	RevokeRefreshTokensBySid(ctx context.Context, sid pgtype.UUID) error
	UpdateClientSecretCredential(ctx context.Context, arg UpdateClientSecretCredentialParams) error
	UpsertAuthorizationDetailType(ctx context.Context, arg UpsertAuthorizationDetailTypeParams) error
	UpsertClient(ctx context.Context, arg UpsertClientParams) error
	UpsertConsent(ctx context.Context, arg UpsertConsentParams) error
	UpsertMcpResourceServer(ctx context.Context, arg UpsertMcpResourceServerParams) error
}

var _ Querier = (*Queries)(nil)
