// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db_postgres

import (
	"context"
)

type Querier interface {
	DeleteScimGroupRef(ctx context.Context, arg DeleteScimGroupRefParams) error
	DeleteScimUserRef(ctx context.Context, arg DeleteScimUserRefParams) error
	FindScimGroupRefByGroupID(ctx context.Context, arg FindScimGroupRefByGroupIDParams) (*FindScimGroupRefByGroupIDRow, error)
	FindScimGroupRefByScimID(ctx context.Context, arg FindScimGroupRefByScimIDParams) (*FindScimGroupRefByScimIDRow, error)
	FindScimUserRefByScimID(ctx context.Context, arg FindScimUserRefByScimIDParams) (*FindScimUserRefByScimIDRow, error)
	FindScimUserRefByUserID(ctx context.Context, arg FindScimUserRefByUserIDParams) (*FindScimUserRefByUserIDRow, error)
	// 接続は uuid を text として登録しているが、uuid[] の要素はバイナリで符号化されるため、
	// 配列は text[] で受け取ってから uuid[] にする。
	ListScimGroupRefsByGroupIDs(ctx context.Context, arg ListScimGroupRefsByGroupIDsParams) ([]*ListScimGroupRefsByGroupIDsRow, error)
	// 接続は uuid を text として登録しているが、uuid[] の要素はバイナリで符号化されるため、
	// 配列は text[] で受け取ってから uuid[] にする。
	ListScimUserRefsByUserIDs(ctx context.Context, arg ListScimUserRefsByUserIDsParams) ([]*ListScimUserRefsByUserIDsRow, error)
	SaveScimGroupRef(ctx context.Context, arg SaveScimGroupRefParams) error
	SaveScimUserRef(ctx context.Context, arg SaveScimUserRefParams) error
}

var _ Querier = (*Queries)(nil)
